// Code generated by MockGen. DO NOT EDIT.
// Source: internal\infrastructure\email\email.go
//
// Generated by this command:
//
//	mockgen -source=internal\infrastructure\email\email.go -package=email -destination=internal\infrastructure\email\mock_email.go
//

// Package email is a generated GoMock package.
package email

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockEmailer is a mock of Emailer interface.
type MockEmailer struct {
	ctrl     *gomock.Controller
	recorder *MockEmailerMockRecorder
	isgomock struct{}
}

// MockEmailerMockRecorder is the mock recorder for MockEmailer.
type MockEmailerMockRecorder struct {
	mock *MockEmailer
}

// NewMockEmailer creates a new mock instance.
func NewMockEmailer(ctrl *gomock.Controller) *MockEmailer {
	mock := &MockEmailer{ctrl: ctrl}
	mock.recorder = &MockEmailerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEmailer) EXPECT() *MockEmailerMockRecorder {
	return m.recorder
}

// SendEmail mocks base method.
func (m *MockEmailer) SendEmail(ctx context.Context, to, subject, body string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendEmail", ctx, to, subject, body)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SendEmail indicates an expected call of SendEmail.
func (mr *MockEmailerMockRecorder) SendEmail(ctx, to, subject, body any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendEmail", reflect.TypeOf((*MockEmailer)(nil).SendEmail), ctx, to, subject, body)
}

// SendOTP mocks base method.
func (m *MockEmailer) SendOTP(ctx context.Context, to, otp string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendOTP", ctx, to, otp)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SendOTP indicates an expected call of SendOTP.
func (mr *MockEmailerMockRecorder) SendOTP(ctx, to, otp any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendOTP", reflect.TypeOf((*MockEmailer)(nil).SendOTP), ctx, to, otp)
}
