// Code generated by MockGen. DO NOT EDIT.
// Source: internal/features/analytics/interface.go
//
// Generated by this command:
//
//	mockgen -source=internal/features/analytics/interface.go -destination=internal/features/analytics/mock_interfaces.go -package=analytics
//

// Package analytics is a generated GoMock package.
package analytics

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockServiceInterface is a mock of ServiceInterface interface.
type MockServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockServiceInterfaceMockRecorder
	isgomock struct{}
}

// MockServiceInterfaceMockRecorder is the mock recorder for MockServiceInterface.
type MockServiceInterfaceMockRecorder struct {
	mock *MockServiceInterface
}

// NewMockServiceInterface creates a new mock instance.
func NewMockServiceInterface(ctrl *gomock.Controller) *MockServiceInterface {
	mock := &MockServiceInterface{ctrl: ctrl}
	mock.recorder = &MockServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockServiceInterface) EXPECT() *MockServiceInterfaceMockRecorder {
	return m.recorder
}

// GetAdminDashboard mocks base method.
func (m *MockServiceInterface) GetAdminDashboard(ctx context.Context, timeRange, source string) (*AdminDashboardResponseDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAdminDashboard", ctx, timeRange, source)
	ret0, _ := ret[0].(*AdminDashboardResponseDTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAdminDashboard indicates an expected call of GetAdminDashboard.
func (mr *MockServiceInterfaceMockRecorder) GetAdminDashboard(ctx, timeRange, source any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAdminDashboard", reflect.TypeOf((*MockServiceInterface)(nil).GetAdminDashboard), ctx, timeRange, source)
}

// GetDashboard mocks base method.
func (m *MockServiceInterface) GetDashboard(ctx context.Context, year, courseID int) (*DashboardResponseDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDashboard", ctx, year, courseID)
	ret0, _ := ret[0].(*DashboardResponseDTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDashboard indicates an expected call of GetDashboard.
func (mr *MockServiceInterfaceMockRecorder) GetDashboard(ctx, year, courseID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDashboard", reflect.TypeOf((*MockServiceInterface)(nil).GetDashboard), ctx, year, courseID)
}

// MockRepositoryInterface is a mock of RepositoryInterface interface.
type MockRepositoryInterface struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryInterfaceMockRecorder
	isgomock struct{}
}

// MockRepositoryInterfaceMockRecorder is the mock recorder for MockRepositoryInterface.
type MockRepositoryInterfaceMockRecorder struct {
	mock *MockRepositoryInterface
}

// NewMockRepositoryInterface creates a new mock instance.
func NewMockRepositoryInterface(ctrl *gomock.Controller) *MockRepositoryInterface {
	mock := &MockRepositoryInterface{ctrl: ctrl}
	mock.recorder = &MockRepositoryInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepositoryInterface) EXPECT() *MockRepositoryInterfaceMockRecorder {
	return m.recorder
}

// GetAgeStats mocks base method.
func (m *MockRepositoryInterface) GetAgeStats(ctx context.Context, year, courseID int) ([]DemographicStat, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAgeStats", ctx, year, courseID)
	ret0, _ := ret[0].([]DemographicStat)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAgeStats indicates an expected call of GetAgeStats.
func (mr *MockRepositoryInterfaceMockRecorder) GetAgeStats(ctx, year, courseID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAgeStats", reflect.TypeOf((*MockRepositoryInterface)(nil).GetAgeStats), ctx, year, courseID)
}

// GetCityAddressStats mocks base method.
func (m *MockRepositoryInterface) GetCityAddressStats(ctx context.Context, year, courseID int) ([]DemographicStat, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCityAddressStats", ctx, year, courseID)
	ret0, _ := ret[0].([]DemographicStat)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCityAddressStats indicates an expected call of GetCityAddressStats.
func (mr *MockRepositoryInterfaceMockRecorder) GetCityAddressStats(ctx, year, courseID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCityAddressStats", reflect.TypeOf((*MockRepositoryInterface)(nil).GetCityAddressStats), ctx, year, courseID)
}

// GetCivilStatusStats mocks base method.
func (m *MockRepositoryInterface) GetCivilStatusStats(ctx context.Context, year, courseID int) ([]DemographicStat, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCivilStatusStats", ctx, year, courseID)
	ret0, _ := ret[0].([]DemographicStat)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCivilStatusStats indicates an expected call of GetCivilStatusStats.
func (mr *MockRepositoryInterfaceMockRecorder) GetCivilStatusStats(ctx, year, courseID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCivilStatusStats", reflect.TypeOf((*MockRepositoryInterface)(nil).GetCivilStatusStats), ctx, year, courseID)
}

// GetElementaryStats mocks base method.
func (m *MockRepositoryInterface) GetElementaryStats(ctx context.Context, year, courseID int) ([]DemographicStat, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetElementaryStats", ctx, year, courseID)
	ret0, _ := ret[0].([]DemographicStat)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetElementaryStats indicates an expected call of GetElementaryStats.
func (mr *MockRepositoryInterfaceMockRecorder) GetElementaryStats(ctx, year, courseID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetElementaryStats", reflect.TypeOf((*MockRepositoryInterface)(nil).GetElementaryStats), ctx, year, courseID)
}

// GetFatherEducationStats mocks base method.
func (m *MockRepositoryInterface) GetFatherEducationStats(ctx context.Context, year, courseID int) ([]DemographicStat, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFatherEducationStats", ctx, year, courseID)
	ret0, _ := ret[0].([]DemographicStat)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFatherEducationStats indicates an expected call of GetFatherEducationStats.
func (mr *MockRepositoryInterfaceMockRecorder) GetFatherEducationStats(ctx, year, courseID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFatherEducationStats", reflect.TypeOf((*MockRepositoryInterface)(nil).GetFatherEducationStats), ctx, year, courseID)
}

// GetGenderStats mocks base method.
func (m *MockRepositoryInterface) GetGenderStats(ctx context.Context, year, courseID int) ([]DemographicStat, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGenderStats", ctx, year, courseID)
	ret0, _ := ret[0].([]DemographicStat)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGenderStats indicates an expected call of GetGenderStats.
func (mr *MockRepositoryInterfaceMockRecorder) GetGenderStats(ctx, year, courseID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGenderStats", reflect.TypeOf((*MockRepositoryInterface)(nil).GetGenderStats), ctx, year, courseID)
}

// GetHSGWAStats mocks base method.
func (m *MockRepositoryInterface) GetHSGWAStats(ctx context.Context, year, courseID int) ([]DemographicStat, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHSGWAStats", ctx, year, courseID)
	ret0, _ := ret[0].([]DemographicStat)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetHSGWAStats indicates an expected call of GetHSGWAStats.
func (mr *MockRepositoryInterfaceMockRecorder) GetHSGWAStats(ctx, year, courseID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHSGWAStats", reflect.TypeOf((*MockRepositoryInterface)(nil).GetHSGWAStats), ctx, year, courseID)
}

// GetJuniorHighStats mocks base method.
func (m *MockRepositoryInterface) GetJuniorHighStats(ctx context.Context, year, courseID int) ([]DemographicStat, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetJuniorHighStats", ctx, year, courseID)
	ret0, _ := ret[0].([]DemographicStat)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetJuniorHighStats indicates an expected call of GetJuniorHighStats.
func (mr *MockRepositoryInterfaceMockRecorder) GetJuniorHighStats(ctx, year, courseID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetJuniorHighStats", reflect.TypeOf((*MockRepositoryInterface)(nil).GetJuniorHighStats), ctx, year, courseID)
}

// GetMonthlyAppointmentStats mocks base method.
func (m *MockRepositoryInterface) GetMonthlyAppointmentStats(ctx context.Context, timeRange string) ([]MonthlyVisitorStatDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMonthlyAppointmentStats", ctx, timeRange)
	ret0, _ := ret[0].([]MonthlyVisitorStatDTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMonthlyAppointmentStats indicates an expected call of GetMonthlyAppointmentStats.
func (mr *MockRepositoryInterfaceMockRecorder) GetMonthlyAppointmentStats(ctx, timeRange any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMonthlyAppointmentStats", reflect.TypeOf((*MockRepositoryInterface)(nil).GetMonthlyAppointmentStats), ctx, timeRange)
}

// GetMonthlyIncomeStats mocks base method.
func (m *MockRepositoryInterface) GetMonthlyIncomeStats(ctx context.Context, year, courseID int) ([]DemographicStat, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMonthlyIncomeStats", ctx, year, courseID)
	ret0, _ := ret[0].([]DemographicStat)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMonthlyIncomeStats indicates an expected call of GetMonthlyIncomeStats.
func (mr *MockRepositoryInterfaceMockRecorder) GetMonthlyIncomeStats(ctx, year, courseID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMonthlyIncomeStats", reflect.TypeOf((*MockRepositoryInterface)(nil).GetMonthlyIncomeStats), ctx, year, courseID)
}

// GetMonthlyVisitorStats mocks base method.
func (m *MockRepositoryInterface) GetMonthlyVisitorStats(ctx context.Context, timeRange string) ([]MonthlyVisitorStatDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMonthlyVisitorStats", ctx, timeRange)
	ret0, _ := ret[0].([]MonthlyVisitorStatDTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMonthlyVisitorStats indicates an expected call of GetMonthlyVisitorStats.
func (mr *MockRepositoryInterfaceMockRecorder) GetMonthlyVisitorStats(ctx, timeRange any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMonthlyVisitorStats", reflect.TypeOf((*MockRepositoryInterface)(nil).GetMonthlyVisitorStats), ctx, timeRange)
}

// GetMotherEducationStats mocks base method.
func (m *MockRepositoryInterface) GetMotherEducationStats(ctx context.Context, year, courseID int) ([]DemographicStat, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMotherEducationStats", ctx, year, courseID)
	ret0, _ := ret[0].([]DemographicStat)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMotherEducationStats indicates an expected call of GetMotherEducationStats.
func (mr *MockRepositoryInterfaceMockRecorder) GetMotherEducationStats(ctx, year, courseID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMotherEducationStats", reflect.TypeOf((*MockRepositoryInterface)(nil).GetMotherEducationStats), ctx, year, courseID)
}

// GetNatureOfSchoolingStats mocks base method.
func (m *MockRepositoryInterface) GetNatureOfSchoolingStats(ctx context.Context, year, courseID int) ([]DemographicStat, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNatureOfSchoolingStats", ctx, year, courseID)
	ret0, _ := ret[0].([]DemographicStat)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNatureOfSchoolingStats indicates an expected call of GetNatureOfSchoolingStats.
func (mr *MockRepositoryInterfaceMockRecorder) GetNatureOfSchoolingStats(ctx, year, courseID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNatureOfSchoolingStats", reflect.TypeOf((*MockRepositoryInterface)(nil).GetNatureOfSchoolingStats), ctx, year, courseID)
}

// GetOrdinalPositionStats mocks base method.
func (m *MockRepositoryInterface) GetOrdinalPositionStats(ctx context.Context, year, courseID int) ([]DemographicStat, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrdinalPositionStats", ctx, year, courseID)
	ret0, _ := ret[0].([]DemographicStat)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrdinalPositionStats indicates an expected call of GetOrdinalPositionStats.
func (mr *MockRepositoryInterfaceMockRecorder) GetOrdinalPositionStats(ctx, year, courseID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrdinalPositionStats", reflect.TypeOf((*MockRepositoryInterface)(nil).GetOrdinalPositionStats), ctx, year, courseID)
}

// GetParentsMaritalStatusStats mocks base method.
func (m *MockRepositoryInterface) GetParentsMaritalStatusStats(ctx context.Context, year, courseID int) ([]DemographicStat, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetParentsMaritalStatusStats", ctx, year, courseID)
	ret0, _ := ret[0].([]DemographicStat)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetParentsMaritalStatusStats indicates an expected call of GetParentsMaritalStatusStats.
func (mr *MockRepositoryInterfaceMockRecorder) GetParentsMaritalStatusStats(ctx, year, courseID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetParentsMaritalStatusStats", reflect.TypeOf((*MockRepositoryInterface)(nil).GetParentsMaritalStatusStats), ctx, year, courseID)
}

// GetQuietStudyPlaceStats mocks base method.
func (m *MockRepositoryInterface) GetQuietStudyPlaceStats(ctx context.Context, year, courseID int) ([]DemographicStat, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetQuietStudyPlaceStats", ctx, year, courseID)
	ret0, _ := ret[0].([]DemographicStat)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetQuietStudyPlaceStats indicates an expected call of GetQuietStudyPlaceStats.
func (mr *MockRepositoryInterfaceMockRecorder) GetQuietStudyPlaceStats(ctx, year, courseID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetQuietStudyPlaceStats", reflect.TypeOf((*MockRepositoryInterface)(nil).GetQuietStudyPlaceStats), ctx, year, courseID)
}

// GetReligionStats mocks base method.
func (m *MockRepositoryInterface) GetReligionStats(ctx context.Context, year, courseID int) ([]DemographicStat, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetReligionStats", ctx, year, courseID)
	ret0, _ := ret[0].([]DemographicStat)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetReligionStats indicates an expected call of GetReligionStats.
func (mr *MockRepositoryInterfaceMockRecorder) GetReligionStats(ctx, year, courseID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetReligionStats", reflect.TypeOf((*MockRepositoryInterface)(nil).GetReligionStats), ctx, year, courseID)
}

// GetSeniorHighStats mocks base method.
func (m *MockRepositoryInterface) GetSeniorHighStats(ctx context.Context, year, courseID int) ([]DemographicStat, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSeniorHighStats", ctx, year, courseID)
	ret0, _ := ret[0].([]DemographicStat)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSeniorHighStats indicates an expected call of GetSeniorHighStats.
func (mr *MockRepositoryInterfaceMockRecorder) GetSeniorHighStats(ctx, year, courseID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSeniorHighStats", reflect.TypeOf((*MockRepositoryInterface)(nil).GetSeniorHighStats), ctx, year, courseID)
}

// GetTotalAppointments mocks base method.
func (m *MockRepositoryInterface) GetTotalAppointments(ctx context.Context) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTotalAppointments", ctx)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTotalAppointments indicates an expected call of GetTotalAppointments.
func (mr *MockRepositoryInterfaceMockRecorder) GetTotalAppointments(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTotalAppointments", reflect.TypeOf((*MockRepositoryInterface)(nil).GetTotalAppointments), ctx)
}

// GetTotalReports mocks base method.
func (m *MockRepositoryInterface) GetTotalReports(ctx context.Context) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTotalReports", ctx)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTotalReports indicates an expected call of GetTotalReports.
func (mr *MockRepositoryInterfaceMockRecorder) GetTotalReports(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTotalReports", reflect.TypeOf((*MockRepositoryInterface)(nil).GetTotalReports), ctx)
}

// GetTotalSlips mocks base method.
func (m *MockRepositoryInterface) GetTotalSlips(ctx context.Context) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTotalSlips", ctx)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTotalSlips indicates an expected call of GetTotalSlips.
func (mr *MockRepositoryInterfaceMockRecorder) GetTotalSlips(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTotalSlips", reflect.TypeOf((*MockRepositoryInterface)(nil).GetTotalSlips), ctx)
}

// GetTotalStudents mocks base method.
func (m *MockRepositoryInterface) GetTotalStudents(ctx context.Context, year, courseID int) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTotalStudents", ctx, year, courseID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTotalStudents indicates an expected call of GetTotalStudents.
func (mr *MockRepositoryInterfaceMockRecorder) GetTotalStudents(ctx, year, courseID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTotalStudents", reflect.TypeOf((*MockRepositoryInterface)(nil).GetTotalStudents), ctx, year, courseID)
}
