version: "3.8"

services:
  api:
    image: olazojohnalbert/capstone-gin-api:latest
    ports:
      - "80:8080"
    depends_on:
      - redis
    networks:
      - app-network

  redis:
    image: redis/redis-stack-server:latest
    container_name: capstone-redis
    ports:
      - "6379:6379"
    command: >
      redis-server
      --requirepass "${REDIS_PASS}"
      --stop-writes-on-bgsave-error no
    restart: always
    networks:
      - app-network
    volumes:
      - redis-data:/data

  gotenberg:
    image: gotenberg/gotenberg:8
    container_name: capstone-gotenberg
    restart: always
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  redis-data:
