version: "3.8"

services:
    redis:
        image: redis:alpine
        container_name: capstone-redis
        deploy:
            resources:
                limits:
                    cpus: "0.25"
                    memory: 256M
        healthcheck:
            test: [ "CMD", "redis-cli", "ping" ]
            interval: 5s
            timeout: 3s
            retries: 5
        ports:
            - "${REDIS_PORT}:6379"
        networks:
            - app-network
        volumes:
            - redis-data:/data

    mysql:
        image: mysql:8.0
        container_name: capstone-mysql
        deploy:
            resources:
                limits:
                    cpus: "1.0"
                    memory: 1024M
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASS}
            MYSQL_DATABASE: ${DB_NAME}
            MYSQL_USER: ${DB_USER}
            MYSQL_PASSWORD: ${DB_PASS}
        healthcheck:
            test: [ "CMD", "${DB_USER}", "ping", "-h", "${DB_HOST}", "-u${DB_USER}", "-p${DB_PASS}" ]
            interval: 10s
            timeout: 5s
            retries: 5
        ports:
            - "3307:3306"
        networks:
            - app-network
        volumes:
            - mysql-data:/var/lib/mysql

    gotenberg:
        image: gotenberg/gotenberg:8
        container_name: capstone-gotenberg
        deploy:
            resources:
                limits:
                    cpus: "0.5"
                    memory: 512M
        ports:
            - "3001:3000"
        networks:
            - app-network

    mailpit:
        image: axllent/mailpit:latest
        container_name: capstone-mailpit
        deploy:
            resources:
                limits:
                    cpus: "0.25"
                    memory: 256M
        ports:
            - "1025:1025"
            - "8025:8025"
        networks:
            - app-network

networks:
    app-network:
        driver: bridge

volumes:
    mysql-data:
    redis-data:
