version: "3.8"

services:
  api:
    image: olazojohnalbert/capstone-gin-api:latest
    ports:
      - "80:8080"
    depends_on:
      - redis
    networks:
      - app-network

  redis:
    image: redis:alpine
    container_name: capstone-redis
    restart: always
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
