// Code generated by MockGen. DO NOT EDIT.
// Source: internal/features/notifications/interface.go
//
// Generated by this command:
//
//	mockgen -source=internal/features/notifications/interface.go -destination=internal/features/notifications/mock_interfaces.go -package=notifications
//

// Package notifications is a generated GoMock package.
package notifications

import (
	context "context"
	reflect "reflect"

	audit "github.com/olazo-johnalbert/duckload-api/internal/core/audit"
	datastore "github.com/olazo-johnalbert/duckload-api/internal/infrastructure/datastore"
	gomock "go.uber.org/mock/gomock"
)

// MockServiceInterface is a mock of ServiceInterface interface.
type MockServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockServiceInterfaceMockRecorder
	isgomock struct{}
}

// MockServiceInterfaceMockRecorder is the mock recorder for MockServiceInterface.
type MockServiceInterfaceMockRecorder struct {
	mock *MockServiceInterface
}

// NewMockServiceInterface creates a new mock instance.
func NewMockServiceInterface(ctrl *gomock.Controller) *MockServiceInterface {
	mock := &MockServiceInterface{ctrl: ctrl}
	mock.recorder = &MockServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockServiceInterface) EXPECT() *MockServiceInterfaceMockRecorder {
	return m.recorder
}

// GetUserNotifications mocks base method.
func (m *MockServiceInterface) GetUserNotifications(ctx context.Context, userID string) ([]audit.NotificationEntry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserNotifications", ctx, userID)
	ret0, _ := ret[0].([]audit.NotificationEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserNotifications indicates an expected call of GetUserNotifications.
func (mr *MockServiceInterfaceMockRecorder) GetUserNotifications(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserNotifications", reflect.TypeOf((*MockServiceInterface)(nil).GetUserNotifications), ctx, userID)
}

// MarkAsRead mocks base method.
func (m *MockServiceInterface) MarkAsRead(ctx context.Context, id, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkAsRead", ctx, id, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkAsRead indicates an expected call of MarkAsRead.
func (mr *MockServiceInterfaceMockRecorder) MarkAsRead(ctx, id, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkAsRead", reflect.TypeOf((*MockServiceInterface)(nil).MarkAsRead), ctx, id, userID)
}

// Subscribe mocks base method.
func (m *MockServiceInterface) Subscribe(ctx context.Context, userID string) (<-chan audit.NotificationEntry, func()) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Subscribe", ctx, userID)
	ret0, _ := ret[0].(<-chan audit.NotificationEntry)
	ret1, _ := ret[1].(func())
	return ret0, ret1
}

// Subscribe indicates an expected call of Subscribe.
func (mr *MockServiceInterfaceMockRecorder) Subscribe(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Subscribe", reflect.TypeOf((*MockServiceInterface)(nil).Subscribe), ctx, userID)
}

// Unsubscribe mocks base method.
func (m *MockServiceInterface) Unsubscribe(ctx context.Context, userID string, ch chan audit.NotificationEntry) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Unsubscribe", ctx, userID, ch)
}

// Unsubscribe indicates an expected call of Unsubscribe.
func (mr *MockServiceInterfaceMockRecorder) Unsubscribe(ctx, userID, ch any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Unsubscribe", reflect.TypeOf((*MockServiceInterface)(nil).Unsubscribe), ctx, userID, ch)
}

// Broadcast mocks base method.
func (m *MockServiceInterface) Broadcast(ctx context.Context, notif audit.NotificationEntry) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Broadcast", ctx, notif)
	ret0, _ := ret[0].(error)
	return ret0
}

// Broadcast indicates an expected call of Broadcast.
func (mr *MockServiceInterfaceMockRecorder) Broadcast(ctx, notif any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Broadcast", reflect.TypeOf((*MockServiceInterface)(nil).Broadcast), ctx, notif)
}

// DeleteOldNotifications mocks base method.
func (m *MockServiceInterface) DeleteOldNotifications(ctx context.Context, days int) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteOldNotifications", ctx, days)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteOldNotifications indicates an expected call of DeleteOldNotifications.
func (mr *MockServiceInterfaceMockRecorder) DeleteOldNotifications(ctx, days any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteOldNotifications", reflect.TypeOf((*MockServiceInterface)(nil).DeleteOldNotifications), ctx, days)
}

// Send mocks base method.
func (m *MockServiceInterface) Send(ctx context.Context, notif audit.NotificationEntry) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Send", ctx, notif)
	ret0, _ := ret[0].(error)
	return ret0
}

// Send indicates an expected call of Send.
func (mr *MockServiceInterfaceMockRecorder) Send(ctx, notif any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockServiceInterface)(nil).Send), ctx, notif)
}

// MockRepositoryInterface is a mock of RepositoryInterface interface.
type MockRepositoryInterface struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryInterfaceMockRecorder
	isgomock struct{}
}

// MockRepositoryInterfaceMockRecorder is the mock recorder for MockRepositoryInterface.
type MockRepositoryInterfaceMockRecorder struct {
	mock *MockRepositoryInterface
}

// NewMockRepositoryInterface creates a new mock instance.
func NewMockRepositoryInterface(ctrl *gomock.Controller) *MockRepositoryInterface {
	mock := &MockRepositoryInterface{ctrl: ctrl}
	mock.recorder = &MockRepositoryInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepositoryInterface) EXPECT() *MockRepositoryInterfaceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockRepositoryInterface) Create(ctx context.Context, tx datastore.DB, notif Notification) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, tx, notif)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockRepositoryInterfaceMockRecorder) Create(ctx, tx, notif any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRepositoryInterface)(nil).Create), ctx, tx, notif)
}

// GetByUserID mocks base method.
func (m *MockRepositoryInterface) GetByUserID(ctx context.Context, userID string) ([]Notification, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUserID", ctx, userID)
	ret0, _ := ret[0].([]Notification)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByUserID indicates an expected call of GetByUserID.
func (mr *MockRepositoryInterfaceMockRecorder) GetByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUserID", reflect.TypeOf((*MockRepositoryInterface)(nil).GetByUserID), ctx, userID)
}

// MarkAsRead mocks base method.
func (m *MockRepositoryInterface) MarkAsRead(ctx context.Context, tx datastore.DB, id, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkAsRead", ctx, tx, id, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkAsRead indicates an expected call of MarkAsRead.
func (mr *MockRepositoryInterfaceMockRecorder) MarkAsRead(ctx, tx, id, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkAsRead", reflect.TypeOf((*MockRepositoryInterface)(nil).MarkAsRead), ctx, tx, id, userID)
}

// DeleteOldNotifications mocks base method.
func (m *MockRepositoryInterface) DeleteOldNotifications(ctx context.Context, days int) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteOldNotifications", ctx, days)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteOldNotifications indicates an expected call of DeleteOldNotifications.
func (mr *MockRepositoryInterfaceMockRecorder) DeleteOldNotifications(ctx, days any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteOldNotifications", reflect.TypeOf((*MockRepositoryInterface)(nil).DeleteOldNotifications), ctx, days)
}

// WithTransaction mocks base method.
func (m *MockRepositoryInterface) WithTransaction(ctx context.Context, fn func(datastore.DB) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithTransaction", ctx, fn)
	ret0, _ := ret[0].(error)
	return ret0
}

// WithTransaction indicates an expected call of WithTransaction.
func (mr *MockRepositoryInterfaceMockRecorder) WithTransaction(ctx, fn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithTransaction", reflect.TypeOf((*MockRepositoryInterface)(nil).WithTransaction), ctx, fn)
}
