// Code generated by MockGen. DO NOT EDIT.
// Source: internal/features/users/interface.go
//
// Generated by this command:
//
//	mockgen -source=internal/features/users/interface.go -package=users -destination=internal/features/users/mock_interfaces.go
//

// Package users is a generated GoMock package.
package users

import (
	context "context"
	reflect "reflect"

	sqlx "github.com/jmoiron/sqlx"
	datastore "github.com/olazo-johnalbert/duckload-api/internal/infrastructure/datastore"
	gomock "go.uber.org/mock/gomock"
)

// MockServiceInterface is a mock of ServiceInterface interface.
type MockServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockServiceInterfaceMockRecorder
	isgomock struct{}
}

// MockServiceInterfaceMockRecorder is the mock recorder for MockServiceInterface.
type MockServiceInterfaceMockRecorder struct {
	mock *MockServiceInterface
}

// NewMockServiceInterface creates a new mock instance.
func NewMockServiceInterface(ctrl *gomock.Controller) *MockServiceInterface {
	mock := &MockServiceInterface{ctrl: ctrl}
	mock.recorder = &MockServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockServiceInterface) EXPECT() *MockServiceInterfaceMockRecorder {
	return m.recorder
}

// AddUserToWhitelist mocks base method.
func (m *MockServiceInterface) AddUserToWhitelist(ctx context.Context, req AddUserToWhitelistRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddUserToWhitelist", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddUserToWhitelist indicates an expected call of AddUserToWhitelist.
func (mr *MockServiceInterfaceMockRecorder) AddUserToWhitelist(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddUserToWhitelist", reflect.TypeOf((*MockServiceInterface)(nil).AddUserToWhitelist), ctx, req)
}

// BlockUser mocks base method.
func (m *MockServiceInterface) BlockUser(ctx context.Context, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BlockUser", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// BlockUser indicates an expected call of BlockUser.
func (mr *MockServiceInterfaceMockRecorder) BlockUser(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BlockUser", reflect.TypeOf((*MockServiceInterface)(nil).BlockUser), ctx, userID)
}

// GetRoleDistribution mocks base method.
func (m *MockServiceInterface) GetRoleDistribution(ctx context.Context) ([]RoleDistributionDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRoleDistribution", ctx)
	ret0, _ := ret[0].([]RoleDistributionDTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRoleDistribution indicates an expected call of GetRoleDistribution.
func (mr *MockServiceInterfaceMockRecorder) GetRoleDistribution(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRoleDistribution", reflect.TypeOf((*MockServiceInterface)(nil).GetRoleDistribution), ctx)
}

// GetUserByEmail mocks base method.
func (m *MockServiceInterface) GetUserByEmail(ctx context.Context, email, authType string) (*GetUserResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByEmail", ctx, email, authType)
	ret0, _ := ret[0].(*GetUserResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByEmail indicates an expected call of GetUserByEmail.
func (mr *MockServiceInterfaceMockRecorder) GetUserByEmail(ctx, email, authType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByEmail", reflect.TypeOf((*MockServiceInterface)(nil).GetUserByEmail), ctx, email, authType)
}

// GetUserByID mocks base method.
func (m *MockServiceInterface) GetUserByID(ctx context.Context, userID string) (*GetUserResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByID", ctx, userID)
	ret0, _ := ret[0].(*GetUserResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByID indicates an expected call of GetUserByID.
func (mr *MockServiceInterfaceMockRecorder) GetUserByID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByID", reflect.TypeOf((*MockServiceInterface)(nil).GetUserByID), ctx, userID)
}

// GetUserIDsByRole mocks base method.
func (m *MockServiceInterface) GetUserIDsByRole(ctx context.Context, roleID int) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserIDsByRole", ctx, roleID)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserIDsByRole indicates an expected call of GetUserIDsByRole.
func (mr *MockServiceInterfaceMockRecorder) GetUserIDsByRole(ctx, roleID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserIDsByRole", reflect.TypeOf((*MockServiceInterface)(nil).GetUserIDsByRole), ctx, roleID)
}

// ListUsers mocks base method.
func (m *MockServiceInterface) ListUsers(ctx context.Context, params ListUsersParams) (*ListUsersResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListUsers", ctx, params)
	ret0, _ := ret[0].(*ListUsersResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListUsers indicates an expected call of ListUsers.
func (mr *MockServiceInterfaceMockRecorder) ListUsers(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListUsers", reflect.TypeOf((*MockServiceInterface)(nil).ListUsers), ctx, params)
}

// PostProfilePicture mocks base method.
func (m *MockServiceInterface) PostProfilePicture(ctx context.Context, userID, fileID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PostProfilePicture", ctx, userID, fileID)
	ret0, _ := ret[0].(error)
	return ret0
}

// PostProfilePicture indicates an expected call of PostProfilePicture.
func (mr *MockServiceInterfaceMockRecorder) PostProfilePicture(ctx, userID, fileID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PostProfilePicture", reflect.TypeOf((*MockServiceInterface)(nil).PostProfilePicture), ctx, userID, fileID)
}

// RemoveUserFromWhitelist mocks base method.
func (m *MockServiceInterface) RemoveUserFromWhitelist(ctx context.Context, req RemoveUserFromWhitelistRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveUserFromWhitelist", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveUserFromWhitelist indicates an expected call of RemoveUserFromWhitelist.
func (mr *MockServiceInterfaceMockRecorder) RemoveUserFromWhitelist(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveUserFromWhitelist", reflect.TypeOf((*MockServiceInterface)(nil).RemoveUserFromWhitelist), ctx, req)
}

// UnblockUser mocks base method.
func (m *MockServiceInterface) UnblockUser(ctx context.Context, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnblockUser", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// UnblockUser indicates an expected call of UnblockUser.
func (mr *MockServiceInterfaceMockRecorder) UnblockUser(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnblockUser", reflect.TypeOf((*MockServiceInterface)(nil).UnblockUser), ctx, userID)
}

// UpdateUserRoles mocks base method.
func (m *MockServiceInterface) UpdateUserRoles(ctx context.Context, req UpdateRolesRequest, adminID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUserRoles", ctx, req, adminID)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateUserRoles indicates an expected call of UpdateUserRoles.
func (mr *MockServiceInterfaceMockRecorder) UpdateUserRoles(ctx, req, adminID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUserRoles", reflect.TypeOf((*MockServiceInterface)(nil).UpdateUserRoles), ctx, req, adminID)
}

// MockRepositoryInterface is a mock of RepositoryInterface interface.
type MockRepositoryInterface struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryInterfaceMockRecorder
	isgomock struct{}
}

// MockRepositoryInterfaceMockRecorder is the mock recorder for MockRepositoryInterface.
type MockRepositoryInterfaceMockRecorder struct {
	mock *MockRepositoryInterface
}

// NewMockRepositoryInterface creates a new mock instance.
func NewMockRepositoryInterface(ctrl *gomock.Controller) *MockRepositoryInterface {
	mock := &MockRepositoryInterface{ctrl: ctrl}
	mock.recorder = &MockRepositoryInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepositoryInterface) EXPECT() *MockRepositoryInterfaceMockRecorder {
	return m.recorder
}

// AddUserToWhitelist mocks base method.
func (m *MockRepositoryInterface) AddUserToWhitelist(ctx context.Context, tx datastore.DB, email string, roleID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddUserToWhitelist", ctx, tx, email, roleID)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddUserToWhitelist indicates an expected call of AddUserToWhitelist.
func (mr *MockRepositoryInterfaceMockRecorder) AddUserToWhitelist(ctx, tx, email, roleID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddUserToWhitelist", reflect.TypeOf((*MockRepositoryInterface)(nil).AddUserToWhitelist), ctx, tx, email, roleID)
}

// AssignRole mocks base method.
func (m *MockRepositoryInterface) AssignRole(ctx context.Context, tx datastore.DB, assignment RoleAssignment) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AssignRole", ctx, tx, assignment)
	ret0, _ := ret[0].(error)
	return ret0
}

// AssignRole indicates an expected call of AssignRole.
func (mr *MockRepositoryInterfaceMockRecorder) AssignRole(ctx, tx, assignment any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AssignRole", reflect.TypeOf((*MockRepositoryInterface)(nil).AssignRole), ctx, tx, assignment)
}

// BlockUser mocks base method.
func (m *MockRepositoryInterface) BlockUser(ctx context.Context, tx datastore.DB, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BlockUser", ctx, tx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// BlockUser indicates an expected call of BlockUser.
func (mr *MockRepositoryInterfaceMockRecorder) BlockUser(ctx, tx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BlockUser", reflect.TypeOf((*MockRepositoryInterface)(nil).BlockUser), ctx, tx, userID)
}

// CheckUserWhitelist mocks base method.
func (m *MockRepositoryInterface) CheckUserWhitelist(ctx context.Context, email string) ([]int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckUserWhitelist", ctx, email)
	ret0, _ := ret[0].([]int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckUserWhitelist indicates an expected call of CheckUserWhitelist.
func (mr *MockRepositoryInterfaceMockRecorder) CheckUserWhitelist(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckUserWhitelist", reflect.TypeOf((*MockRepositoryInterface)(nil).CheckUserWhitelist), ctx, email)
}

// CreateUser mocks base method.
func (m *MockRepositoryInterface) CreateUser(ctx context.Context, tx datastore.DB, user User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", ctx, tx, user)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockRepositoryInterfaceMockRecorder) CreateUser(ctx, tx, user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockRepositoryInterface)(nil).CreateUser), ctx, tx, user)
}

// GetDB mocks base method.
func (m *MockRepositoryInterface) GetDB() *sqlx.DB {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDB")
	ret0, _ := ret[0].(*sqlx.DB)
	return ret0
}

// GetDB indicates an expected call of GetDB.
func (mr *MockRepositoryInterfaceMockRecorder) GetDB() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDB", reflect.TypeOf((*MockRepositoryInterface)(nil).GetDB))
}

// GetRoleByID mocks base method.
func (m *MockRepositoryInterface) GetRoleByID(ctx context.Context, roleID int) (*Role, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRoleByID", ctx, roleID)
	ret0, _ := ret[0].(*Role)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRoleByID indicates an expected call of GetRoleByID.
func (mr *MockRepositoryInterfaceMockRecorder) GetRoleByID(ctx, roleID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRoleByID", reflect.TypeOf((*MockRepositoryInterface)(nil).GetRoleByID), ctx, roleID)
}

// GetRoleDistribution mocks base method.
func (m *MockRepositoryInterface) GetRoleDistribution(ctx context.Context) ([]RoleDistributionDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRoleDistribution", ctx)
	ret0, _ := ret[0].([]RoleDistributionDTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRoleDistribution indicates an expected call of GetRoleDistribution.
func (mr *MockRepositoryInterfaceMockRecorder) GetRoleDistribution(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRoleDistribution", reflect.TypeOf((*MockRepositoryInterface)(nil).GetRoleDistribution), ctx)
}

// GetRolesByUserID mocks base method.
func (m *MockRepositoryInterface) GetRolesByUserID(ctx context.Context, userID string) ([]Role, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRolesByUserID", ctx, userID)
	ret0, _ := ret[0].([]Role)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRolesByUserID indicates an expected call of GetRolesByUserID.
func (mr *MockRepositoryInterfaceMockRecorder) GetRolesByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRolesByUserID", reflect.TypeOf((*MockRepositoryInterface)(nil).GetRolesByUserID), ctx, userID)
}

// GetUserByEmail mocks base method.
func (m *MockRepositoryInterface) GetUserByEmail(ctx context.Context, email, authType string) (*User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByEmail", ctx, email, authType)
	ret0, _ := ret[0].(*User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByEmail indicates an expected call of GetUserByEmail.
func (mr *MockRepositoryInterfaceMockRecorder) GetUserByEmail(ctx, email, authType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByEmail", reflect.TypeOf((*MockRepositoryInterface)(nil).GetUserByEmail), ctx, email, authType)
}

// GetUserByID mocks base method.
func (m *MockRepositoryInterface) GetUserByID(ctx context.Context, userID string) (*User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByID", ctx, userID)
	ret0, _ := ret[0].(*User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByID indicates an expected call of GetUserByID.
func (mr *MockRepositoryInterfaceMockRecorder) GetUserByID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByID", reflect.TypeOf((*MockRepositoryInterface)(nil).GetUserByID), ctx, userID)
}

// GetUserIDsByRole mocks base method.
func (m *MockRepositoryInterface) GetUserIDsByRole(ctx context.Context, roleID int) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserIDsByRole", ctx, roleID)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserIDsByRole indicates an expected call of GetUserIDsByRole.
func (mr *MockRepositoryInterfaceMockRecorder) GetUserIDsByRole(ctx, roleID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserIDsByRole", reflect.TypeOf((*MockRepositoryInterface)(nil).GetUserIDsByRole), ctx, roleID)
}

// ListUsers mocks base method.
func (m *MockRepositoryInterface) ListUsers(ctx context.Context, params ListUsersParams) ([]User, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListUsers", ctx, params)
	ret0, _ := ret[0].([]User)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListUsers indicates an expected call of ListUsers.
func (mr *MockRepositoryInterfaceMockRecorder) ListUsers(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListUsers", reflect.TypeOf((*MockRepositoryInterface)(nil).ListUsers), ctx, params)
}

// PostProfilePicture mocks base method.
func (m *MockRepositoryInterface) PostProfilePicture(ctx context.Context, tx datastore.DB, userID, fileID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PostProfilePicture", ctx, tx, userID, fileID)
	ret0, _ := ret[0].(error)
	return ret0
}

// PostProfilePicture indicates an expected call of PostProfilePicture.
func (mr *MockRepositoryInterfaceMockRecorder) PostProfilePicture(ctx, tx, userID, fileID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PostProfilePicture", reflect.TypeOf((*MockRepositoryInterface)(nil).PostProfilePicture), ctx, tx, userID, fileID)
}

// RemoveRoles mocks base method.
func (m *MockRepositoryInterface) RemoveRoles(ctx context.Context, tx datastore.DB, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveRoles", ctx, tx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveRoles indicates an expected call of RemoveRoles.
func (mr *MockRepositoryInterfaceMockRecorder) RemoveRoles(ctx, tx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveRoles", reflect.TypeOf((*MockRepositoryInterface)(nil).RemoveRoles), ctx, tx, userID)
}

// RemoveUserFromWhitelist mocks base method.
func (m *MockRepositoryInterface) RemoveUserFromWhitelist(ctx context.Context, tx datastore.DB, email string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveUserFromWhitelist", ctx, tx, email)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveUserFromWhitelist indicates an expected call of RemoveUserFromWhitelist.
func (mr *MockRepositoryInterfaceMockRecorder) RemoveUserFromWhitelist(ctx, tx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveUserFromWhitelist", reflect.TypeOf((*MockRepositoryInterface)(nil).RemoveUserFromWhitelist), ctx, tx, email)
}

// UnblockUser mocks base method.
func (m *MockRepositoryInterface) UnblockUser(ctx context.Context, tx datastore.DB, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnblockUser", ctx, tx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// UnblockUser indicates an expected call of UnblockUser.
func (mr *MockRepositoryInterfaceMockRecorder) UnblockUser(ctx, tx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnblockUser", reflect.TypeOf((*MockRepositoryInterface)(nil).UnblockUser), ctx, tx, userID)
}

// WithTransaction mocks base method.
func (m *MockRepositoryInterface) WithTransaction(ctx context.Context, fn func(datastore.DB) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithTransaction", ctx, fn)
	ret0, _ := ret[0].(error)
	return ret0
}

// WithTransaction indicates an expected call of WithTransaction.
func (mr *MockRepositoryInterfaceMockRecorder) WithTransaction(ctx, fn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithTransaction", reflect.TypeOf((*MockRepositoryInterface)(nil).WithTransaction), ctx, fn)
}
