// Code generated by MockGen. DO NOT EDIT.
// Source: internal\features\notes\interface.go
//
// Generated by this command:
//
//	mockgen -source=internal\features\notes\interface.go -package=notes -destination=internal\features\notes\mock_interfaces.go
//

// Package notes is a generated GoMock package.
package notes

import (
	context "context"
	reflect "reflect"

	datastore "github.com/olazo-johnalbert/duckload-api/internal/infrastructure/datastore"
	gomock "go.uber.org/mock/gomock"
)

// MockServiceInterface is a mock of ServiceInterface interface.
type MockServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockServiceInterfaceMockRecorder
	isgomock struct{}
}

// MockServiceInterfaceMockRecorder is the mock recorder for MockServiceInterface.
type MockServiceInterfaceMockRecorder struct {
	mock *MockServiceInterface
}

// NewMockServiceInterface creates a new mock instance.
func NewMockServiceInterface(ctrl *gomock.Controller) *MockServiceInterface {
	mock := &MockServiceInterface{ctrl: ctrl}
	mock.recorder = &MockServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockServiceInterface) EXPECT() *MockServiceInterfaceMockRecorder {
	return m.recorder
}

// CreateSignificantNote mocks base method.
func (m *MockServiceInterface) CreateSignificantNote(ctx context.Context, iirID string, noteReq SignificantNoteDTO) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSignificantNote", ctx, iirID, noteReq)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateSignificantNote indicates an expected call of CreateSignificantNote.
func (mr *MockServiceInterfaceMockRecorder) CreateSignificantNote(ctx, iirID, noteReq any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSignificantNote", reflect.TypeOf((*MockServiceInterface)(nil).CreateSignificantNote), ctx, iirID, noteReq)
}

// GetStudentSignificantNotes mocks base method.
func (m *MockServiceInterface) GetStudentSignificantNotes(ctx context.Context, iirID string) ([]SignificantNoteDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStudentSignificantNotes", ctx, iirID)
	ret0, _ := ret[0].([]SignificantNoteDTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStudentSignificantNotes indicates an expected call of GetStudentSignificantNotes.
func (mr *MockServiceInterfaceMockRecorder) GetStudentSignificantNotes(ctx, iirID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStudentSignificantNotes", reflect.TypeOf((*MockServiceInterface)(nil).GetStudentSignificantNotes), ctx, iirID)
}

// HasNoteForAppointment mocks base method.
func (m *MockServiceInterface) HasNoteForAppointment(ctx context.Context, appointmentID string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasNoteForAppointment", ctx, appointmentID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HasNoteForAppointment indicates an expected call of HasNoteForAppointment.
func (mr *MockServiceInterfaceMockRecorder) HasNoteForAppointment(ctx, appointmentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasNoteForAppointment", reflect.TypeOf((*MockServiceInterface)(nil).HasNoteForAppointment), ctx, appointmentID)
}

// WithTransaction mocks base method.
func (m *MockServiceInterface) WithTransaction(ctx context.Context, fn func(datastore.DB) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithTransaction", ctx, fn)
	ret0, _ := ret[0].(error)
	return ret0
}

// WithTransaction indicates an expected call of WithTransaction.
func (mr *MockServiceInterfaceMockRecorder) WithTransaction(ctx, fn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithTransaction", reflect.TypeOf((*MockServiceInterface)(nil).WithTransaction), ctx, fn)
}

// MockRepositoryInterface is a mock of RepositoryInterface interface.
type MockRepositoryInterface struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryInterfaceMockRecorder
	isgomock struct{}
}

// MockRepositoryInterfaceMockRecorder is the mock recorder for MockRepositoryInterface.
type MockRepositoryInterfaceMockRecorder struct {
	mock *MockRepositoryInterface
}

// NewMockRepositoryInterface creates a new mock instance.
func NewMockRepositoryInterface(ctrl *gomock.Controller) *MockRepositoryInterface {
	mock := &MockRepositoryInterface{ctrl: ctrl}
	mock.recorder = &MockRepositoryInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepositoryInterface) EXPECT() *MockRepositoryInterfaceMockRecorder {
	return m.recorder
}

// CreateSignificantNote mocks base method.
func (m *MockRepositoryInterface) CreateSignificantNote(ctx context.Context, sn *SignificantNote) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSignificantNote", ctx, sn)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSignificantNote indicates an expected call of CreateSignificantNote.
func (mr *MockRepositoryInterfaceMockRecorder) CreateSignificantNote(ctx, sn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSignificantNote", reflect.TypeOf((*MockRepositoryInterface)(nil).CreateSignificantNote), ctx, sn)
}

// GetStudentSignificantNotes mocks base method.
func (m *MockRepositoryInterface) GetStudentSignificantNotes(ctx context.Context, iirID string) ([]SignificantNote, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStudentSignificantNotes", ctx, iirID)
	ret0, _ := ret[0].([]SignificantNote)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStudentSignificantNotes indicates an expected call of GetStudentSignificantNotes.
func (mr *MockRepositoryInterfaceMockRecorder) GetStudentSignificantNotes(ctx, iirID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStudentSignificantNotes", reflect.TypeOf((*MockRepositoryInterface)(nil).GetStudentSignificantNotes), ctx, iirID)
}

// HasNoteForAppointment mocks base method.
func (m *MockRepositoryInterface) HasNoteForAppointment(ctx context.Context, appointmentID string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasNoteForAppointment", ctx, appointmentID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HasNoteForAppointment indicates an expected call of HasNoteForAppointment.
func (mr *MockRepositoryInterfaceMockRecorder) HasNoteForAppointment(ctx, appointmentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasNoteForAppointment", reflect.TypeOf((*MockRepositoryInterface)(nil).HasNoteForAppointment), ctx, appointmentID)
}

// WithTransaction mocks base method.
func (m *MockRepositoryInterface) WithTransaction(ctx context.Context, fn func(datastore.DB) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithTransaction", ctx, fn)
	ret0, _ := ret[0].(error)
	return ret0
}

// WithTransaction indicates an expected call of WithTransaction.
func (mr *MockRepositoryInterfaceMockRecorder) WithTransaction(ctx, fn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithTransaction", reflect.TypeOf((*MockRepositoryInterface)(nil).WithTransaction), ctx, fn)
}
