// Code generated by MockGen. DO NOT EDIT.
// Source: internal\infrastructure\identity\idp\interface.go
//
// Generated by this command:
//
//	mockgen -source=internal\infrastructure\identity\idp\interface.go -package=idp -destination=internal\infrastructure\identity\idp\mock_idp.go
//

// Package idp is a generated GoMock package.
package idp

import (
	context "context"
	reflect "reflect"

	config "github.com/olazo-johnalbert/duckload-api/internal/core/config"
	gomock "go.uber.org/mock/gomock"
)

// MockIDPClientInterface is a mock of IDPClientInterface interface.
type MockIDPClientInterface struct {
	ctrl     *gomock.Controller
	recorder *MockIDPClientInterfaceMockRecorder
	isgomock struct{}
}

// MockIDPClientInterfaceMockRecorder is the mock recorder for MockIDPClientInterface.
type MockIDPClientInterfaceMockRecorder struct {
	mock *MockIDPClientInterface
}

// NewMockIDPClientInterface creates a new mock instance.
func NewMockIDPClientInterface(ctrl *gomock.Controller) *MockIDPClientInterface {
	mock := &MockIDPClientInterface{ctrl: ctrl}
	mock.recorder = &MockIDPClientInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIDPClientInterface) EXPECT() *MockIDPClientInterfaceMockRecorder {
	return m.recorder
}

// ExchangeCodeForToken mocks base method.
func (m *MockIDPClientInterface) ExchangeCodeForToken(ctx context.Context, code string, cfg *config.Config) (*IDPTokenResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExchangeCodeForToken", ctx, code, cfg)
	ret0, _ := ret[0].(*IDPTokenResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExchangeCodeForToken indicates an expected call of ExchangeCodeForToken.
func (mr *MockIDPClientInterfaceMockRecorder) ExchangeCodeForToken(ctx, code, cfg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExchangeCodeForToken", reflect.TypeOf((*MockIDPClientInterface)(nil).ExchangeCodeForToken), ctx, code, cfg)
}

// GetLogoutURL mocks base method.
func (m *MockIDPClientInterface) GetLogoutURL(cfg *config.Config, idpUserID string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLogoutURL", cfg, idpUserID)
	ret0, _ := ret[0].(string)
	return ret0
}

// GetLogoutURL indicates an expected call of GetLogoutURL.
func (mr *MockIDPClientInterfaceMockRecorder) GetLogoutURL(cfg, idpUserID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLogoutURL", reflect.TypeOf((*MockIDPClientInterface)(nil).GetLogoutURL), cfg, idpUserID)
}

// GetUserInfo mocks base method.
func (m *MockIDPClientInterface) GetUserInfo(ctx context.Context, accessToken string, cfg *config.Config) (*IDPUserInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserInfo", ctx, accessToken, cfg)
	ret0, _ := ret[0].(*IDPUserInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserInfo indicates an expected call of GetUserInfo.
func (mr *MockIDPClientInterfaceMockRecorder) GetUserInfo(ctx, accessToken, cfg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserInfo", reflect.TypeOf((*MockIDPClientInterface)(nil).GetUserInfo), ctx, accessToken, cfg)
}

// RefreshToken mocks base method.
func (m *MockIDPClientInterface) RefreshToken(ctx context.Context, refreshToken string, cfg *config.Config) (*IDPTokenResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RefreshToken", ctx, refreshToken, cfg)
	ret0, _ := ret[0].(*IDPTokenResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RefreshToken indicates an expected call of RefreshToken.
func (mr *MockIDPClientInterfaceMockRecorder) RefreshToken(ctx, refreshToken, cfg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RefreshToken", reflect.TypeOf((*MockIDPClientInterface)(nil).RefreshToken), ctx, refreshToken, cfg)
}

// ValidateSession mocks base method.
func (m *MockIDPClientInterface) ValidateSession(ctx context.Context, sessionID string, cfg *config.Config) (*IDPSessionResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateSession", ctx, sessionID, cfg)
	ret0, _ := ret[0].(*IDPSessionResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ValidateSession indicates an expected call of ValidateSession.
func (mr *MockIDPClientInterfaceMockRecorder) ValidateSession(ctx, sessionID, cfg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateSession", reflect.TypeOf((*MockIDPClientInterface)(nil).ValidateSession), ctx, sessionID, cfg)
}
