// Code generated by MockGen. DO NOT EDIT.
// Source: c:\Users\JA\school_programming\capstone\DuckLoadLogic-Capstone\ogos-gin-api\internal\features\auth\interface.go
//
// Generated by this command:
//
//	mockgen -source=c:\Users\JA\school_programming\capstone\DuckLoadLogic-Capstone\ogos-gin-api\internal\features\auth\interface.go -package=auth -destination=c:\Users\JA\school_programming\capstone\DuckLoadLogic-Capstone\ogos-gin-api\internal\features\auth\mock_interfaces.go
//

// Package auth is a generated GoMock package.
package auth

import (
	context "context"
	reflect "reflect"

	config "github.com/olazo-johnalbert/duckload-api/internal/core/config"
	sessions "github.com/olazo-johnalbert/duckload-api/internal/core/sessions"
	users "github.com/olazo-johnalbert/duckload-api/internal/features/users"
	datastore "github.com/olazo-johnalbert/duckload-api/internal/infrastructure/datastore"
	idp "github.com/olazo-johnalbert/duckload-api/internal/infrastructure/identity/idp"
	gomock "go.uber.org/mock/gomock"
)

// MockServiceInterface is a mock of ServiceInterface interface.
type MockServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockServiceInterfaceMockRecorder
	isgomock struct{}
}

// MockServiceInterfaceMockRecorder is the mock recorder for MockServiceInterface.
type MockServiceInterfaceMockRecorder struct {
	mock *MockServiceInterface
}

// NewMockServiceInterface creates a new mock instance.
func NewMockServiceInterface(ctrl *gomock.Controller) *MockServiceInterface {
	mock := &MockServiceInterface{ctrl: ctrl}
	mock.recorder = &MockServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockServiceInterface) EXPECT() *MockServiceInterfaceMockRecorder {
	return m.recorder
}

// AuthenticateUser mocks base method.
func (m *MockServiceInterface) AuthenticateUser(ctx context.Context, email, password, ipAddress, userAgent string) (string, string, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AuthenticateUser", ctx, email, password, ipAddress, userAgent)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(string)
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// AuthenticateUser indicates an expected call of AuthenticateUser.
func (mr *MockServiceInterfaceMockRecorder) AuthenticateUser(ctx, email, password, ipAddress, userAgent any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AuthenticateUser", reflect.TypeOf((*MockServiceInterface)(nil).AuthenticateUser), ctx, email, password, ipAddress, userAgent)
}

// BlockUser mocks base method.
func (m *MockServiceInterface) BlockUser(ctx context.Context, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BlockUser", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// BlockUser indicates an expected call of BlockUser.
func (mr *MockServiceInterfaceMockRecorder) BlockUser(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BlockUser", reflect.TypeOf((*MockServiceInterface)(nil).BlockUser), ctx, userID)
}

// GetAuthorizeURL mocks base method.
func (m *MockServiceInterface) GetAuthorizeURL(cfg *config.Config) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAuthorizeURL", cfg)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAuthorizeURL indicates an expected call of GetAuthorizeURL.
func (mr *MockServiceInterfaceMockRecorder) GetAuthorizeURL(cfg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAuthorizeURL", reflect.TypeOf((*MockServiceInterface)(nil).GetAuthorizeURL), cfg)
}

// GetIDPUserInfo mocks base method.
func (m *MockServiceInterface) GetIDPUserInfo(ctx context.Context, accessToken string, cfg *config.Config) (*idp.IDPUserInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIDPUserInfo", ctx, accessToken, cfg)
	ret0, _ := ret[0].(*idp.IDPUserInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetIDPUserInfo indicates an expected call of GetIDPUserInfo.
func (mr *MockServiceInterfaceMockRecorder) GetIDPUserInfo(ctx, accessToken, cfg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIDPUserInfo", reflect.TypeOf((*MockServiceInterface)(nil).GetIDPUserInfo), ctx, accessToken, cfg)
}

// GetMe mocks base method.
func (m *MockServiceInterface) GetMe(ctx context.Context, userID, tokenType string) (*MeResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMe", ctx, userID, tokenType)
	ret0, _ := ret[0].(*MeResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMe indicates an expected call of GetMe.
func (mr *MockServiceInterfaceMockRecorder) GetMe(ctx, userID, tokenType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMe", reflect.TypeOf((*MockServiceInterface)(nil).GetMe), ctx, userID, tokenType)
}

// Logout mocks base method.
func (m *MockServiceInterface) Logout(ctx context.Context, token, tokenType string, cfg *config.Config) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Logout", ctx, token, tokenType, cfg)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Logout indicates an expected call of Logout.
func (mr *MockServiceInterfaceMockRecorder) Logout(ctx, token, tokenType, cfg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Logout", reflect.TypeOf((*MockServiceInterface)(nil).Logout), ctx, token, tokenType, cfg)
}

// PostIDPTokenExchange mocks base method.
func (m *MockServiceInterface) PostIDPTokenExchange(ctx context.Context, code string, cfg *config.Config, ipAddress, userAgent string) (string, string, string, string, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PostIDPTokenExchange", ctx, code, cfg, ipAddress, userAgent)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(string)
	ret3, _ := ret[3].(string)
	ret4, _ := ret[4].(string)
	ret5, _ := ret[5].(error)
	return ret0, ret1, ret2, ret3, ret4, ret5
}

// PostIDPTokenExchange indicates an expected call of PostIDPTokenExchange.
func (mr *MockServiceInterfaceMockRecorder) PostIDPTokenExchange(ctx, code, cfg, ipAddress, userAgent any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PostIDPTokenExchange", reflect.TypeOf((*MockServiceInterface)(nil).PostIDPTokenExchange), ctx, code, cfg, ipAddress, userAgent)
}

// RefreshIDPToken mocks base method.
func (m *MockServiceInterface) RefreshIDPToken(ctx context.Context, refreshToken string, cfg *config.Config) (string, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RefreshIDPToken", ctx, refreshToken, cfg)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// RefreshIDPToken indicates an expected call of RefreshIDPToken.
func (mr *MockServiceInterfaceMockRecorder) RefreshIDPToken(ctx, refreshToken, cfg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RefreshIDPToken", reflect.TypeOf((*MockServiceInterface)(nil).RefreshIDPToken), ctx, refreshToken, cfg)
}

// RefreshToken mocks base method.
func (m *MockServiceInterface) RefreshToken(ctx context.Context, accessTokenJTI sessions.JTIDTO, cfg *config.Config, ipAddress, userAgent string) (string, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RefreshToken", ctx, accessTokenJTI, cfg, ipAddress, userAgent)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// RefreshToken indicates an expected call of RefreshToken.
func (mr *MockServiceInterfaceMockRecorder) RefreshToken(ctx, accessTokenJTI, cfg, ipAddress, userAgent any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RefreshToken", reflect.TypeOf((*MockServiceInterface)(nil).RefreshToken), ctx, accessTokenJTI, cfg, ipAddress, userAgent)
}

// RegisterUser mocks base method.
func (m *MockServiceInterface) RegisterUser(ctx context.Context, req RegisterDTO) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RegisterUser", ctx, req)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RegisterUser indicates an expected call of RegisterUser.
func (mr *MockServiceInterfaceMockRecorder) RegisterUser(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterUser", reflect.TypeOf((*MockServiceInterface)(nil).RegisterUser), ctx, req)
}

// ResendVerification mocks base method.
func (m *MockServiceInterface) ResendVerification(ctx context.Context, registrationID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResendVerification", ctx, registrationID)
	ret0, _ := ret[0].(error)
	return ret0
}

// ResendVerification indicates an expected call of ResendVerification.
func (mr *MockServiceInterfaceMockRecorder) ResendVerification(ctx, registrationID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResendVerification", reflect.TypeOf((*MockServiceInterface)(nil).ResendVerification), ctx, registrationID)
}

// UnblockUser mocks base method.
func (m *MockServiceInterface) UnblockUser(ctx context.Context, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnblockUser", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// UnblockUser indicates an expected call of UnblockUser.
func (mr *MockServiceInterfaceMockRecorder) UnblockUser(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnblockUser", reflect.TypeOf((*MockServiceInterface)(nil).UnblockUser), ctx, userID)
}

// VerifyUser mocks base method.
func (m *MockServiceInterface) VerifyUser(ctx context.Context, registrationID, verificationOTP string) (string, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyUser", ctx, registrationID, verificationOTP)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// VerifyUser indicates an expected call of VerifyUser.
func (mr *MockServiceInterfaceMockRecorder) VerifyUser(ctx, registrationID, verificationOTP any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyUser", reflect.TypeOf((*MockServiceInterface)(nil).VerifyUser), ctx, registrationID, verificationOTP)
}

// MockRepositoryInterface is a mock of RepositoryInterface interface.
type MockRepositoryInterface struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryInterfaceMockRecorder
	isgomock struct{}
}

// MockRepositoryInterfaceMockRecorder is the mock recorder for MockRepositoryInterface.
type MockRepositoryInterfaceMockRecorder struct {
	mock *MockRepositoryInterface
}

// NewMockRepositoryInterface creates a new mock instance.
func NewMockRepositoryInterface(ctrl *gomock.Controller) *MockRepositoryInterface {
	mock := &MockRepositoryInterface{ctrl: ctrl}
	mock.recorder = &MockRepositoryInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepositoryInterface) EXPECT() *MockRepositoryInterfaceMockRecorder {
	return m.recorder
}

// AssignRole mocks base method.
func (m *MockRepositoryInterface) AssignRole(ctx context.Context, tx datastore.DB, assignment users.RoleAssignment) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AssignRole", ctx, tx, assignment)
	ret0, _ := ret[0].(error)
	return ret0
}

// AssignRole indicates an expected call of AssignRole.
func (mr *MockRepositoryInterfaceMockRecorder) AssignRole(ctx, tx, assignment any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AssignRole", reflect.TypeOf((*MockRepositoryInterface)(nil).AssignRole), ctx, tx, assignment)
}

// BlockUser mocks base method.
func (m *MockRepositoryInterface) BlockUser(ctx context.Context, tx datastore.DB, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BlockUser", ctx, tx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// BlockUser indicates an expected call of BlockUser.
func (mr *MockRepositoryInterfaceMockRecorder) BlockUser(ctx, tx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BlockUser", reflect.TypeOf((*MockRepositoryInterface)(nil).BlockUser), ctx, tx, userID)
}

// CheckUserWhitelist mocks base method.
func (m *MockRepositoryInterface) CheckUserWhitelist(ctx context.Context, email string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckUserWhitelist", ctx, email)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckUserWhitelist indicates an expected call of CheckUserWhitelist.
func (mr *MockRepositoryInterfaceMockRecorder) CheckUserWhitelist(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckUserWhitelist", reflect.TypeOf((*MockRepositoryInterface)(nil).CheckUserWhitelist), ctx, email)
}

// CreateUser mocks base method.
func (m *MockRepositoryInterface) CreateUser(ctx context.Context, tx datastore.DB, user users.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", ctx, tx, user)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockRepositoryInterfaceMockRecorder) CreateUser(ctx, tx, user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockRepositoryInterface)(nil).CreateUser), ctx, tx, user)
}

// GetRoleByID mocks base method.
func (m *MockRepositoryInterface) GetRoleByID(ctx context.Context, roleID int) (*users.Role, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRoleByID", ctx, roleID)
	ret0, _ := ret[0].(*users.Role)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRoleByID indicates an expected call of GetRoleByID.
func (mr *MockRepositoryInterfaceMockRecorder) GetRoleByID(ctx, roleID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRoleByID", reflect.TypeOf((*MockRepositoryInterface)(nil).GetRoleByID), ctx, roleID)
}

// GetRolesByUserID mocks base method.
func (m *MockRepositoryInterface) GetRolesByUserID(ctx context.Context, userID string) ([]users.Role, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRolesByUserID", ctx, userID)
	ret0, _ := ret[0].([]users.Role)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRolesByUserID indicates an expected call of GetRolesByUserID.
func (mr *MockRepositoryInterfaceMockRecorder) GetRolesByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRolesByUserID", reflect.TypeOf((*MockRepositoryInterface)(nil).GetRolesByUserID), ctx, userID)
}

// GetUserByEmail mocks base method.
func (m *MockRepositoryInterface) GetUserByEmail(ctx context.Context, email, authType string) (*users.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByEmail", ctx, email, authType)
	ret0, _ := ret[0].(*users.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByEmail indicates an expected call of GetUserByEmail.
func (mr *MockRepositoryInterfaceMockRecorder) GetUserByEmail(ctx, email, authType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByEmail", reflect.TypeOf((*MockRepositoryInterface)(nil).GetUserByEmail), ctx, email, authType)
}

// GetUserByID mocks base method.
func (m *MockRepositoryInterface) GetUserByID(ctx context.Context, userID string) (*users.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByID", ctx, userID)
	ret0, _ := ret[0].(*users.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByID indicates an expected call of GetUserByID.
func (mr *MockRepositoryInterfaceMockRecorder) GetUserByID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByID", reflect.TypeOf((*MockRepositoryInterface)(nil).GetUserByID), ctx, userID)
}

// RemoveRoles mocks base method.
func (m *MockRepositoryInterface) RemoveRoles(ctx context.Context, tx datastore.DB, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveRoles", ctx, tx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveRoles indicates an expected call of RemoveRoles.
func (mr *MockRepositoryInterfaceMockRecorder) RemoveRoles(ctx, tx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveRoles", reflect.TypeOf((*MockRepositoryInterface)(nil).RemoveRoles), ctx, tx, userID)
}

// UnblockUser mocks base method.
func (m *MockRepositoryInterface) UnblockUser(ctx context.Context, tx datastore.DB, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnblockUser", ctx, tx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// UnblockUser indicates an expected call of UnblockUser.
func (mr *MockRepositoryInterfaceMockRecorder) UnblockUser(ctx, tx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnblockUser", reflect.TypeOf((*MockRepositoryInterface)(nil).UnblockUser), ctx, tx, userID)
}

// WithTransaction mocks base method.
func (m *MockRepositoryInterface) WithTransaction(ctx context.Context, fn func(datastore.DB) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithTransaction", ctx, fn)
	ret0, _ := ret[0].(error)
	return ret0
}

// WithTransaction indicates an expected call of WithTransaction.
func (mr *MockRepositoryInterfaceMockRecorder) WithTransaction(ctx, fn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithTransaction", reflect.TypeOf((*MockRepositoryInterface)(nil).WithTransaction), ctx, fn)
}
