// Code generated by MockGen. DO NOT EDIT.
// Source: internal\features\locations\interface.go
//
// Generated by this command:
//
//	mockgen -source=internal\features\locations\interface.go -package=locations -destination=internal\features\locations\mock_interfaces.go
//

// Package locations is a generated GoMock package.
package locations

import (
	context "context"
	reflect "reflect"

	sqlx "github.com/jmoiron/sqlx"
	datastore "github.com/olazo-johnalbert/duckload-api/internal/infrastructure/datastore"
	gomock "go.uber.org/mock/gomock"
)

// MockServiceInterface is a mock of ServiceInterface interface.
type MockServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockServiceInterfaceMockRecorder
	isgomock struct{}
}

// MockServiceInterfaceMockRecorder is the mock recorder for MockServiceInterface.
type MockServiceInterfaceMockRecorder struct {
	mock *MockServiceInterface
}

// NewMockServiceInterface creates a new mock instance.
func NewMockServiceInterface(ctrl *gomock.Controller) *MockServiceInterface {
	mock := &MockServiceInterface{ctrl: ctrl}
	mock.recorder = &MockServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockServiceInterface) EXPECT() *MockServiceInterfaceMockRecorder {
	return m.recorder
}

// GetAddressByID mocks base method.
func (m *MockServiceInterface) GetAddressByID(ctx context.Context, addressID int) (AddressDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAddressByID", ctx, addressID)
	ret0, _ := ret[0].(AddressDTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAddressByID indicates an expected call of GetAddressByID.
func (mr *MockServiceInterfaceMockRecorder) GetAddressByID(ctx, addressID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAddressByID", reflect.TypeOf((*MockServiceInterface)(nil).GetAddressByID), ctx, addressID)
}

// GetBarangayByCode mocks base method.
func (m *MockServiceInterface) GetBarangayByCode(ctx context.Context, barangayCode string) (*Barangay, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBarangayByCode", ctx, barangayCode)
	ret0, _ := ret[0].(*Barangay)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBarangayByCode indicates an expected call of GetBarangayByCode.
func (mr *MockServiceInterfaceMockRecorder) GetBarangayByCode(ctx, barangayCode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBarangayByCode", reflect.TypeOf((*MockServiceInterface)(nil).GetBarangayByCode), ctx, barangayCode)
}

// GetBarangaysByCity mocks base method.
func (m *MockServiceInterface) GetBarangaysByCity(ctx context.Context, cityCode string) ([]Barangay, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBarangaysByCity", ctx, cityCode)
	ret0, _ := ret[0].([]Barangay)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBarangaysByCity indicates an expected call of GetBarangaysByCity.
func (mr *MockServiceInterfaceMockRecorder) GetBarangaysByCity(ctx, cityCode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBarangaysByCity", reflect.TypeOf((*MockServiceInterface)(nil).GetBarangaysByCity), ctx, cityCode)
}

// GetCitiesByProvince mocks base method.
func (m *MockServiceInterface) GetCitiesByProvince(ctx context.Context, provinceCode string) ([]City, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCitiesByProvince", ctx, provinceCode)
	ret0, _ := ret[0].([]City)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCitiesByProvince indicates an expected call of GetCitiesByProvince.
func (mr *MockServiceInterfaceMockRecorder) GetCitiesByProvince(ctx, provinceCode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCitiesByProvince", reflect.TypeOf((*MockServiceInterface)(nil).GetCitiesByProvince), ctx, provinceCode)
}

// GetCitiesByRegion mocks base method.
func (m *MockServiceInterface) GetCitiesByRegion(ctx context.Context, regionCode string) ([]City, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCitiesByRegion", ctx, regionCode)
	ret0, _ := ret[0].([]City)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCitiesByRegion indicates an expected call of GetCitiesByRegion.
func (mr *MockServiceInterfaceMockRecorder) GetCitiesByRegion(ctx, regionCode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCitiesByRegion", reflect.TypeOf((*MockServiceInterface)(nil).GetCitiesByRegion), ctx, regionCode)
}

// GetCityByCode mocks base method.
func (m *MockServiceInterface) GetCityByCode(ctx context.Context, cityCode string) (*City, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCityByCode", ctx, cityCode)
	ret0, _ := ret[0].(*City)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCityByCode indicates an expected call of GetCityByCode.
func (mr *MockServiceInterfaceMockRecorder) GetCityByCode(ctx, cityCode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCityByCode", reflect.TypeOf((*MockServiceInterface)(nil).GetCityByCode), ctx, cityCode)
}

// GetProvinceByCode mocks base method.
func (m *MockServiceInterface) GetProvinceByCode(ctx context.Context, provinceCode string) (*Province, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProvinceByCode", ctx, provinceCode)
	ret0, _ := ret[0].(*Province)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProvinceByCode indicates an expected call of GetProvinceByCode.
func (mr *MockServiceInterfaceMockRecorder) GetProvinceByCode(ctx, provinceCode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProvinceByCode", reflect.TypeOf((*MockServiceInterface)(nil).GetProvinceByCode), ctx, provinceCode)
}

// GetProvincesByRegion mocks base method.
func (m *MockServiceInterface) GetProvincesByRegion(ctx context.Context, regionCode string) ([]Province, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProvincesByRegion", ctx, regionCode)
	ret0, _ := ret[0].([]Province)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProvincesByRegion indicates an expected call of GetProvincesByRegion.
func (mr *MockServiceInterfaceMockRecorder) GetProvincesByRegion(ctx, regionCode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProvincesByRegion", reflect.TypeOf((*MockServiceInterface)(nil).GetProvincesByRegion), ctx, regionCode)
}

// GetRegionByCode mocks base method.
func (m *MockServiceInterface) GetRegionByCode(ctx context.Context, regionCode string) (*Region, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRegionByCode", ctx, regionCode)
	ret0, _ := ret[0].(*Region)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRegionByCode indicates an expected call of GetRegionByCode.
func (mr *MockServiceInterfaceMockRecorder) GetRegionByCode(ctx, regionCode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRegionByCode", reflect.TypeOf((*MockServiceInterface)(nil).GetRegionByCode), ctx, regionCode)
}

// GetRegions mocks base method.
func (m *MockServiceInterface) GetRegions(ctx context.Context) ([]Region, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRegions", ctx)
	ret0, _ := ret[0].([]Region)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRegions indicates an expected call of GetRegions.
func (mr *MockServiceInterfaceMockRecorder) GetRegions(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRegions", reflect.TypeOf((*MockServiceInterface)(nil).GetRegions), ctx)
}

// SaveAddress mocks base method.
func (m *MockServiceInterface) SaveAddress(ctx context.Context, tx datastore.DB, addr *Address) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveAddress", ctx, tx, addr)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SaveAddress indicates an expected call of SaveAddress.
func (mr *MockServiceInterfaceMockRecorder) SaveAddress(ctx, tx, addr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveAddress", reflect.TypeOf((*MockServiceInterface)(nil).SaveAddress), ctx, tx, addr)
}

// WithTransaction mocks base method.
func (m *MockServiceInterface) WithTransaction(ctx context.Context, fn func(datastore.DB) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithTransaction", ctx, fn)
	ret0, _ := ret[0].(error)
	return ret0
}

// WithTransaction indicates an expected call of WithTransaction.
func (mr *MockServiceInterfaceMockRecorder) WithTransaction(ctx, fn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithTransaction", reflect.TypeOf((*MockServiceInterface)(nil).WithTransaction), ctx, fn)
}

// MockRepositoryInterface is a mock of RepositoryInterface interface.
type MockRepositoryInterface struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryInterfaceMockRecorder
	isgomock struct{}
}

// MockRepositoryInterfaceMockRecorder is the mock recorder for MockRepositoryInterface.
type MockRepositoryInterfaceMockRecorder struct {
	mock *MockRepositoryInterface
}

// NewMockRepositoryInterface creates a new mock instance.
func NewMockRepositoryInterface(ctrl *gomock.Controller) *MockRepositoryInterface {
	mock := &MockRepositoryInterface{ctrl: ctrl}
	mock.recorder = &MockRepositoryInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepositoryInterface) EXPECT() *MockRepositoryInterfaceMockRecorder {
	return m.recorder
}

// GetAddressByID mocks base method.
func (m *MockRepositoryInterface) GetAddressByID(ctx context.Context, addressID int) (*Address, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAddressByID", ctx, addressID)
	ret0, _ := ret[0].(*Address)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAddressByID indicates an expected call of GetAddressByID.
func (mr *MockRepositoryInterfaceMockRecorder) GetAddressByID(ctx, addressID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAddressByID", reflect.TypeOf((*MockRepositoryInterface)(nil).GetAddressByID), ctx, addressID)
}

// GetBarangayByCode mocks base method.
func (m *MockRepositoryInterface) GetBarangayByCode(ctx context.Context, barangayCode string) (*Barangay, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBarangayByCode", ctx, barangayCode)
	ret0, _ := ret[0].(*Barangay)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBarangayByCode indicates an expected call of GetBarangayByCode.
func (mr *MockRepositoryInterfaceMockRecorder) GetBarangayByCode(ctx, barangayCode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBarangayByCode", reflect.TypeOf((*MockRepositoryInterface)(nil).GetBarangayByCode), ctx, barangayCode)
}

// GetBarangaysByCity mocks base method.
func (m *MockRepositoryInterface) GetBarangaysByCity(ctx context.Context, cityCode string) ([]Barangay, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBarangaysByCity", ctx, cityCode)
	ret0, _ := ret[0].([]Barangay)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBarangaysByCity indicates an expected call of GetBarangaysByCity.
func (mr *MockRepositoryInterfaceMockRecorder) GetBarangaysByCity(ctx, cityCode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBarangaysByCity", reflect.TypeOf((*MockRepositoryInterface)(nil).GetBarangaysByCity), ctx, cityCode)
}

// GetCitiesByProvince mocks base method.
func (m *MockRepositoryInterface) GetCitiesByProvince(ctx context.Context, provinceCode string) ([]City, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCitiesByProvince", ctx, provinceCode)
	ret0, _ := ret[0].([]City)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCitiesByProvince indicates an expected call of GetCitiesByProvince.
func (mr *MockRepositoryInterfaceMockRecorder) GetCitiesByProvince(ctx, provinceCode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCitiesByProvince", reflect.TypeOf((*MockRepositoryInterface)(nil).GetCitiesByProvince), ctx, provinceCode)
}

// GetCitiesByRegion mocks base method.
func (m *MockRepositoryInterface) GetCitiesByRegion(ctx context.Context, regionCode string) ([]City, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCitiesByRegion", ctx, regionCode)
	ret0, _ := ret[0].([]City)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCitiesByRegion indicates an expected call of GetCitiesByRegion.
func (mr *MockRepositoryInterfaceMockRecorder) GetCitiesByRegion(ctx, regionCode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCitiesByRegion", reflect.TypeOf((*MockRepositoryInterface)(nil).GetCitiesByRegion), ctx, regionCode)
}

// GetCityByCode mocks base method.
func (m *MockRepositoryInterface) GetCityByCode(ctx context.Context, cityCode string) (*City, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCityByCode", ctx, cityCode)
	ret0, _ := ret[0].(*City)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCityByCode indicates an expected call of GetCityByCode.
func (mr *MockRepositoryInterfaceMockRecorder) GetCityByCode(ctx, cityCode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCityByCode", reflect.TypeOf((*MockRepositoryInterface)(nil).GetCityByCode), ctx, cityCode)
}

// GetDB mocks base method.
func (m *MockRepositoryInterface) GetDB() *sqlx.DB {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDB")
	ret0, _ := ret[0].(*sqlx.DB)
	return ret0
}

// GetDB indicates an expected call of GetDB.
func (mr *MockRepositoryInterfaceMockRecorder) GetDB() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDB", reflect.TypeOf((*MockRepositoryInterface)(nil).GetDB))
}

// GetProvinceByCode mocks base method.
func (m *MockRepositoryInterface) GetProvinceByCode(ctx context.Context, provinceCode string) (*Province, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProvinceByCode", ctx, provinceCode)
	ret0, _ := ret[0].(*Province)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProvinceByCode indicates an expected call of GetProvinceByCode.
func (mr *MockRepositoryInterfaceMockRecorder) GetProvinceByCode(ctx, provinceCode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProvinceByCode", reflect.TypeOf((*MockRepositoryInterface)(nil).GetProvinceByCode), ctx, provinceCode)
}

// GetProvincesByRegion mocks base method.
func (m *MockRepositoryInterface) GetProvincesByRegion(ctx context.Context, regionCode string) ([]Province, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProvincesByRegion", ctx, regionCode)
	ret0, _ := ret[0].([]Province)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProvincesByRegion indicates an expected call of GetProvincesByRegion.
func (mr *MockRepositoryInterfaceMockRecorder) GetProvincesByRegion(ctx, regionCode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProvincesByRegion", reflect.TypeOf((*MockRepositoryInterface)(nil).GetProvincesByRegion), ctx, regionCode)
}

// GetRegionByCode mocks base method.
func (m *MockRepositoryInterface) GetRegionByCode(ctx context.Context, regionCode string) (*Region, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRegionByCode", ctx, regionCode)
	ret0, _ := ret[0].(*Region)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRegionByCode indicates an expected call of GetRegionByCode.
func (mr *MockRepositoryInterfaceMockRecorder) GetRegionByCode(ctx, regionCode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRegionByCode", reflect.TypeOf((*MockRepositoryInterface)(nil).GetRegionByCode), ctx, regionCode)
}

// GetRegions mocks base method.
func (m *MockRepositoryInterface) GetRegions(ctx context.Context) ([]Region, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRegions", ctx)
	ret0, _ := ret[0].([]Region)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRegions indicates an expected call of GetRegions.
func (mr *MockRepositoryInterfaceMockRecorder) GetRegions(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRegions", reflect.TypeOf((*MockRepositoryInterface)(nil).GetRegions), ctx)
}

// UpsertAddress mocks base method.
func (m *MockRepositoryInterface) UpsertAddress(ctx context.Context, tx datastore.DB, addr *Address) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertAddress", ctx, tx, addr)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpsertAddress indicates an expected call of UpsertAddress.
func (mr *MockRepositoryInterfaceMockRecorder) UpsertAddress(ctx, tx, addr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertAddress", reflect.TypeOf((*MockRepositoryInterface)(nil).UpsertAddress), ctx, tx, addr)
}

// WithTransaction mocks base method.
func (m *MockRepositoryInterface) WithTransaction(ctx context.Context, fn func(datastore.DB) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithTransaction", ctx, fn)
	ret0, _ := ret[0].(error)
	return ret0
}

// WithTransaction indicates an expected call of WithTransaction.
func (mr *MockRepositoryInterfaceMockRecorder) WithTransaction(ctx, fn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithTransaction", reflect.TypeOf((*MockRepositoryInterface)(nil).WithTransaction), ctx, fn)
}
