// Code generated by MockGen. DO NOT EDIT.
// Source: internal\features\slips\interface.go
//
// Generated by this command:
//
//	mockgen -source=internal\features\slips\interface.go -package=slips -destination=internal\features\slips\mock_interfaces.go
//

// Package slips is a generated GoMock package.
package slips

import (
	context "context"
	io "io"
	multipart "mime/multipart"
	reflect "reflect"

	sqlx "github.com/jmoiron/sqlx"
	datastore "github.com/olazo-johnalbert/duckload-api/internal/infrastructure/datastore"
	gomock "go.uber.org/mock/gomock"
)

// MockServiceInterface is a mock of ServiceInterface interface.
type MockServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockServiceInterfaceMockRecorder
	isgomock struct{}
}

// MockServiceInterfaceMockRecorder is the mock recorder for MockServiceInterface.
type MockServiceInterfaceMockRecorder struct {
	mock *MockServiceInterface
}

// NewMockServiceInterface creates a new mock instance.
func NewMockServiceInterface(ctrl *gomock.Controller) *MockServiceInterface {
	mock := &MockServiceInterface{ctrl: ctrl}
	mock.recorder = &MockServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockServiceInterface) EXPECT() *MockServiceInterfaceMockRecorder {
	return m.recorder
}

// DownloadAttachment mocks base method.
func (m *MockServiceInterface) DownloadAttachment(ctx context.Context, attachmentID string, writer io.Writer) (*SlipAttachment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DownloadAttachment", ctx, attachmentID, writer)
	ret0, _ := ret[0].(*SlipAttachment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DownloadAttachment indicates an expected call of DownloadAttachment.
func (mr *MockServiceInterfaceMockRecorder) DownloadAttachment(ctx, attachmentID, writer any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DownloadAttachment", reflect.TypeOf((*MockServiceInterface)(nil).DownloadAttachment), ctx, attachmentID, writer)
}

// GetAllExcuseSlips mocks base method.
func (m *MockServiceInterface) GetAllExcuseSlips(ctx context.Context, req ListSlipRequest) (*ListSlipsDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllExcuseSlips", ctx, req)
	ret0, _ := ret[0].(*ListSlipsDTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllExcuseSlips indicates an expected call of GetAllExcuseSlips.
func (mr *MockServiceInterfaceMockRecorder) GetAllExcuseSlips(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllExcuseSlips", reflect.TypeOf((*MockServiceInterface)(nil).GetAllExcuseSlips), ctx, req)
}

// GetAttachmentFile mocks base method.
func (m *MockServiceInterface) GetAttachmentFile(ctx context.Context, attachmentID string) (*SlipAttachment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAttachmentFile", ctx, attachmentID)
	ret0, _ := ret[0].(*SlipAttachment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAttachmentFile indicates an expected call of GetAttachmentFile.
func (mr *MockServiceInterfaceMockRecorder) GetAttachmentFile(ctx, attachmentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAttachmentFile", reflect.TypeOf((*MockServiceInterface)(nil).GetAttachmentFile), ctx, attachmentID)
}

// GetExcuseSlipsByIIRID mocks base method.
func (m *MockServiceInterface) GetExcuseSlipsByIIRID(ctx context.Context, iirID string, req ListSlipRequest) (*ListSlipsDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetExcuseSlipsByIIRID", ctx, iirID, req)
	ret0, _ := ret[0].(*ListSlipsDTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetExcuseSlipsByIIRID indicates an expected call of GetExcuseSlipsByIIRID.
func (mr *MockServiceInterfaceMockRecorder) GetExcuseSlipsByIIRID(ctx, iirID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetExcuseSlipsByIIRID", reflect.TypeOf((*MockServiceInterface)(nil).GetExcuseSlipsByIIRID), ctx, iirID, req)
}

// GetSlipAttachments mocks base method.
func (m *MockServiceInterface) GetSlipAttachments(ctx context.Context, slipID string) ([]AttachmentDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSlipAttachments", ctx, slipID)
	ret0, _ := ret[0].([]AttachmentDTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSlipAttachments indicates an expected call of GetSlipAttachments.
func (mr *MockServiceInterfaceMockRecorder) GetSlipAttachments(ctx, slipID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSlipAttachments", reflect.TypeOf((*MockServiceInterface)(nil).GetSlipAttachments), ctx, slipID)
}

// GetSlipByID mocks base method.
func (m *MockServiceInterface) GetSlipByID(ctx context.Context, id string) (*SlipDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSlipByID", ctx, id)
	ret0, _ := ret[0].(*SlipDTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSlipByID indicates an expected call of GetSlipByID.
func (mr *MockServiceInterfaceMockRecorder) GetSlipByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSlipByID", reflect.TypeOf((*MockServiceInterface)(nil).GetSlipByID), ctx, id)
}

// GetSlipCategories mocks base method.
func (m *MockServiceInterface) GetSlipCategories(ctx context.Context) ([]SlipCategory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSlipCategories", ctx)
	ret0, _ := ret[0].([]SlipCategory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSlipCategories indicates an expected call of GetSlipCategories.
func (mr *MockServiceInterfaceMockRecorder) GetSlipCategories(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSlipCategories", reflect.TypeOf((*MockServiceInterface)(nil).GetSlipCategories), ctx)
}

// GetSlipStats mocks base method.
func (m *MockServiceInterface) GetSlipStats(ctx context.Context, iirID *string, req *ListSlipRequest) ([]SlipStatusCount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSlipStats", ctx, iirID, req)
	ret0, _ := ret[0].([]SlipStatusCount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSlipStats indicates an expected call of GetSlipStats.
func (mr *MockServiceInterfaceMockRecorder) GetSlipStats(ctx, iirID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSlipStats", reflect.TypeOf((*MockServiceInterface)(nil).GetSlipStats), ctx, iirID, req)
}

// GetSlipStatuses mocks base method.
func (m *MockServiceInterface) GetSlipStatuses(ctx context.Context) ([]SlipStatus, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSlipStatuses", ctx)
	ret0, _ := ret[0].([]SlipStatus)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSlipStatuses indicates an expected call of GetSlipStatuses.
func (mr *MockServiceInterfaceMockRecorder) GetSlipStatuses(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSlipStatuses", reflect.TypeOf((*MockServiceInterface)(nil).GetSlipStatuses), ctx)
}

// GetUrgentSlips mocks base method.
func (m *MockServiceInterface) GetUrgentSlips(ctx context.Context, req *ListSlipRequest) (*ListSlipsDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUrgentSlips", ctx, req)
	ret0, _ := ret[0].(*ListSlipsDTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUrgentSlips indicates an expected call of GetUrgentSlips.
func (mr *MockServiceInterfaceMockRecorder) GetUrgentSlips(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUrgentSlips", reflect.TypeOf((*MockServiceInterface)(nil).GetUrgentSlips), ctx, req)
}

// SubmitExcuseSlip mocks base method.
func (m *MockServiceInterface) SubmitExcuseSlip(ctx context.Context, iirID string, req CreateSlipRequest, files []*multipart.FileHeader) (*Slip, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SubmitExcuseSlip", ctx, iirID, req, files)
	ret0, _ := ret[0].(*Slip)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SubmitExcuseSlip indicates an expected call of SubmitExcuseSlip.
func (mr *MockServiceInterfaceMockRecorder) SubmitExcuseSlip(ctx, iirID, req, files any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubmitExcuseSlip", reflect.TypeOf((*MockServiceInterface)(nil).SubmitExcuseSlip), ctx, iirID, req, files)
}

// UpdateExcuseSlip mocks base method.
func (m *MockServiceInterface) UpdateExcuseSlip(ctx context.Context, iirID, slipID string, req CreateSlipRequest, files []*multipart.FileHeader) (*Slip, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateExcuseSlip", ctx, iirID, slipID, req, files)
	ret0, _ := ret[0].(*Slip)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateExcuseSlip indicates an expected call of UpdateExcuseSlip.
func (mr *MockServiceInterfaceMockRecorder) UpdateExcuseSlip(ctx, iirID, slipID, req, files any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateExcuseSlip", reflect.TypeOf((*MockServiceInterface)(nil).UpdateExcuseSlip), ctx, iirID, slipID, req, files)
}

// UpdateExcuseSlipStatus mocks base method.
func (m *MockServiceInterface) UpdateExcuseSlipStatus(ctx context.Context, id, newStatus, adminNotes string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateExcuseSlipStatus", ctx, id, newStatus, adminNotes)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateExcuseSlipStatus indicates an expected call of UpdateExcuseSlipStatus.
func (mr *MockServiceInterfaceMockRecorder) UpdateExcuseSlipStatus(ctx, id, newStatus, adminNotes any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateExcuseSlipStatus", reflect.TypeOf((*MockServiceInterface)(nil).UpdateExcuseSlipStatus), ctx, id, newStatus, adminNotes)
}

// WithTransaction mocks base method.
func (m *MockServiceInterface) WithTransaction(ctx context.Context, fn func(datastore.DB) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithTransaction", ctx, fn)
	ret0, _ := ret[0].(error)
	return ret0
}

// WithTransaction indicates an expected call of WithTransaction.
func (mr *MockServiceInterfaceMockRecorder) WithTransaction(ctx, fn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithTransaction", reflect.TypeOf((*MockServiceInterface)(nil).WithTransaction), ctx, fn)
}

// MockRepositoryInterface is a mock of RepositoryInterface interface.
type MockRepositoryInterface struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryInterfaceMockRecorder
	isgomock struct{}
}

// MockRepositoryInterfaceMockRecorder is the mock recorder for MockRepositoryInterface.
type MockRepositoryInterfaceMockRecorder struct {
	mock *MockRepositoryInterface
}

// NewMockRepositoryInterface creates a new mock instance.
func NewMockRepositoryInterface(ctrl *gomock.Controller) *MockRepositoryInterface {
	mock := &MockRepositoryInterface{ctrl: ctrl}
	mock.recorder = &MockRepositoryInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepositoryInterface) EXPECT() *MockRepositoryInterfaceMockRecorder {
	return m.recorder
}

// BeginTx mocks base method.
func (m *MockRepositoryInterface) BeginTx(ctx context.Context) (datastore.DB, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BeginTx", ctx)
	ret0, _ := ret[0].(datastore.DB)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BeginTx indicates an expected call of BeginTx.
func (mr *MockRepositoryInterfaceMockRecorder) BeginTx(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BeginTx", reflect.TypeOf((*MockRepositoryInterface)(nil).BeginTx), ctx)
}

// CheckStudentExistence mocks base method.
func (m *MockRepositoryInterface) CheckStudentExistence(ctx context.Context, studentID int) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckStudentExistence", ctx, studentID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckStudentExistence indicates an expected call of CheckStudentExistence.
func (mr *MockRepositoryInterfaceMockRecorder) CheckStudentExistence(ctx, studentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckStudentExistence", reflect.TypeOf((*MockRepositoryInterface)(nil).CheckStudentExistence), ctx, studentID)
}

// CreateSlip mocks base method.
func (m *MockRepositoryInterface) CreateSlip(ctx context.Context, tx datastore.DB, slip *Slip) (*string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSlip", ctx, tx, slip)
	ret0, _ := ret[0].(*string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSlip indicates an expected call of CreateSlip.
func (mr *MockRepositoryInterfaceMockRecorder) CreateSlip(ctx, tx, slip any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSlip", reflect.TypeOf((*MockRepositoryInterface)(nil).CreateSlip), ctx, tx, slip)
}

// Delete mocks base method.
func (m *MockRepositoryInterface) Delete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockRepositoryInterfaceMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockRepositoryInterface)(nil).Delete), ctx, id)
}

// DeleteSlipAttachments mocks base method.
func (m *MockRepositoryInterface) DeleteSlipAttachments(ctx context.Context, tx datastore.DB, slipID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSlipAttachments", ctx, tx, slipID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteSlipAttachments indicates an expected call of DeleteSlipAttachments.
func (mr *MockRepositoryInterfaceMockRecorder) DeleteSlipAttachments(ctx, tx, slipID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSlipAttachments", reflect.TypeOf((*MockRepositoryInterface)(nil).DeleteSlipAttachments), ctx, tx, slipID)
}

// GetAll mocks base method.
func (m *MockRepositoryInterface) GetAll(ctx context.Context, req *ListSlipRequest) ([]SlipWithDetailsView, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", ctx, req)
	ret0, _ := ret[0].([]SlipWithDetailsView)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockRepositoryInterfaceMockRecorder) GetAll(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockRepositoryInterface)(nil).GetAll), ctx, req)
}

// GetAttachmentByID mocks base method.
func (m *MockRepositoryInterface) GetAttachmentByID(ctx context.Context, attachmentID string) (*SlipAttachment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAttachmentByID", ctx, attachmentID)
	ret0, _ := ret[0].(*SlipAttachment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAttachmentByID indicates an expected call of GetAttachmentByID.
func (mr *MockRepositoryInterfaceMockRecorder) GetAttachmentByID(ctx, attachmentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAttachmentByID", reflect.TypeOf((*MockRepositoryInterface)(nil).GetAttachmentByID), ctx, attachmentID)
}

// GetByIIRID mocks base method.
func (m *MockRepositoryInterface) GetByIIRID(ctx context.Context, iirID string, req *ListSlipRequest) ([]SlipWithDetailsView, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByIIRID", ctx, iirID, req)
	ret0, _ := ret[0].([]SlipWithDetailsView)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByIIRID indicates an expected call of GetByIIRID.
func (mr *MockRepositoryInterfaceMockRecorder) GetByIIRID(ctx, iirID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByIIRID", reflect.TypeOf((*MockRepositoryInterface)(nil).GetByIIRID), ctx, iirID, req)
}

// GetByUserID mocks base method.
func (m *MockRepositoryInterface) GetByUserID(ctx context.Context, userID string, req *ListSlipRequest) ([]SlipWithDetailsView, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUserID", ctx, userID, req)
	ret0, _ := ret[0].([]SlipWithDetailsView)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByUserID indicates an expected call of GetByUserID.
func (mr *MockRepositoryInterfaceMockRecorder) GetByUserID(ctx, userID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUserID", reflect.TypeOf((*MockRepositoryInterface)(nil).GetByUserID), ctx, userID, req)
}

// GetDB mocks base method.
func (m *MockRepositoryInterface) GetDB() *sqlx.DB {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDB")
	ret0, _ := ret[0].(*sqlx.DB)
	return ret0
}

// GetDB indicates an expected call of GetDB.
func (mr *MockRepositoryInterfaceMockRecorder) GetDB() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDB", reflect.TypeOf((*MockRepositoryInterface)(nil).GetDB))
}

// GetSlipAttachments mocks base method.
func (m *MockRepositoryInterface) GetSlipAttachments(ctx context.Context, slipID string) ([]SlipAttachment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSlipAttachments", ctx, slipID)
	ret0, _ := ret[0].([]SlipAttachment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSlipAttachments indicates an expected call of GetSlipAttachments.
func (mr *MockRepositoryInterfaceMockRecorder) GetSlipAttachments(ctx, slipID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSlipAttachments", reflect.TypeOf((*MockRepositoryInterface)(nil).GetSlipAttachments), ctx, slipID)
}

// GetSlipByID mocks base method.
func (m *MockRepositoryInterface) GetSlipByID(ctx context.Context, id string) (*Slip, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSlipByID", ctx, id)
	ret0, _ := ret[0].(*Slip)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSlipByID indicates an expected call of GetSlipByID.
func (mr *MockRepositoryInterfaceMockRecorder) GetSlipByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSlipByID", reflect.TypeOf((*MockRepositoryInterface)(nil).GetSlipByID), ctx, id)
}

// GetSlipByIDWithDetails mocks base method.
func (m *MockRepositoryInterface) GetSlipByIDWithDetails(ctx context.Context, id string) (*SlipWithDetailsView, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSlipByIDWithDetails", ctx, id)
	ret0, _ := ret[0].(*SlipWithDetailsView)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSlipByIDWithDetails indicates an expected call of GetSlipByIDWithDetails.
func (mr *MockRepositoryInterfaceMockRecorder) GetSlipByIDWithDetails(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSlipByIDWithDetails", reflect.TypeOf((*MockRepositoryInterface)(nil).GetSlipByIDWithDetails), ctx, id)
}

// GetSlipCategories mocks base method.
func (m *MockRepositoryInterface) GetSlipCategories(ctx context.Context) ([]SlipCategory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSlipCategories", ctx)
	ret0, _ := ret[0].([]SlipCategory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSlipCategories indicates an expected call of GetSlipCategories.
func (mr *MockRepositoryInterfaceMockRecorder) GetSlipCategories(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSlipCategories", reflect.TypeOf((*MockRepositoryInterface)(nil).GetSlipCategories), ctx)
}

// GetSlipStats mocks base method.
func (m *MockRepositoryInterface) GetSlipStats(ctx context.Context, iirID *string, req *ListSlipRequest) ([]SlipStatusCount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSlipStats", ctx, iirID, req)
	ret0, _ := ret[0].([]SlipStatusCount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSlipStats indicates an expected call of GetSlipStats.
func (mr *MockRepositoryInterfaceMockRecorder) GetSlipStats(ctx, iirID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSlipStats", reflect.TypeOf((*MockRepositoryInterface)(nil).GetSlipStats), ctx, iirID, req)
}

// GetSlipStatuses mocks base method.
func (m *MockRepositoryInterface) GetSlipStatuses(ctx context.Context) ([]SlipStatus, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSlipStatuses", ctx)
	ret0, _ := ret[0].([]SlipStatus)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSlipStatuses indicates an expected call of GetSlipStatuses.
func (mr *MockRepositoryInterfaceMockRecorder) GetSlipStatuses(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSlipStatuses", reflect.TypeOf((*MockRepositoryInterface)(nil).GetSlipStatuses), ctx)
}

// GetTotalSlipsCount mocks base method.
func (m *MockRepositoryInterface) GetTotalSlipsCount(ctx context.Context, req *ListSlipRequest) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTotalSlipsCount", ctx, req)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTotalSlipsCount indicates an expected call of GetTotalSlipsCount.
func (mr *MockRepositoryInterfaceMockRecorder) GetTotalSlipsCount(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTotalSlipsCount", reflect.TypeOf((*MockRepositoryInterface)(nil).GetTotalSlipsCount), ctx, req)
}

// GetTotalUrgentSlipsCount mocks base method.
func (m *MockRepositoryInterface) GetTotalUrgentSlipsCount(ctx context.Context, req *ListSlipRequest) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTotalUrgentSlipsCount", ctx, req)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTotalUrgentSlipsCount indicates an expected call of GetTotalUrgentSlipsCount.
func (mr *MockRepositoryInterfaceMockRecorder) GetTotalUrgentSlipsCount(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTotalUrgentSlipsCount", reflect.TypeOf((*MockRepositoryInterface)(nil).GetTotalUrgentSlipsCount), ctx, req)
}

// GetUrgentSlips mocks base method.
func (m *MockRepositoryInterface) GetUrgentSlips(ctx context.Context, req *ListSlipRequest) ([]SlipWithDetailsView, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUrgentSlips", ctx, req)
	ret0, _ := ret[0].([]SlipWithDetailsView)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUrgentSlips indicates an expected call of GetUrgentSlips.
func (mr *MockRepositoryInterfaceMockRecorder) GetUrgentSlips(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUrgentSlips", reflect.TypeOf((*MockRepositoryInterface)(nil).GetUrgentSlips), ctx, req)
}

// GetUserIDBySlipID mocks base method.
func (m *MockRepositoryInterface) GetUserIDBySlipID(ctx context.Context, id string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserIDBySlipID", ctx, id)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserIDBySlipID indicates an expected call of GetUserIDBySlipID.
func (mr *MockRepositoryInterfaceMockRecorder) GetUserIDBySlipID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserIDBySlipID", reflect.TypeOf((*MockRepositoryInterface)(nil).GetUserIDBySlipID), ctx, id)
}

// SaveSlipAttachment mocks base method.
func (m *MockRepositoryInterface) SaveSlipAttachment(ctx context.Context, tx datastore.DB, attachment *SlipAttachment) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveSlipAttachment", ctx, tx, attachment)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveSlipAttachment indicates an expected call of SaveSlipAttachment.
func (mr *MockRepositoryInterfaceMockRecorder) SaveSlipAttachment(ctx, tx, attachment any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveSlipAttachment", reflect.TypeOf((*MockRepositoryInterface)(nil).SaveSlipAttachment), ctx, tx, attachment)
}

// UpdateSlip mocks base method.
func (m *MockRepositoryInterface) UpdateSlip(ctx context.Context, tx datastore.DB, slip *Slip) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSlip", ctx, tx, slip)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateSlip indicates an expected call of UpdateSlip.
func (mr *MockRepositoryInterfaceMockRecorder) UpdateSlip(ctx, tx, slip any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSlip", reflect.TypeOf((*MockRepositoryInterface)(nil).UpdateSlip), ctx, tx, slip)
}

// UpdateStatus mocks base method.
func (m *MockRepositoryInterface) UpdateStatus(ctx context.Context, tx datastore.DB, id, statusName, adminNotes string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatus", ctx, tx, id, statusName, adminNotes)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStatus indicates an expected call of UpdateStatus.
func (mr *MockRepositoryInterfaceMockRecorder) UpdateStatus(ctx, tx, id, statusName, adminNotes any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatus", reflect.TypeOf((*MockRepositoryInterface)(nil).UpdateStatus), ctx, tx, id, statusName, adminNotes)
}

// WithTransaction mocks base method.
func (m *MockRepositoryInterface) WithTransaction(ctx context.Context, fn func(datastore.DB) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithTransaction", ctx, fn)
	ret0, _ := ret[0].(error)
	return ret0
}

// WithTransaction indicates an expected call of WithTransaction.
func (mr *MockRepositoryInterfaceMockRecorder) WithTransaction(ctx, fn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithTransaction", reflect.TypeOf((*MockRepositoryInterface)(nil).WithTransaction), ctx, fn)
}
