// Code generated by MockGen. DO NOT EDIT.
// Source: internal/features/students/interface.go
//
// Generated by this command:
//
//	mockgen -source=internal/features/students/interface.go -package=students -destination=internal/features/students/mock_interfaces.go
//

// Package students is a generated GoMock package.
package students

import (
	context "context"
	multipart "mime/multipart"
	reflect "reflect"

	sqlx "github.com/jmoiron/sqlx"
	datastore "github.com/olazo-johnalbert/duckload-api/internal/infrastructure/datastore"
	gomock "go.uber.org/mock/gomock"
)

// MockServiceInterface is a mock of ServiceInterface interface.
type MockServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockServiceInterfaceMockRecorder
	isgomock struct{}
}

// MockServiceInterfaceMockRecorder is the mock recorder for MockServiceInterface.
type MockServiceInterfaceMockRecorder struct {
	mock *MockServiceInterface
}

// NewMockServiceInterface creates a new mock instance.
func NewMockServiceInterface(ctrl *gomock.Controller) *MockServiceInterface {
	mock := &MockServiceInterface{ctrl: ctrl}
	mock.recorder = &MockServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockServiceInterface) EXPECT() *MockServiceInterfaceMockRecorder {
	return m.recorder
}

// BulkUpdateStudentStatus mocks base method.
func (m *MockServiceInterface) BulkUpdateStudentStatus(ctx context.Context, req BulkUpdateStatusRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BulkUpdateStudentStatus", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// BulkUpdateStudentStatus indicates an expected call of BulkUpdateStudentStatus.
func (mr *MockServiceInterfaceMockRecorder) BulkUpdateStudentStatus(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BulkUpdateStudentStatus", reflect.TypeOf((*MockServiceInterface)(nil).BulkUpdateStudentStatus), ctx, req)
}

// GenerateIIR mocks base method.
func (m *MockServiceInterface) GenerateIIR(ctx context.Context, iirID string) ([]byte, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateIIR", ctx, iirID)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GenerateIIR indicates an expected call of GenerateIIR.
func (mr *MockServiceInterfaceMockRecorder) GenerateIIR(ctx, iirID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateIIR", reflect.TypeOf((*MockServiceInterface)(nil).GenerateIIR), ctx, iirID)
}

// GetActivityOptions mocks base method.
func (m *MockServiceInterface) GetActivityOptions(ctx context.Context) ([]ActivityOption, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActivityOptions", ctx)
	ret0, _ := ret[0].([]ActivityOption)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActivityOptions indicates an expected call of GetActivityOptions.
func (mr *MockServiceInterfaceMockRecorder) GetActivityOptions(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActivityOptions", reflect.TypeOf((*MockServiceInterface)(nil).GetActivityOptions), ctx)
}

// GetCivilStatusTypes mocks base method.
func (m *MockServiceInterface) GetCivilStatusTypes(ctx context.Context) ([]CivilStatusType, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCivilStatusTypes", ctx)
	ret0, _ := ret[0].([]CivilStatusType)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCivilStatusTypes indicates an expected call of GetCivilStatusTypes.
func (mr *MockServiceInterfaceMockRecorder) GetCivilStatusTypes(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCivilStatusTypes", reflect.TypeOf((*MockServiceInterface)(nil).GetCivilStatusTypes), ctx)
}

// GetCourses mocks base method.
func (m *MockServiceInterface) GetCourses(ctx context.Context) ([]Course, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCourses", ctx)
	ret0, _ := ret[0].([]Course)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCourses indicates an expected call of GetCourses.
func (mr *MockServiceInterfaceMockRecorder) GetCourses(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCourses", reflect.TypeOf((*MockServiceInterface)(nil).GetCourses), ctx)
}

// GetEducationalBackground mocks base method.
func (m *MockServiceInterface) GetEducationalBackground(ctx context.Context, iirID string) (*EducationalBackgroundDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEducationalBackground", ctx, iirID)
	ret0, _ := ret[0].(*EducationalBackgroundDTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEducationalBackground indicates an expected call of GetEducationalBackground.
func (mr *MockServiceInterfaceMockRecorder) GetEducationalBackground(ctx, iirID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEducationalBackground", reflect.TypeOf((*MockServiceInterface)(nil).GetEducationalBackground), ctx, iirID)
}

// GetEducationalLevels mocks base method.
func (m *MockServiceInterface) GetEducationalLevels(ctx context.Context) ([]EducationalLevel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEducationalLevels", ctx)
	ret0, _ := ret[0].([]EducationalLevel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEducationalLevels indicates an expected call of GetEducationalLevels.
func (mr *MockServiceInterfaceMockRecorder) GetEducationalLevels(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEducationalLevels", reflect.TypeOf((*MockServiceInterface)(nil).GetEducationalLevels), ctx)
}

// GetEnrollmentReasons mocks base method.
func (m *MockServiceInterface) GetEnrollmentReasons(ctx context.Context) ([]EnrollmentReason, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEnrollmentReasons", ctx)
	ret0, _ := ret[0].([]EnrollmentReason)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEnrollmentReasons indicates an expected call of GetEnrollmentReasons.
func (mr *MockServiceInterfaceMockRecorder) GetEnrollmentReasons(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEnrollmentReasons", reflect.TypeOf((*MockServiceInterface)(nil).GetEnrollmentReasons), ctx)
}

// GetGenders mocks base method.
func (m *MockServiceInterface) GetGenders(ctx context.Context) ([]Gender, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGenders", ctx)
	ret0, _ := ret[0].([]Gender)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGenders indicates an expected call of GetGenders.
func (mr *MockServiceInterfaceMockRecorder) GetGenders(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGenders", reflect.TypeOf((*MockServiceInterface)(nil).GetGenders), ctx)
}

// GetIIRDraft mocks base method.
func (m *MockServiceInterface) GetIIRDraft(ctx context.Context, userID string) (*ComprehensiveProfileDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIIRDraft", ctx, userID)
	ret0, _ := ret[0].(*ComprehensiveProfileDTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetIIRDraft indicates an expected call of GetIIRDraft.
func (mr *MockServiceInterfaceMockRecorder) GetIIRDraft(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIIRDraft", reflect.TypeOf((*MockServiceInterface)(nil).GetIIRDraft), ctx, userID)
}

// GetIncomeRanges mocks base method.
func (m *MockServiceInterface) GetIncomeRanges(ctx context.Context) ([]IncomeRange, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIncomeRanges", ctx)
	ret0, _ := ret[0].([]IncomeRange)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetIncomeRanges indicates an expected call of GetIncomeRanges.
func (mr *MockServiceInterfaceMockRecorder) GetIncomeRanges(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIncomeRanges", reflect.TypeOf((*MockServiceInterface)(nil).GetIncomeRanges), ctx)
}

// GetNatureOfResidenceTypes mocks base method.
func (m *MockServiceInterface) GetNatureOfResidenceTypes(ctx context.Context) ([]NatureOfResidenceType, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNatureOfResidenceTypes", ctx)
	ret0, _ := ret[0].([]NatureOfResidenceType)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNatureOfResidenceTypes indicates an expected call of GetNatureOfResidenceTypes.
func (mr *MockServiceInterfaceMockRecorder) GetNatureOfResidenceTypes(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNatureOfResidenceTypes", reflect.TypeOf((*MockServiceInterface)(nil).GetNatureOfResidenceTypes), ctx)
}

// GetParentalStatusTypes mocks base method.
func (m *MockServiceInterface) GetParentalStatusTypes(ctx context.Context) ([]ParentalStatusType, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetParentalStatusTypes", ctx)
	ret0, _ := ret[0].([]ParentalStatusType)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetParentalStatusTypes indicates an expected call of GetParentalStatusTypes.
func (mr *MockServiceInterfaceMockRecorder) GetParentalStatusTypes(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetParentalStatusTypes", reflect.TypeOf((*MockServiceInterface)(nil).GetParentalStatusTypes), ctx)
}

// GetReligions mocks base method.
func (m *MockServiceInterface) GetReligions(ctx context.Context) ([]Religion, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetReligions", ctx)
	ret0, _ := ret[0].([]Religion)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetReligions indicates an expected call of GetReligions.
func (mr *MockServiceInterfaceMockRecorder) GetReligions(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetReligions", reflect.TypeOf((*MockServiceInterface)(nil).GetReligions), ctx)
}

// GetSiblingSupportTypes mocks base method.
func (m *MockServiceInterface) GetSiblingSupportTypes(ctx context.Context) ([]SibilingSupportType, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSiblingSupportTypes", ctx)
	ret0, _ := ret[0].([]SibilingSupportType)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSiblingSupportTypes indicates an expected call of GetSiblingSupportTypes.
func (mr *MockServiceInterfaceMockRecorder) GetSiblingSupportTypes(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSiblingSupportTypes", reflect.TypeOf((*MockServiceInterface)(nil).GetSiblingSupportTypes), ctx)
}

// GetStudentActivities mocks base method.
func (m *MockServiceInterface) GetStudentActivities(ctx context.Context, iirID string) ([]StudentActivityDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStudentActivities", ctx, iirID)
	ret0, _ := ret[0].([]StudentActivityDTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStudentActivities indicates an expected call of GetStudentActivities.
func (mr *MockServiceInterfaceMockRecorder) GetStudentActivities(ctx, iirID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStudentActivities", reflect.TypeOf((*MockServiceInterface)(nil).GetStudentActivities), ctx, iirID)
}

// GetStudentAddresses mocks base method.
func (m *MockServiceInterface) GetStudentAddresses(ctx context.Context, iirID string) ([]StudentAddressDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStudentAddresses", ctx, iirID)
	ret0, _ := ret[0].([]StudentAddressDTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStudentAddresses indicates an expected call of GetStudentAddresses.
func (mr *MockServiceInterfaceMockRecorder) GetStudentAddresses(ctx, iirID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStudentAddresses", reflect.TypeOf((*MockServiceInterface)(nil).GetStudentAddresses), ctx, iirID)
}

// GetStudentBasicInfo mocks base method.
func (m *MockServiceInterface) GetStudentBasicInfo(ctx context.Context, iirID string) (*StudentBasicInfoViewDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStudentBasicInfo", ctx, iirID)
	ret0, _ := ret[0].(*StudentBasicInfoViewDTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStudentBasicInfo indicates an expected call of GetStudentBasicInfo.
func (mr *MockServiceInterfaceMockRecorder) GetStudentBasicInfo(ctx, iirID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStudentBasicInfo", reflect.TypeOf((*MockServiceInterface)(nil).GetStudentBasicInfo), ctx, iirID)
}

// GetStudentCOR mocks base method.
func (m *MockServiceInterface) GetStudentCOR(ctx context.Context, userID string) (StudentCOR, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStudentCOR", ctx, userID)
	ret0, _ := ret[0].(StudentCOR)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStudentCOR indicates an expected call of GetStudentCOR.
func (mr *MockServiceInterfaceMockRecorder) GetStudentCOR(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStudentCOR", reflect.TypeOf((*MockServiceInterface)(nil).GetStudentCOR), ctx, userID)
}

// GetStudentCORs mocks base method.
func (m *MockServiceInterface) GetStudentCORs(ctx context.Context, userID string) ([]StudentCOR, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStudentCORs", ctx, userID)
	ret0, _ := ret[0].([]StudentCOR)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStudentCORs indicates an expected call of GetStudentCORs.
func (mr *MockServiceInterfaceMockRecorder) GetStudentCORs(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStudentCORs", reflect.TypeOf((*MockServiceInterface)(nil).GetStudentCORs), ctx, userID)
}

// GetStudentConsultations mocks base method.
func (m *MockServiceInterface) GetStudentConsultations(ctx context.Context, iirID string) ([]StudentConsultationDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStudentConsultations", ctx, iirID)
	ret0, _ := ret[0].([]StudentConsultationDTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStudentConsultations indicates an expected call of GetStudentConsultations.
func (mr *MockServiceInterfaceMockRecorder) GetStudentConsultations(ctx, iirID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStudentConsultations", reflect.TypeOf((*MockServiceInterface)(nil).GetStudentConsultations), ctx, iirID)
}

// GetStudentEnrollmentReasons mocks base method.
func (m *MockServiceInterface) GetStudentEnrollmentReasons(ctx context.Context, iirID string) ([]StudentSelectedReasonDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStudentEnrollmentReasons", ctx, iirID)
	ret0, _ := ret[0].([]StudentSelectedReasonDTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStudentEnrollmentReasons indicates an expected call of GetStudentEnrollmentReasons.
func (mr *MockServiceInterfaceMockRecorder) GetStudentEnrollmentReasons(ctx, iirID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStudentEnrollmentReasons", reflect.TypeOf((*MockServiceInterface)(nil).GetStudentEnrollmentReasons), ctx, iirID)
}

// GetStudentFamilyBackground mocks base method.
func (m *MockServiceInterface) GetStudentFamilyBackground(ctx context.Context, iirID string) (*FamilyBackgroundDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStudentFamilyBackground", ctx, iirID)
	ret0, _ := ret[0].(*FamilyBackgroundDTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStudentFamilyBackground indicates an expected call of GetStudentFamilyBackground.
func (mr *MockServiceInterfaceMockRecorder) GetStudentFamilyBackground(ctx, iirID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStudentFamilyBackground", reflect.TypeOf((*MockServiceInterface)(nil).GetStudentFamilyBackground), ctx, iirID)
}

// GetStudentFinancialInfo mocks base method.
func (m *MockServiceInterface) GetStudentFinancialInfo(ctx context.Context, iirID string) (*StudentFinanceDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStudentFinancialInfo", ctx, iirID)
	ret0, _ := ret[0].(*StudentFinanceDTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStudentFinancialInfo indicates an expected call of GetStudentFinancialInfo.
func (mr *MockServiceInterfaceMockRecorder) GetStudentFinancialInfo(ctx, iirID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStudentFinancialInfo", reflect.TypeOf((*MockServiceInterface)(nil).GetStudentFinancialInfo), ctx, iirID)
}

// GetStudentHealthRecord mocks base method.
func (m *MockServiceInterface) GetStudentHealthRecord(ctx context.Context, iirID string) (*StudentHealthRecordDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStudentHealthRecord", ctx, iirID)
	ret0, _ := ret[0].(*StudentHealthRecordDTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStudentHealthRecord indicates an expected call of GetStudentHealthRecord.
func (mr *MockServiceInterfaceMockRecorder) GetStudentHealthRecord(ctx, iirID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStudentHealthRecord", reflect.TypeOf((*MockServiceInterface)(nil).GetStudentHealthRecord), ctx, iirID)
}

// GetStudentHobbies mocks base method.
func (m *MockServiceInterface) GetStudentHobbies(ctx context.Context, iirID string) ([]StudentHobbyDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStudentHobbies", ctx, iirID)
	ret0, _ := ret[0].([]StudentHobbyDTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStudentHobbies indicates an expected call of GetStudentHobbies.
func (mr *MockServiceInterfaceMockRecorder) GetStudentHobbies(ctx, iirID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStudentHobbies", reflect.TypeOf((*MockServiceInterface)(nil).GetStudentHobbies), ctx, iirID)
}

// GetStudentIIR mocks base method.
func (m *MockServiceInterface) GetStudentIIR(ctx context.Context, iirID string) (*IIRRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStudentIIR", ctx, iirID)
	ret0, _ := ret[0].(*IIRRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStudentIIR indicates an expected call of GetStudentIIR.
func (mr *MockServiceInterfaceMockRecorder) GetStudentIIR(ctx, iirID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStudentIIR", reflect.TypeOf((*MockServiceInterface)(nil).GetStudentIIR), ctx, iirID)
}

// GetStudentIIRByUserID mocks base method.
func (m *MockServiceInterface) GetStudentIIRByUserID(ctx context.Context, userID string) (*IIRRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStudentIIRByUserID", ctx, userID)
	ret0, _ := ret[0].(*IIRRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStudentIIRByUserID indicates an expected call of GetStudentIIRByUserID.
func (mr *MockServiceInterfaceMockRecorder) GetStudentIIRByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStudentIIRByUserID", reflect.TypeOf((*MockServiceInterface)(nil).GetStudentIIRByUserID), ctx, userID)
}

// GetStudentPersonalInfo mocks base method.
func (m *MockServiceInterface) GetStudentPersonalInfo(ctx context.Context, iirID string) (*StudentPersonalInfoDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStudentPersonalInfo", ctx, iirID)
	ret0, _ := ret[0].(*StudentPersonalInfoDTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStudentPersonalInfo indicates an expected call of GetStudentPersonalInfo.
func (mr *MockServiceInterfaceMockRecorder) GetStudentPersonalInfo(ctx, iirID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStudentPersonalInfo", reflect.TypeOf((*MockServiceInterface)(nil).GetStudentPersonalInfo), ctx, iirID)
}

// GetStudentProfile mocks base method.
func (m *MockServiceInterface) GetStudentProfile(ctx context.Context, iirID string) (*ComprehensiveProfileDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStudentProfile", ctx, iirID)
	ret0, _ := ret[0].(*ComprehensiveProfileDTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStudentProfile indicates an expected call of GetStudentProfile.
func (mr *MockServiceInterfaceMockRecorder) GetStudentProfile(ctx, iirID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStudentProfile", reflect.TypeOf((*MockServiceInterface)(nil).GetStudentProfile), ctx, iirID)
}

// GetStudentRelatedPersons mocks base method.
func (m *MockServiceInterface) GetStudentRelatedPersons(ctx context.Context, iirID string) ([]RelatedPersonDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStudentRelatedPersons", ctx, iirID)
	ret0, _ := ret[0].([]RelatedPersonDTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStudentRelatedPersons indicates an expected call of GetStudentRelatedPersons.
func (mr *MockServiceInterfaceMockRecorder) GetStudentRelatedPersons(ctx, iirID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStudentRelatedPersons", reflect.TypeOf((*MockServiceInterface)(nil).GetStudentRelatedPersons), ctx, iirID)
}

// GetStudentRelationshipTypes mocks base method.
func (m *MockServiceInterface) GetStudentRelationshipTypes(ctx context.Context) ([]StudentRelationshipType, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStudentRelationshipTypes", ctx)
	ret0, _ := ret[0].([]StudentRelationshipType)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStudentRelationshipTypes indicates an expected call of GetStudentRelationshipTypes.
func (mr *MockServiceInterfaceMockRecorder) GetStudentRelationshipTypes(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStudentRelationshipTypes", reflect.TypeOf((*MockServiceInterface)(nil).GetStudentRelationshipTypes), ctx)
}

// GetStudentStatuses mocks base method.
func (m *MockServiceInterface) GetStudentStatuses(ctx context.Context) ([]StudentStatus, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStudentStatuses", ctx)
	ret0, _ := ret[0].([]StudentStatus)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStudentStatuses indicates an expected call of GetStudentStatuses.
func (mr *MockServiceInterfaceMockRecorder) GetStudentStatuses(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStudentStatuses", reflect.TypeOf((*MockServiceInterface)(nil).GetStudentStatuses), ctx)
}

// GetStudentSubjectPreferences mocks base method.
func (m *MockServiceInterface) GetStudentSubjectPreferences(ctx context.Context, iirID string) ([]StudentSubjectPreferenceDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStudentSubjectPreferences", ctx, iirID)
	ret0, _ := ret[0].([]StudentSubjectPreferenceDTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStudentSubjectPreferences indicates an expected call of GetStudentSubjectPreferences.
func (mr *MockServiceInterfaceMockRecorder) GetStudentSubjectPreferences(ctx, iirID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStudentSubjectPreferences", reflect.TypeOf((*MockServiceInterface)(nil).GetStudentSubjectPreferences), ctx, iirID)
}

// GetStudentSupportTypes mocks base method.
func (m *MockServiceInterface) GetStudentSupportTypes(ctx context.Context) ([]StudentSupportType, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStudentSupportTypes", ctx)
	ret0, _ := ret[0].([]StudentSupportType)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStudentSupportTypes indicates an expected call of GetStudentSupportTypes.
func (mr *MockServiceInterfaceMockRecorder) GetStudentSupportTypes(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStudentSupportTypes", reflect.TypeOf((*MockServiceInterface)(nil).GetStudentSupportTypes), ctx)
}

// GetStudentTestResults mocks base method.
func (m *MockServiceInterface) GetStudentTestResults(ctx context.Context, iirID string) ([]TestResultDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStudentTestResults", ctx, iirID)
	ret0, _ := ret[0].([]TestResultDTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStudentTestResults indicates an expected call of GetStudentTestResults.
func (mr *MockServiceInterfaceMockRecorder) GetStudentTestResults(ctx, iirID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStudentTestResults", reflect.TypeOf((*MockServiceInterface)(nil).GetStudentTestResults), ctx, iirID)
}

// IsStudentLocked mocks base method.
func (m *MockServiceInterface) IsStudentLocked(ctx context.Context, iirID string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsStudentLocked", ctx, iirID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsStudentLocked indicates an expected call of IsStudentLocked.
func (mr *MockServiceInterfaceMockRecorder) IsStudentLocked(ctx, iirID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsStudentLocked", reflect.TypeOf((*MockServiceInterface)(nil).IsStudentLocked), ctx, iirID)
}

// ListStudents mocks base method.
func (m *MockServiceInterface) ListStudents(ctx context.Context, req ListStudentsRequest) (*ListStudentsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListStudents", ctx, req)
	ret0, _ := ret[0].(*ListStudentsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListStudents indicates an expected call of ListStudents.
func (mr *MockServiceInterfaceMockRecorder) ListStudents(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListStudents", reflect.TypeOf((*MockServiceInterface)(nil).ListStudents), ctx, req)
}

// SaveIIRDraft mocks base method.
func (m *MockServiceInterface) SaveIIRDraft(ctx context.Context, userID string, req ComprehensiveProfileDTO) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveIIRDraft", ctx, userID, req)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SaveIIRDraft indicates an expected call of SaveIIRDraft.
func (mr *MockServiceInterfaceMockRecorder) SaveIIRDraft(ctx, userID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveIIRDraft", reflect.TypeOf((*MockServiceInterface)(nil).SaveIIRDraft), ctx, userID, req)
}

// SubmitCOR mocks base method.
func (m *MockServiceInterface) SubmitCOR(ctx context.Context, userID string, file *multipart.FileHeader) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SubmitCOR", ctx, userID, file)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SubmitCOR indicates an expected call of SubmitCOR.
func (mr *MockServiceInterfaceMockRecorder) SubmitCOR(ctx, userID, file any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubmitCOR", reflect.TypeOf((*MockServiceInterface)(nil).SubmitCOR), ctx, userID, file)
}

// SubmitStudentIIR mocks base method.
func (m *MockServiceInterface) SubmitStudentIIR(ctx context.Context, userID string, req ComprehensiveProfileDTO) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SubmitStudentIIR", ctx, userID, req)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SubmitStudentIIR indicates an expected call of SubmitStudentIIR.
func (mr *MockServiceInterfaceMockRecorder) SubmitStudentIIR(ctx, userID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubmitStudentIIR", reflect.TypeOf((*MockServiceInterface)(nil).SubmitStudentIIR), ctx, userID, req)
}

// MockRepositoryInterface is a mock of RepositoryInterface interface.
type MockRepositoryInterface struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryInterfaceMockRecorder
	isgomock struct{}
}

// MockRepositoryInterfaceMockRecorder is the mock recorder for MockRepositoryInterface.
type MockRepositoryInterfaceMockRecorder struct {
	mock *MockRepositoryInterface
}

// NewMockRepositoryInterface creates a new mock instance.
func NewMockRepositoryInterface(ctrl *gomock.Controller) *MockRepositoryInterface {
	mock := &MockRepositoryInterface{ctrl: ctrl}
	mock.recorder = &MockRepositoryInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepositoryInterface) EXPECT() *MockRepositoryInterfaceMockRecorder {
	return m.recorder
}

// BeginTx mocks base method.
func (m *MockRepositoryInterface) BeginTx(ctx context.Context) (datastore.DB, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BeginTx", ctx)
	ret0, _ := ret[0].(datastore.DB)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BeginTx indicates an expected call of BeginTx.
func (mr *MockRepositoryInterfaceMockRecorder) BeginTx(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BeginTx", reflect.TypeOf((*MockRepositoryInterface)(nil).BeginTx), ctx)
}

// BulkUpdateStudentStatus mocks base method.
func (m *MockRepositoryInterface) BulkUpdateStudentStatus(ctx context.Context, req BulkUpdateStatusRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BulkUpdateStudentStatus", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// BulkUpdateStudentStatus indicates an expected call of BulkUpdateStudentStatus.
func (mr *MockRepositoryInterfaceMockRecorder) BulkUpdateStudentStatus(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BulkUpdateStudentStatus", reflect.TypeOf((*MockRepositoryInterface)(nil).BulkUpdateStudentStatus), ctx, req)
}

// CreateStudentActivity mocks base method.
func (m *MockRepositoryInterface) CreateStudentActivity(ctx context.Context, tx datastore.DB, sa *StudentActivity) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateStudentActivity", ctx, tx, sa)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateStudentActivity indicates an expected call of CreateStudentActivity.
func (mr *MockRepositoryInterfaceMockRecorder) CreateStudentActivity(ctx, tx, sa any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateStudentActivity", reflect.TypeOf((*MockRepositoryInterface)(nil).CreateStudentActivity), ctx, tx, sa)
}

// CreateStudentFinancialSupport mocks base method.
func (m *MockRepositoryInterface) CreateStudentFinancialSupport(ctx context.Context, tx datastore.DB, sfs *StudentFinancialSupport) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateStudentFinancialSupport", ctx, tx, sfs)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateStudentFinancialSupport indicates an expected call of CreateStudentFinancialSupport.
func (mr *MockRepositoryInterfaceMockRecorder) CreateStudentFinancialSupport(ctx, tx, sfs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateStudentFinancialSupport", reflect.TypeOf((*MockRepositoryInterface)(nil).CreateStudentFinancialSupport), ctx, tx, sfs)
}

// CreateStudentHobby mocks base method.
func (m *MockRepositoryInterface) CreateStudentHobby(ctx context.Context, tx datastore.DB, sh *StudentHobby) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateStudentHobby", ctx, tx, sh)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateStudentHobby indicates an expected call of CreateStudentHobby.
func (mr *MockRepositoryInterfaceMockRecorder) CreateStudentHobby(ctx, tx, sh any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateStudentHobby", reflect.TypeOf((*MockRepositoryInterface)(nil).CreateStudentHobby), ctx, tx, sh)
}

// CreateStudentSelectedReason mocks base method.
func (m *MockRepositoryInterface) CreateStudentSelectedReason(ctx context.Context, tx datastore.DB, ssr *StudentSelectedReason) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateStudentSelectedReason", ctx, tx, ssr)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateStudentSelectedReason indicates an expected call of CreateStudentSelectedReason.
func (mr *MockRepositoryInterfaceMockRecorder) CreateStudentSelectedReason(ctx, tx, ssr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateStudentSelectedReason", reflect.TypeOf((*MockRepositoryInterface)(nil).CreateStudentSelectedReason), ctx, tx, ssr)
}

// CreateStudentSiblingSupport mocks base method.
func (m *MockRepositoryInterface) CreateStudentSiblingSupport(ctx context.Context, tx datastore.DB, sss *StudentSiblingSupport) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateStudentSiblingSupport", ctx, tx, sss)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateStudentSiblingSupport indicates an expected call of CreateStudentSiblingSupport.
func (mr *MockRepositoryInterfaceMockRecorder) CreateStudentSiblingSupport(ctx, tx, sss any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateStudentSiblingSupport", reflect.TypeOf((*MockRepositoryInterface)(nil).CreateStudentSiblingSupport), ctx, tx, sss)
}

// CreateStudentSubjectPreference mocks base method.
func (m *MockRepositoryInterface) CreateStudentSubjectPreference(ctx context.Context, tx datastore.DB, ssp *StudentSubjectPreference) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateStudentSubjectPreference", ctx, tx, ssp)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateStudentSubjectPreference indicates an expected call of CreateStudentSubjectPreference.
func (mr *MockRepositoryInterfaceMockRecorder) CreateStudentSubjectPreference(ctx, tx, ssp any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateStudentSubjectPreference", reflect.TypeOf((*MockRepositoryInterface)(nil).CreateStudentSubjectPreference), ctx, tx, ssp)
}

// DeleteSchoolDetailsByEBID mocks base method.
func (m *MockRepositoryInterface) DeleteSchoolDetailsByEBID(ctx context.Context, tx datastore.DB, ebID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSchoolDetailsByEBID", ctx, tx, ebID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteSchoolDetailsByEBID indicates an expected call of DeleteSchoolDetailsByEBID.
func (mr *MockRepositoryInterfaceMockRecorder) DeleteSchoolDetailsByEBID(ctx, tx, ebID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSchoolDetailsByEBID", reflect.TypeOf((*MockRepositoryInterface)(nil).DeleteSchoolDetailsByEBID), ctx, tx, ebID)
}

// DeleteSignificantNotesByIIRID mocks base method.
func (m *MockRepositoryInterface) DeleteSignificantNotesByIIRID(ctx context.Context, tx datastore.DB, iirID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSignificantNotesByIIRID", ctx, tx, iirID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteSignificantNotesByIIRID indicates an expected call of DeleteSignificantNotesByIIRID.
func (mr *MockRepositoryInterfaceMockRecorder) DeleteSignificantNotesByIIRID(ctx, tx, iirID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSignificantNotesByIIRID", reflect.TypeOf((*MockRepositoryInterface)(nil).DeleteSignificantNotesByIIRID), ctx, tx, iirID)
}

// DeleteStudentActivitiesByIIRID mocks base method.
func (m *MockRepositoryInterface) DeleteStudentActivitiesByIIRID(ctx context.Context, tx datastore.DB, iirID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteStudentActivitiesByIIRID", ctx, tx, iirID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteStudentActivitiesByIIRID indicates an expected call of DeleteStudentActivitiesByIIRID.
func (mr *MockRepositoryInterfaceMockRecorder) DeleteStudentActivitiesByIIRID(ctx, tx, iirID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteStudentActivitiesByIIRID", reflect.TypeOf((*MockRepositoryInterface)(nil).DeleteStudentActivitiesByIIRID), ctx, tx, iirID)
}

// DeleteStudentFinancialSupportsByFinanceID mocks base method.
func (m *MockRepositoryInterface) DeleteStudentFinancialSupportsByFinanceID(ctx context.Context, tx datastore.DB, financeID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteStudentFinancialSupportsByFinanceID", ctx, tx, financeID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteStudentFinancialSupportsByFinanceID indicates an expected call of DeleteStudentFinancialSupportsByFinanceID.
func (mr *MockRepositoryInterfaceMockRecorder) DeleteStudentFinancialSupportsByFinanceID(ctx, tx, financeID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteStudentFinancialSupportsByFinanceID", reflect.TypeOf((*MockRepositoryInterface)(nil).DeleteStudentFinancialSupportsByFinanceID), ctx, tx, financeID)
}

// DeleteStudentHobbiesByIIRID mocks base method.
func (m *MockRepositoryInterface) DeleteStudentHobbiesByIIRID(ctx context.Context, tx datastore.DB, iirID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteStudentHobbiesByIIRID", ctx, tx, iirID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteStudentHobbiesByIIRID indicates an expected call of DeleteStudentHobbiesByIIRID.
func (mr *MockRepositoryInterfaceMockRecorder) DeleteStudentHobbiesByIIRID(ctx, tx, iirID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteStudentHobbiesByIIRID", reflect.TypeOf((*MockRepositoryInterface)(nil).DeleteStudentHobbiesByIIRID), ctx, tx, iirID)
}

// DeleteStudentRelatedPersons mocks base method.
func (m *MockRepositoryInterface) DeleteStudentRelatedPersons(ctx context.Context, tx datastore.DB, iirID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteStudentRelatedPersons", ctx, tx, iirID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteStudentRelatedPersons indicates an expected call of DeleteStudentRelatedPersons.
func (mr *MockRepositoryInterfaceMockRecorder) DeleteStudentRelatedPersons(ctx, tx, iirID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteStudentRelatedPersons", reflect.TypeOf((*MockRepositoryInterface)(nil).DeleteStudentRelatedPersons), ctx, tx, iirID)
}

// DeleteStudentSelectedReasons mocks base method.
func (m *MockRepositoryInterface) DeleteStudentSelectedReasons(ctx context.Context, tx datastore.DB, iirID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteStudentSelectedReasons", ctx, tx, iirID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteStudentSelectedReasons indicates an expected call of DeleteStudentSelectedReasons.
func (mr *MockRepositoryInterfaceMockRecorder) DeleteStudentSelectedReasons(ctx, tx, iirID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteStudentSelectedReasons", reflect.TypeOf((*MockRepositoryInterface)(nil).DeleteStudentSelectedReasons), ctx, tx, iirID)
}

// DeleteStudentSiblingSupportsByFamilyID mocks base method.
func (m *MockRepositoryInterface) DeleteStudentSiblingSupportsByFamilyID(ctx context.Context, tx datastore.DB, familyBackgroundID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteStudentSiblingSupportsByFamilyID", ctx, tx, familyBackgroundID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteStudentSiblingSupportsByFamilyID indicates an expected call of DeleteStudentSiblingSupportsByFamilyID.
func (mr *MockRepositoryInterfaceMockRecorder) DeleteStudentSiblingSupportsByFamilyID(ctx, tx, familyBackgroundID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteStudentSiblingSupportsByFamilyID", reflect.TypeOf((*MockRepositoryInterface)(nil).DeleteStudentSiblingSupportsByFamilyID), ctx, tx, familyBackgroundID)
}

// DeleteStudentSubjectPreferencesByIIRID mocks base method.
func (m *MockRepositoryInterface) DeleteStudentSubjectPreferencesByIIRID(ctx context.Context, tx datastore.DB, iirID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteStudentSubjectPreferencesByIIRID", ctx, tx, iirID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteStudentSubjectPreferencesByIIRID indicates an expected call of DeleteStudentSubjectPreferencesByIIRID.
func (mr *MockRepositoryInterfaceMockRecorder) DeleteStudentSubjectPreferencesByIIRID(ctx, tx, iirID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteStudentSubjectPreferencesByIIRID", reflect.TypeOf((*MockRepositoryInterface)(nil).DeleteStudentSubjectPreferencesByIIRID), ctx, tx, iirID)
}

// DeleteTestResultsByIIRID mocks base method.
func (m *MockRepositoryInterface) DeleteTestResultsByIIRID(ctx context.Context, tx datastore.DB, iirID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTestResultsByIIRID", ctx, tx, iirID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteTestResultsByIIRID indicates an expected call of DeleteTestResultsByIIRID.
func (mr *MockRepositoryInterfaceMockRecorder) DeleteTestResultsByIIRID(ctx, tx, iirID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTestResultsByIIRID", reflect.TypeOf((*MockRepositoryInterface)(nil).DeleteTestResultsByIIRID), ctx, tx, iirID)
}

// GetActivityOptionByID mocks base method.
func (m *MockRepositoryInterface) GetActivityOptionByID(ctx context.Context, optionID int) (*ActivityOption, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActivityOptionByID", ctx, optionID)
	ret0, _ := ret[0].(*ActivityOption)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActivityOptionByID indicates an expected call of GetActivityOptionByID.
func (mr *MockRepositoryInterfaceMockRecorder) GetActivityOptionByID(ctx, optionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActivityOptionByID", reflect.TypeOf((*MockRepositoryInterface)(nil).GetActivityOptionByID), ctx, optionID)
}

// GetActivityOptions mocks base method.
func (m *MockRepositoryInterface) GetActivityOptions(ctx context.Context) ([]ActivityOption, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActivityOptions", ctx)
	ret0, _ := ret[0].([]ActivityOption)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActivityOptions indicates an expected call of GetActivityOptions.
func (mr *MockRepositoryInterfaceMockRecorder) GetActivityOptions(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActivityOptions", reflect.TypeOf((*MockRepositoryInterface)(nil).GetActivityOptions), ctx)
}

// GetCivilStatusByID mocks base method.
func (m *MockRepositoryInterface) GetCivilStatusByID(ctx context.Context, statusID int) (*CivilStatusType, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCivilStatusByID", ctx, statusID)
	ret0, _ := ret[0].(*CivilStatusType)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCivilStatusByID indicates an expected call of GetCivilStatusByID.
func (mr *MockRepositoryInterfaceMockRecorder) GetCivilStatusByID(ctx, statusID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCivilStatusByID", reflect.TypeOf((*MockRepositoryInterface)(nil).GetCivilStatusByID), ctx, statusID)
}

// GetCivilStatusTypes mocks base method.
func (m *MockRepositoryInterface) GetCivilStatusTypes(ctx context.Context) ([]CivilStatusType, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCivilStatusTypes", ctx)
	ret0, _ := ret[0].([]CivilStatusType)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCivilStatusTypes indicates an expected call of GetCivilStatusTypes.
func (mr *MockRepositoryInterfaceMockRecorder) GetCivilStatusTypes(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCivilStatusTypes", reflect.TypeOf((*MockRepositoryInterface)(nil).GetCivilStatusTypes), ctx)
}

// GetCourseByID mocks base method.
func (m *MockRepositoryInterface) GetCourseByID(ctx context.Context, courseID int) (*Course, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCourseByID", ctx, courseID)
	ret0, _ := ret[0].(*Course)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCourseByID indicates an expected call of GetCourseByID.
func (mr *MockRepositoryInterfaceMockRecorder) GetCourseByID(ctx, courseID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCourseByID", reflect.TypeOf((*MockRepositoryInterface)(nil).GetCourseByID), ctx, courseID)
}

// GetCourses mocks base method.
func (m *MockRepositoryInterface) GetCourses(ctx context.Context) ([]Course, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCourses", ctx)
	ret0, _ := ret[0].([]Course)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCourses indicates an expected call of GetCourses.
func (mr *MockRepositoryInterfaceMockRecorder) GetCourses(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCourses", reflect.TypeOf((*MockRepositoryInterface)(nil).GetCourses), ctx)
}

// GetDB mocks base method.
func (m *MockRepositoryInterface) GetDB() *sqlx.DB {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDB")
	ret0, _ := ret[0].(*sqlx.DB)
	return ret0
}

// GetDB indicates an expected call of GetDB.
func (mr *MockRepositoryInterfaceMockRecorder) GetDB() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDB", reflect.TypeOf((*MockRepositoryInterface)(nil).GetDB))
}

// GetEducationalLevelByID mocks base method.
func (m *MockRepositoryInterface) GetEducationalLevelByID(ctx context.Context, levelID int) (*EducationalLevel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEducationalLevelByID", ctx, levelID)
	ret0, _ := ret[0].(*EducationalLevel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEducationalLevelByID indicates an expected call of GetEducationalLevelByID.
func (mr *MockRepositoryInterfaceMockRecorder) GetEducationalLevelByID(ctx, levelID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEducationalLevelByID", reflect.TypeOf((*MockRepositoryInterface)(nil).GetEducationalLevelByID), ctx, levelID)
}

// GetEducationalLevels mocks base method.
func (m *MockRepositoryInterface) GetEducationalLevels(ctx context.Context) ([]EducationalLevel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEducationalLevels", ctx)
	ret0, _ := ret[0].([]EducationalLevel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEducationalLevels indicates an expected call of GetEducationalLevels.
func (mr *MockRepositoryInterfaceMockRecorder) GetEducationalLevels(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEducationalLevels", reflect.TypeOf((*MockRepositoryInterface)(nil).GetEducationalLevels), ctx)
}

// GetEmergencyContactByIIRID mocks base method.
func (m *MockRepositoryInterface) GetEmergencyContactByIIRID(ctx context.Context, iirID string) (*EmergencyContact, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEmergencyContactByIIRID", ctx, iirID)
	ret0, _ := ret[0].(*EmergencyContact)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEmergencyContactByIIRID indicates an expected call of GetEmergencyContactByIIRID.
func (mr *MockRepositoryInterfaceMockRecorder) GetEmergencyContactByIIRID(ctx, iirID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEmergencyContactByIIRID", reflect.TypeOf((*MockRepositoryInterface)(nil).GetEmergencyContactByIIRID), ctx, iirID)
}

// GetEnrollmentReasonByID mocks base method.
func (m *MockRepositoryInterface) GetEnrollmentReasonByID(ctx context.Context, reasonID int) (*EnrollmentReason, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEnrollmentReasonByID", ctx, reasonID)
	ret0, _ := ret[0].(*EnrollmentReason)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEnrollmentReasonByID indicates an expected call of GetEnrollmentReasonByID.
func (mr *MockRepositoryInterfaceMockRecorder) GetEnrollmentReasonByID(ctx, reasonID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEnrollmentReasonByID", reflect.TypeOf((*MockRepositoryInterface)(nil).GetEnrollmentReasonByID), ctx, reasonID)
}

// GetEnrollmentReasons mocks base method.
func (m *MockRepositoryInterface) GetEnrollmentReasons(ctx context.Context) ([]EnrollmentReason, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEnrollmentReasons", ctx)
	ret0, _ := ret[0].([]EnrollmentReason)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEnrollmentReasons indicates an expected call of GetEnrollmentReasons.
func (mr *MockRepositoryInterfaceMockRecorder) GetEnrollmentReasons(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEnrollmentReasons", reflect.TypeOf((*MockRepositoryInterface)(nil).GetEnrollmentReasons), ctx)
}

// GetFinancialSupportTypeByFinanceID mocks base method.
func (m *MockRepositoryInterface) GetFinancialSupportTypeByFinanceID(ctx context.Context, financeID int) ([]StudentFinancialSupport, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFinancialSupportTypeByFinanceID", ctx, financeID)
	ret0, _ := ret[0].([]StudentFinancialSupport)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFinancialSupportTypeByFinanceID indicates an expected call of GetFinancialSupportTypeByFinanceID.
func (mr *MockRepositoryInterfaceMockRecorder) GetFinancialSupportTypeByFinanceID(ctx, financeID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFinancialSupportTypeByFinanceID", reflect.TypeOf((*MockRepositoryInterface)(nil).GetFinancialSupportTypeByFinanceID), ctx, financeID)
}

// GetGenderByID mocks base method.
func (m *MockRepositoryInterface) GetGenderByID(ctx context.Context, genderID int) (*Gender, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGenderByID", ctx, genderID)
	ret0, _ := ret[0].(*Gender)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGenderByID indicates an expected call of GetGenderByID.
func (mr *MockRepositoryInterfaceMockRecorder) GetGenderByID(ctx, genderID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGenderByID", reflect.TypeOf((*MockRepositoryInterface)(nil).GetGenderByID), ctx, genderID)
}

// GetGenders mocks base method.
func (m *MockRepositoryInterface) GetGenders(ctx context.Context) ([]Gender, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGenders", ctx)
	ret0, _ := ret[0].([]Gender)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGenders indicates an expected call of GetGenders.
func (mr *MockRepositoryInterfaceMockRecorder) GetGenders(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGenders", reflect.TypeOf((*MockRepositoryInterface)(nil).GetGenders), ctx)
}

// GetIIRDraftByUserID mocks base method.
func (m *MockRepositoryInterface) GetIIRDraftByUserID(ctx context.Context, userID string) (*IIRDraft, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIIRDraftByUserID", ctx, userID)
	ret0, _ := ret[0].(*IIRDraft)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetIIRDraftByUserID indicates an expected call of GetIIRDraftByUserID.
func (mr *MockRepositoryInterfaceMockRecorder) GetIIRDraftByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIIRDraftByUserID", reflect.TypeOf((*MockRepositoryInterface)(nil).GetIIRDraftByUserID), ctx, userID)
}

// GetIncomeRangeByID mocks base method.
func (m *MockRepositoryInterface) GetIncomeRangeByID(ctx context.Context, rangeID int) (*IncomeRange, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIncomeRangeByID", ctx, rangeID)
	ret0, _ := ret[0].(*IncomeRange)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetIncomeRangeByID indicates an expected call of GetIncomeRangeByID.
func (mr *MockRepositoryInterfaceMockRecorder) GetIncomeRangeByID(ctx, rangeID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIncomeRangeByID", reflect.TypeOf((*MockRepositoryInterface)(nil).GetIncomeRangeByID), ctx, rangeID)
}

// GetIncomeRanges mocks base method.
func (m *MockRepositoryInterface) GetIncomeRanges(ctx context.Context) ([]IncomeRange, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIncomeRanges", ctx)
	ret0, _ := ret[0].([]IncomeRange)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetIncomeRanges indicates an expected call of GetIncomeRanges.
func (mr *MockRepositoryInterfaceMockRecorder) GetIncomeRanges(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIncomeRanges", reflect.TypeOf((*MockRepositoryInterface)(nil).GetIncomeRanges), ctx)
}

// GetNatureOfResidenceByID mocks base method.
func (m *MockRepositoryInterface) GetNatureOfResidenceByID(ctx context.Context, residenceID int) (*NatureOfResidenceType, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNatureOfResidenceByID", ctx, residenceID)
	ret0, _ := ret[0].(*NatureOfResidenceType)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNatureOfResidenceByID indicates an expected call of GetNatureOfResidenceByID.
func (mr *MockRepositoryInterfaceMockRecorder) GetNatureOfResidenceByID(ctx, residenceID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNatureOfResidenceByID", reflect.TypeOf((*MockRepositoryInterface)(nil).GetNatureOfResidenceByID), ctx, residenceID)
}

// GetNatureOfResidenceTypes mocks base method.
func (m *MockRepositoryInterface) GetNatureOfResidenceTypes(ctx context.Context) ([]NatureOfResidenceType, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNatureOfResidenceTypes", ctx)
	ret0, _ := ret[0].([]NatureOfResidenceType)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNatureOfResidenceTypes indicates an expected call of GetNatureOfResidenceTypes.
func (mr *MockRepositoryInterfaceMockRecorder) GetNatureOfResidenceTypes(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNatureOfResidenceTypes", reflect.TypeOf((*MockRepositoryInterface)(nil).GetNatureOfResidenceTypes), ctx)
}

// GetParentalStatusByID mocks base method.
func (m *MockRepositoryInterface) GetParentalStatusByID(ctx context.Context, statusID int) (*ParentalStatusType, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetParentalStatusByID", ctx, statusID)
	ret0, _ := ret[0].(*ParentalStatusType)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetParentalStatusByID indicates an expected call of GetParentalStatusByID.
func (mr *MockRepositoryInterfaceMockRecorder) GetParentalStatusByID(ctx, statusID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetParentalStatusByID", reflect.TypeOf((*MockRepositoryInterface)(nil).GetParentalStatusByID), ctx, statusID)
}

// GetParentalStatusTypes mocks base method.
func (m *MockRepositoryInterface) GetParentalStatusTypes(ctx context.Context) ([]ParentalStatusType, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetParentalStatusTypes", ctx)
	ret0, _ := ret[0].([]ParentalStatusType)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetParentalStatusTypes indicates an expected call of GetParentalStatusTypes.
func (mr *MockRepositoryInterfaceMockRecorder) GetParentalStatusTypes(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetParentalStatusTypes", reflect.TypeOf((*MockRepositoryInterface)(nil).GetParentalStatusTypes), ctx)
}

// GetRelatedPersonByID mocks base method.
func (m *MockRepositoryInterface) GetRelatedPersonByID(ctx context.Context, personID int) (*RelatedPerson, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRelatedPersonByID", ctx, personID)
	ret0, _ := ret[0].(*RelatedPerson)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRelatedPersonByID indicates an expected call of GetRelatedPersonByID.
func (mr *MockRepositoryInterfaceMockRecorder) GetRelatedPersonByID(ctx, personID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRelatedPersonByID", reflect.TypeOf((*MockRepositoryInterface)(nil).GetRelatedPersonByID), ctx, personID)
}

// GetReligionByID mocks base method.
func (m *MockRepositoryInterface) GetReligionByID(ctx context.Context, religionID int) (*Religion, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetReligionByID", ctx, religionID)
	ret0, _ := ret[0].(*Religion)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetReligionByID indicates an expected call of GetReligionByID.
func (mr *MockRepositoryInterfaceMockRecorder) GetReligionByID(ctx, religionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetReligionByID", reflect.TypeOf((*MockRepositoryInterface)(nil).GetReligionByID), ctx, religionID)
}

// GetReligions mocks base method.
func (m *MockRepositoryInterface) GetReligions(ctx context.Context) ([]Religion, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetReligions", ctx)
	ret0, _ := ret[0].([]Religion)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetReligions indicates an expected call of GetReligions.
func (mr *MockRepositoryInterfaceMockRecorder) GetReligions(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetReligions", reflect.TypeOf((*MockRepositoryInterface)(nil).GetReligions), ctx)
}

// GetSchoolDetailsByEBID mocks base method.
func (m *MockRepositoryInterface) GetSchoolDetailsByEBID(ctx context.Context, ebID int) ([]SchoolDetails, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSchoolDetailsByEBID", ctx, ebID)
	ret0, _ := ret[0].([]SchoolDetails)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSchoolDetailsByEBID indicates an expected call of GetSchoolDetailsByEBID.
func (mr *MockRepositoryInterfaceMockRecorder) GetSchoolDetailsByEBID(ctx, ebID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSchoolDetailsByEBID", reflect.TypeOf((*MockRepositoryInterface)(nil).GetSchoolDetailsByEBID), ctx, ebID)
}

// GetSiblingSupportTypeByID mocks base method.
func (m *MockRepositoryInterface) GetSiblingSupportTypeByID(ctx context.Context, supportID int) (*SibilingSupportType, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSiblingSupportTypeByID", ctx, supportID)
	ret0, _ := ret[0].(*SibilingSupportType)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSiblingSupportTypeByID indicates an expected call of GetSiblingSupportTypeByID.
func (mr *MockRepositoryInterfaceMockRecorder) GetSiblingSupportTypeByID(ctx, supportID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSiblingSupportTypeByID", reflect.TypeOf((*MockRepositoryInterface)(nil).GetSiblingSupportTypeByID), ctx, supportID)
}

// GetSiblingSupportTypes mocks base method.
func (m *MockRepositoryInterface) GetSiblingSupportTypes(ctx context.Context) ([]SibilingSupportType, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSiblingSupportTypes", ctx)
	ret0, _ := ret[0].([]SibilingSupportType)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSiblingSupportTypes indicates an expected call of GetSiblingSupportTypes.
func (mr *MockRepositoryInterfaceMockRecorder) GetSiblingSupportTypes(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSiblingSupportTypes", reflect.TypeOf((*MockRepositoryInterface)(nil).GetSiblingSupportTypes), ctx)
}

// GetStudentActivities mocks base method.
func (m *MockRepositoryInterface) GetStudentActivities(ctx context.Context, iirID string) ([]StudentActivity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStudentActivities", ctx, iirID)
	ret0, _ := ret[0].([]StudentActivity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStudentActivities indicates an expected call of GetStudentActivities.
func (mr *MockRepositoryInterfaceMockRecorder) GetStudentActivities(ctx, iirID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStudentActivities", reflect.TypeOf((*MockRepositoryInterface)(nil).GetStudentActivities), ctx, iirID)
}

// GetStudentAddresses mocks base method.
func (m *MockRepositoryInterface) GetStudentAddresses(ctx context.Context, iirID string) ([]StudentAddress, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStudentAddresses", ctx, iirID)
	ret0, _ := ret[0].([]StudentAddress)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStudentAddresses indicates an expected call of GetStudentAddresses.
func (mr *MockRepositoryInterfaceMockRecorder) GetStudentAddresses(ctx, iirID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStudentAddresses", reflect.TypeOf((*MockRepositoryInterface)(nil).GetStudentAddresses), ctx, iirID)
}

// GetStudentBasicInfo mocks base method.
func (m *MockRepositoryInterface) GetStudentBasicInfo(ctx context.Context, iirID string) (*StudentBasicInfoView, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStudentBasicInfo", ctx, iirID)
	ret0, _ := ret[0].(*StudentBasicInfoView)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStudentBasicInfo indicates an expected call of GetStudentBasicInfo.
func (mr *MockRepositoryInterfaceMockRecorder) GetStudentBasicInfo(ctx, iirID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStudentBasicInfo", reflect.TypeOf((*MockRepositoryInterface)(nil).GetStudentBasicInfo), ctx, iirID)
}

// GetStudentCORByUserID mocks base method.
func (m *MockRepositoryInterface) GetStudentCORByUserID(ctx context.Context, userID string) (StudentCOR, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStudentCORByUserID", ctx, userID)
	ret0, _ := ret[0].(StudentCOR)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStudentCORByUserID indicates an expected call of GetStudentCORByUserID.
func (mr *MockRepositoryInterfaceMockRecorder) GetStudentCORByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStudentCORByUserID", reflect.TypeOf((*MockRepositoryInterface)(nil).GetStudentCORByUserID), ctx, userID)
}

// GetStudentCORsByUserID mocks base method.
func (m *MockRepositoryInterface) GetStudentCORsByUserID(ctx context.Context, userID string) ([]StudentCOR, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStudentCORsByUserID", ctx, userID)
	ret0, _ := ret[0].([]StudentCOR)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStudentCORsByUserID indicates an expected call of GetStudentCORsByUserID.
func (mr *MockRepositoryInterfaceMockRecorder) GetStudentCORsByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStudentCORsByUserID", reflect.TypeOf((*MockRepositoryInterface)(nil).GetStudentCORsByUserID), ctx, userID)
}

// GetStudentConsultations mocks base method.
func (m *MockRepositoryInterface) GetStudentConsultations(ctx context.Context, iirID string) ([]StudentConsultation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStudentConsultations", ctx, iirID)
	ret0, _ := ret[0].([]StudentConsultation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStudentConsultations indicates an expected call of GetStudentConsultations.
func (mr *MockRepositoryInterfaceMockRecorder) GetStudentConsultations(ctx, iirID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStudentConsultations", reflect.TypeOf((*MockRepositoryInterface)(nil).GetStudentConsultations), ctx, iirID)
}

// GetStudentEducationalBackground mocks base method.
func (m *MockRepositoryInterface) GetStudentEducationalBackground(ctx context.Context, iirID string) (*EducationalBackground, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStudentEducationalBackground", ctx, iirID)
	ret0, _ := ret[0].(*EducationalBackground)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStudentEducationalBackground indicates an expected call of GetStudentEducationalBackground.
func (mr *MockRepositoryInterfaceMockRecorder) GetStudentEducationalBackground(ctx, iirID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStudentEducationalBackground", reflect.TypeOf((*MockRepositoryInterface)(nil).GetStudentEducationalBackground), ctx, iirID)
}

// GetStudentEnrollmentReasons mocks base method.
func (m *MockRepositoryInterface) GetStudentEnrollmentReasons(ctx context.Context, iirID string) ([]StudentSelectedReason, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStudentEnrollmentReasons", ctx, iirID)
	ret0, _ := ret[0].([]StudentSelectedReason)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStudentEnrollmentReasons indicates an expected call of GetStudentEnrollmentReasons.
func (mr *MockRepositoryInterfaceMockRecorder) GetStudentEnrollmentReasons(ctx, iirID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStudentEnrollmentReasons", reflect.TypeOf((*MockRepositoryInterface)(nil).GetStudentEnrollmentReasons), ctx, iirID)
}

// GetStudentFamilyBackground mocks base method.
func (m *MockRepositoryInterface) GetStudentFamilyBackground(ctx context.Context, iirID string) (*FamilyBackground, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStudentFamilyBackground", ctx, iirID)
	ret0, _ := ret[0].(*FamilyBackground)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStudentFamilyBackground indicates an expected call of GetStudentFamilyBackground.
func (mr *MockRepositoryInterfaceMockRecorder) GetStudentFamilyBackground(ctx, iirID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStudentFamilyBackground", reflect.TypeOf((*MockRepositoryInterface)(nil).GetStudentFamilyBackground), ctx, iirID)
}

// GetStudentFinancialInfo mocks base method.
func (m *MockRepositoryInterface) GetStudentFinancialInfo(ctx context.Context, iirID string) (*StudentFinance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStudentFinancialInfo", ctx, iirID)
	ret0, _ := ret[0].(*StudentFinance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStudentFinancialInfo indicates an expected call of GetStudentFinancialInfo.
func (mr *MockRepositoryInterfaceMockRecorder) GetStudentFinancialInfo(ctx, iirID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStudentFinancialInfo", reflect.TypeOf((*MockRepositoryInterface)(nil).GetStudentFinancialInfo), ctx, iirID)
}

// GetStudentHealthRecord mocks base method.
func (m *MockRepositoryInterface) GetStudentHealthRecord(ctx context.Context, iirID string) (*StudentHealthRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStudentHealthRecord", ctx, iirID)
	ret0, _ := ret[0].(*StudentHealthRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStudentHealthRecord indicates an expected call of GetStudentHealthRecord.
func (mr *MockRepositoryInterfaceMockRecorder) GetStudentHealthRecord(ctx, iirID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStudentHealthRecord", reflect.TypeOf((*MockRepositoryInterface)(nil).GetStudentHealthRecord), ctx, iirID)
}

// GetStudentHobbies mocks base method.
func (m *MockRepositoryInterface) GetStudentHobbies(ctx context.Context, iirID string) ([]StudentHobby, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStudentHobbies", ctx, iirID)
	ret0, _ := ret[0].([]StudentHobby)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStudentHobbies indicates an expected call of GetStudentHobbies.
func (mr *MockRepositoryInterfaceMockRecorder) GetStudentHobbies(ctx, iirID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStudentHobbies", reflect.TypeOf((*MockRepositoryInterface)(nil).GetStudentHobbies), ctx, iirID)
}

// GetStudentIIR mocks base method.
func (m *MockRepositoryInterface) GetStudentIIR(ctx context.Context, iirID string) (*IIRRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStudentIIR", ctx, iirID)
	ret0, _ := ret[0].(*IIRRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStudentIIR indicates an expected call of GetStudentIIR.
func (mr *MockRepositoryInterfaceMockRecorder) GetStudentIIR(ctx, iirID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStudentIIR", reflect.TypeOf((*MockRepositoryInterface)(nil).GetStudentIIR), ctx, iirID)
}

// GetStudentIIRByUserID mocks base method.
func (m *MockRepositoryInterface) GetStudentIIRByUserID(ctx context.Context, userID string) (*IIRRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStudentIIRByUserID", ctx, userID)
	ret0, _ := ret[0].(*IIRRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStudentIIRByUserID indicates an expected call of GetStudentIIRByUserID.
func (mr *MockRepositoryInterfaceMockRecorder) GetStudentIIRByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStudentIIRByUserID", reflect.TypeOf((*MockRepositoryInterface)(nil).GetStudentIIRByUserID), ctx, userID)
}

// GetStudentPersonalInfo mocks base method.
func (m *MockRepositoryInterface) GetStudentPersonalInfo(ctx context.Context, iirID string) (*StudentPersonalInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStudentPersonalInfo", ctx, iirID)
	ret0, _ := ret[0].(*StudentPersonalInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStudentPersonalInfo indicates an expected call of GetStudentPersonalInfo.
func (mr *MockRepositoryInterfaceMockRecorder) GetStudentPersonalInfo(ctx, iirID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStudentPersonalInfo", reflect.TypeOf((*MockRepositoryInterface)(nil).GetStudentPersonalInfo), ctx, iirID)
}

// GetStudentRelatedPersons mocks base method.
func (m *MockRepositoryInterface) GetStudentRelatedPersons(ctx context.Context, iirID string) ([]StudentRelatedPerson, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStudentRelatedPersons", ctx, iirID)
	ret0, _ := ret[0].([]StudentRelatedPerson)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStudentRelatedPersons indicates an expected call of GetStudentRelatedPersons.
func (mr *MockRepositoryInterfaceMockRecorder) GetStudentRelatedPersons(ctx, iirID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStudentRelatedPersons", reflect.TypeOf((*MockRepositoryInterface)(nil).GetStudentRelatedPersons), ctx, iirID)
}

// GetStudentRelationshipByID mocks base method.
func (m *MockRepositoryInterface) GetStudentRelationshipByID(ctx context.Context, relationshipID int) (*StudentRelationshipType, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStudentRelationshipByID", ctx, relationshipID)
	ret0, _ := ret[0].(*StudentRelationshipType)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStudentRelationshipByID indicates an expected call of GetStudentRelationshipByID.
func (mr *MockRepositoryInterfaceMockRecorder) GetStudentRelationshipByID(ctx, relationshipID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStudentRelationshipByID", reflect.TypeOf((*MockRepositoryInterface)(nil).GetStudentRelationshipByID), ctx, relationshipID)
}

// GetStudentRelationshipTypes mocks base method.
func (m *MockRepositoryInterface) GetStudentRelationshipTypes(ctx context.Context) ([]StudentRelationshipType, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStudentRelationshipTypes", ctx)
	ret0, _ := ret[0].([]StudentRelationshipType)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStudentRelationshipTypes indicates an expected call of GetStudentRelationshipTypes.
func (mr *MockRepositoryInterfaceMockRecorder) GetStudentRelationshipTypes(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStudentRelationshipTypes", reflect.TypeOf((*MockRepositoryInterface)(nil).GetStudentRelationshipTypes), ctx)
}

// GetStudentSiblingSupport mocks base method.
func (m *MockRepositoryInterface) GetStudentSiblingSupport(ctx context.Context, fbID int) ([]StudentSiblingSupport, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStudentSiblingSupport", ctx, fbID)
	ret0, _ := ret[0].([]StudentSiblingSupport)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStudentSiblingSupport indicates an expected call of GetStudentSiblingSupport.
func (mr *MockRepositoryInterfaceMockRecorder) GetStudentSiblingSupport(ctx, fbID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStudentSiblingSupport", reflect.TypeOf((*MockRepositoryInterface)(nil).GetStudentSiblingSupport), ctx, fbID)
}

// GetStudentStatuses mocks base method.
func (m *MockRepositoryInterface) GetStudentStatuses(ctx context.Context) ([]StudentStatus, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStudentStatuses", ctx)
	ret0, _ := ret[0].([]StudentStatus)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStudentStatuses indicates an expected call of GetStudentStatuses.
func (mr *MockRepositoryInterfaceMockRecorder) GetStudentStatuses(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStudentStatuses", reflect.TypeOf((*MockRepositoryInterface)(nil).GetStudentStatuses), ctx)
}

// GetStudentSubjectPreferences mocks base method.
func (m *MockRepositoryInterface) GetStudentSubjectPreferences(ctx context.Context, iirID string) ([]StudentSubjectPreference, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStudentSubjectPreferences", ctx, iirID)
	ret0, _ := ret[0].([]StudentSubjectPreference)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStudentSubjectPreferences indicates an expected call of GetStudentSubjectPreferences.
func (mr *MockRepositoryInterfaceMockRecorder) GetStudentSubjectPreferences(ctx, iirID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStudentSubjectPreferences", reflect.TypeOf((*MockRepositoryInterface)(nil).GetStudentSubjectPreferences), ctx, iirID)
}

// GetStudentSupportByID mocks base method.
func (m *MockRepositoryInterface) GetStudentSupportByID(ctx context.Context, supportID int) (*StudentSupportType, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStudentSupportByID", ctx, supportID)
	ret0, _ := ret[0].(*StudentSupportType)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStudentSupportByID indicates an expected call of GetStudentSupportByID.
func (mr *MockRepositoryInterfaceMockRecorder) GetStudentSupportByID(ctx, supportID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStudentSupportByID", reflect.TypeOf((*MockRepositoryInterface)(nil).GetStudentSupportByID), ctx, supportID)
}

// GetStudentSupportTypes mocks base method.
func (m *MockRepositoryInterface) GetStudentSupportTypes(ctx context.Context) ([]StudentSupportType, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStudentSupportTypes", ctx)
	ret0, _ := ret[0].([]StudentSupportType)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStudentSupportTypes indicates an expected call of GetStudentSupportTypes.
func (mr *MockRepositoryInterfaceMockRecorder) GetStudentSupportTypes(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStudentSupportTypes", reflect.TypeOf((*MockRepositoryInterface)(nil).GetStudentSupportTypes), ctx)
}

// GetStudentTestResults mocks base method.
func (m *MockRepositoryInterface) GetStudentTestResults(ctx context.Context, iirID string) ([]TestResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStudentTestResults", ctx, iirID)
	ret0, _ := ret[0].([]TestResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStudentTestResults indicates an expected call of GetStudentTestResults.
func (mr *MockRepositoryInterfaceMockRecorder) GetStudentTestResults(ctx, iirID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStudentTestResults", reflect.TypeOf((*MockRepositoryInterface)(nil).GetStudentTestResults), ctx, iirID)
}

// GetTotalStudentsCount mocks base method.
func (m *MockRepositoryInterface) GetTotalStudentsCount(ctx context.Context, search string, courseID, genderID, yearLevel, statusID int) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTotalStudentsCount", ctx, search, courseID, genderID, yearLevel, statusID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTotalStudentsCount indicates an expected call of GetTotalStudentsCount.
func (mr *MockRepositoryInterfaceMockRecorder) GetTotalStudentsCount(ctx, search, courseID, genderID, yearLevel, statusID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTotalStudentsCount", reflect.TypeOf((*MockRepositoryInterface)(nil).GetTotalStudentsCount), ctx, search, courseID, genderID, yearLevel, statusID)
}

// IsStudentLocked mocks base method.
func (m *MockRepositoryInterface) IsStudentLocked(ctx context.Context, iirID string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsStudentLocked", ctx, iirID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsStudentLocked indicates an expected call of IsStudentLocked.
func (mr *MockRepositoryInterfaceMockRecorder) IsStudentLocked(ctx, iirID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsStudentLocked", reflect.TypeOf((*MockRepositoryInterface)(nil).IsStudentLocked), ctx, iirID)
}

// ListStudents mocks base method.
func (m *MockRepositoryInterface) ListStudents(ctx context.Context, search string, offset, limit int, orderBy string, courseID, genderID, yearLevel, statusID int) ([]StudentProfileView, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListStudents", ctx, search, offset, limit, orderBy, courseID, genderID, yearLevel, statusID)
	ret0, _ := ret[0].([]StudentProfileView)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListStudents indicates an expected call of ListStudents.
func (mr *MockRepositoryInterfaceMockRecorder) ListStudents(ctx, search, offset, limit, orderBy, courseID, genderID, yearLevel, statusID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListStudents", reflect.TypeOf((*MockRepositoryInterface)(nil).ListStudents), ctx, search, offset, limit, orderBy, courseID, genderID, yearLevel, statusID)
}

// SaveStudentCOR mocks base method.
func (m *MockRepositoryInterface) SaveStudentCOR(ctx context.Context, tx datastore.DB, cor StudentCOR) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveStudentCOR", ctx, tx, cor)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveStudentCOR indicates an expected call of SaveStudentCOR.
func (mr *MockRepositoryInterfaceMockRecorder) SaveStudentCOR(ctx, tx, cor any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveStudentCOR", reflect.TypeOf((*MockRepositoryInterface)(nil).SaveStudentCOR), ctx, tx, cor)
}

// UpsertEducationalBackground mocks base method.
func (m *MockRepositoryInterface) UpsertEducationalBackground(ctx context.Context, tx datastore.DB, eb *EducationalBackground) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertEducationalBackground", ctx, tx, eb)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpsertEducationalBackground indicates an expected call of UpsertEducationalBackground.
func (mr *MockRepositoryInterfaceMockRecorder) UpsertEducationalBackground(ctx, tx, eb any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertEducationalBackground", reflect.TypeOf((*MockRepositoryInterface)(nil).UpsertEducationalBackground), ctx, tx, eb)
}

// UpsertEmergencyContact mocks base method.
func (m *MockRepositoryInterface) UpsertEmergencyContact(ctx context.Context, tx datastore.DB, ec *EmergencyContact) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertEmergencyContact", ctx, tx, ec)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpsertEmergencyContact indicates an expected call of UpsertEmergencyContact.
func (mr *MockRepositoryInterfaceMockRecorder) UpsertEmergencyContact(ctx, tx, ec any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertEmergencyContact", reflect.TypeOf((*MockRepositoryInterface)(nil).UpsertEmergencyContact), ctx, tx, ec)
}

// UpsertFamilyBackground mocks base method.
func (m *MockRepositoryInterface) UpsertFamilyBackground(ctx context.Context, tx datastore.DB, fb *FamilyBackground) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertFamilyBackground", ctx, tx, fb)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpsertFamilyBackground indicates an expected call of UpsertFamilyBackground.
func (mr *MockRepositoryInterfaceMockRecorder) UpsertFamilyBackground(ctx, tx, fb any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertFamilyBackground", reflect.TypeOf((*MockRepositoryInterface)(nil).UpsertFamilyBackground), ctx, tx, fb)
}

// UpsertIIRDraft mocks base method.
func (m *MockRepositoryInterface) UpsertIIRDraft(ctx context.Context, draft IIRDraft) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertIIRDraft", ctx, draft)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpsertIIRDraft indicates an expected call of UpsertIIRDraft.
func (mr *MockRepositoryInterfaceMockRecorder) UpsertIIRDraft(ctx, draft any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertIIRDraft", reflect.TypeOf((*MockRepositoryInterface)(nil).UpsertIIRDraft), ctx, draft)
}

// UpsertIIRRecord mocks base method.
func (m *MockRepositoryInterface) UpsertIIRRecord(ctx context.Context, tx datastore.DB, iir *IIRRecord) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertIIRRecord", ctx, tx, iir)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpsertIIRRecord indicates an expected call of UpsertIIRRecord.
func (mr *MockRepositoryInterfaceMockRecorder) UpsertIIRRecord(ctx, tx, iir any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertIIRRecord", reflect.TypeOf((*MockRepositoryInterface)(nil).UpsertIIRRecord), ctx, tx, iir)
}

// UpsertRelatedPerson mocks base method.
func (m *MockRepositoryInterface) UpsertRelatedPerson(ctx context.Context, tx datastore.DB, rp *RelatedPerson) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertRelatedPerson", ctx, tx, rp)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpsertRelatedPerson indicates an expected call of UpsertRelatedPerson.
func (mr *MockRepositoryInterfaceMockRecorder) UpsertRelatedPerson(ctx, tx, rp any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertRelatedPerson", reflect.TypeOf((*MockRepositoryInterface)(nil).UpsertRelatedPerson), ctx, tx, rp)
}

// UpsertSchoolDetails mocks base method.
func (m *MockRepositoryInterface) UpsertSchoolDetails(ctx context.Context, tx datastore.DB, sd *SchoolDetails) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertSchoolDetails", ctx, tx, sd)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpsertSchoolDetails indicates an expected call of UpsertSchoolDetails.
func (mr *MockRepositoryInterfaceMockRecorder) UpsertSchoolDetails(ctx, tx, sd any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertSchoolDetails", reflect.TypeOf((*MockRepositoryInterface)(nil).UpsertSchoolDetails), ctx, tx, sd)
}

// UpsertStudentAddress mocks base method.
func (m *MockRepositoryInterface) UpsertStudentAddress(ctx context.Context, tx datastore.DB, sa *StudentAddress) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertStudentAddress", ctx, tx, sa)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpsertStudentAddress indicates an expected call of UpsertStudentAddress.
func (mr *MockRepositoryInterfaceMockRecorder) UpsertStudentAddress(ctx, tx, sa any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertStudentAddress", reflect.TypeOf((*MockRepositoryInterface)(nil).UpsertStudentAddress), ctx, tx, sa)
}

// UpsertStudentConsultation mocks base method.
func (m *MockRepositoryInterface) UpsertStudentConsultation(ctx context.Context, tx datastore.DB, sc *StudentConsultation) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertStudentConsultation", ctx, tx, sc)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpsertStudentConsultation indicates an expected call of UpsertStudentConsultation.
func (mr *MockRepositoryInterfaceMockRecorder) UpsertStudentConsultation(ctx, tx, sc any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertStudentConsultation", reflect.TypeOf((*MockRepositoryInterface)(nil).UpsertStudentConsultation), ctx, tx, sc)
}

// UpsertStudentFinance mocks base method.
func (m *MockRepositoryInterface) UpsertStudentFinance(ctx context.Context, tx datastore.DB, sf *StudentFinance) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertStudentFinance", ctx, tx, sf)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpsertStudentFinance indicates an expected call of UpsertStudentFinance.
func (mr *MockRepositoryInterfaceMockRecorder) UpsertStudentFinance(ctx, tx, sf any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertStudentFinance", reflect.TypeOf((*MockRepositoryInterface)(nil).UpsertStudentFinance), ctx, tx, sf)
}

// UpsertStudentHealthRecord mocks base method.
func (m *MockRepositoryInterface) UpsertStudentHealthRecord(ctx context.Context, tx datastore.DB, hr *StudentHealthRecord) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertStudentHealthRecord", ctx, tx, hr)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpsertStudentHealthRecord indicates an expected call of UpsertStudentHealthRecord.
func (mr *MockRepositoryInterfaceMockRecorder) UpsertStudentHealthRecord(ctx, tx, hr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertStudentHealthRecord", reflect.TypeOf((*MockRepositoryInterface)(nil).UpsertStudentHealthRecord), ctx, tx, hr)
}

// UpsertStudentPersonalInfo mocks base method.
func (m *MockRepositoryInterface) UpsertStudentPersonalInfo(ctx context.Context, tx datastore.DB, info *StudentPersonalInfo) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertStudentPersonalInfo", ctx, tx, info)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertStudentPersonalInfo indicates an expected call of UpsertStudentPersonalInfo.
func (mr *MockRepositoryInterfaceMockRecorder) UpsertStudentPersonalInfo(ctx, tx, info any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertStudentPersonalInfo", reflect.TypeOf((*MockRepositoryInterface)(nil).UpsertStudentPersonalInfo), ctx, tx, info)
}

// UpsertStudentRelatedPerson mocks base method.
func (m *MockRepositoryInterface) UpsertStudentRelatedPerson(ctx context.Context, tx datastore.DB, srp *StudentRelatedPerson) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertStudentRelatedPerson", ctx, tx, srp)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertStudentRelatedPerson indicates an expected call of UpsertStudentRelatedPerson.
func (mr *MockRepositoryInterfaceMockRecorder) UpsertStudentRelatedPerson(ctx, tx, srp any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertStudentRelatedPerson", reflect.TypeOf((*MockRepositoryInterface)(nil).UpsertStudentRelatedPerson), ctx, tx, srp)
}

// WithTransaction mocks base method.
func (m *MockRepositoryInterface) WithTransaction(ctx context.Context, fn func(datastore.DB) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithTransaction", ctx, fn)
	ret0, _ := ret[0].(error)
	return ret0
}

// WithTransaction indicates an expected call of WithTransaction.
func (mr *MockRepositoryInterfaceMockRecorder) WithTransaction(ctx, fn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithTransaction", reflect.TypeOf((*MockRepositoryInterface)(nil).WithTransaction), ctx, fn)
}
