// Code generated by MockGen. DO NOT EDIT.
// Source: internal\features\m2mclients\interface.go
//
// Generated by this command:
//
//	mockgen -source=internal\features\m2mclients\interface.go -package=m2mclients -destination=internal\features\m2mclients\mock_interfaces.go
//

// Package m2mclients is a generated GoMock package.
package m2mclients

import (
	context "context"
	reflect "reflect"

	sqlx "github.com/jmoiron/sqlx"
	datastore "github.com/olazo-johnalbert/duckload-api/internal/infrastructure/datastore"
	gomock "go.uber.org/mock/gomock"
)

// MockServiceInterface is a mock of ServiceInterface interface.
type MockServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockServiceInterfaceMockRecorder
	isgomock struct{}
}

// MockServiceInterfaceMockRecorder is the mock recorder for MockServiceInterface.
type MockServiceInterfaceMockRecorder struct {
	mock *MockServiceInterface
}

// NewMockServiceInterface creates a new mock instance.
func NewMockServiceInterface(ctrl *gomock.Controller) *MockServiceInterface {
	mock := &MockServiceInterface{ctrl: ctrl}
	mock.recorder = &MockServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockServiceInterface) EXPECT() *MockServiceInterfaceMockRecorder {
	return m.recorder
}

// Authenticate mocks base method.
func (m *MockServiceInterface) Authenticate(ctx context.Context, clientID, clientSecret string) (*M2MClient, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Authenticate", ctx, clientID, clientSecret)
	ret0, _ := ret[0].(*M2MClient)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Authenticate indicates an expected call of Authenticate.
func (mr *MockServiceInterfaceMockRecorder) Authenticate(ctx, clientID, clientSecret any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Authenticate", reflect.TypeOf((*MockServiceInterface)(nil).Authenticate), ctx, clientID, clientSecret)
}

// CreateClient mocks base method.
func (m *MockServiceInterface) CreateClient(ctx context.Context, userID string, req CreateM2MClientRequest) (*CreateM2MClientResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateClient", ctx, userID, req)
	ret0, _ := ret[0].(*CreateM2MClientResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateClient indicates an expected call of CreateClient.
func (mr *MockServiceInterfaceMockRecorder) CreateClient(ctx, userID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateClient", reflect.TypeOf((*MockServiceInterface)(nil).CreateClient), ctx, userID, req)
}

// IssueToken mocks base method.
func (m *MockServiceInterface) IssueToken(ctx context.Context, client *M2MClient) (*M2MTokenResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IssueToken", ctx, client)
	ret0, _ := ret[0].(*M2MTokenResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IssueToken indicates an expected call of IssueToken.
func (mr *MockServiceInterfaceMockRecorder) IssueToken(ctx, client any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IssueToken", reflect.TypeOf((*MockServiceInterface)(nil).IssueToken), ctx, client)
}

// ListClients mocks base method.
func (m *MockServiceInterface) ListClients(ctx context.Context, userID string, includeRevoked bool, roleID int) ([]M2MClientDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListClients", ctx, userID, includeRevoked, roleID)
	ret0, _ := ret[0].([]M2MClientDTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListClients indicates an expected call of ListClients.
func (mr *MockServiceInterfaceMockRecorder) ListClients(ctx, userID, includeRevoked, roleID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListClients", reflect.TypeOf((*MockServiceInterface)(nil).ListClients), ctx, userID, includeRevoked, roleID)
}

// RefreshToken mocks base method.
func (m *MockServiceInterface) RefreshToken(ctx context.Context, refreshToken string) (*M2MTokenResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RefreshToken", ctx, refreshToken)
	ret0, _ := ret[0].(*M2MTokenResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RefreshToken indicates an expected call of RefreshToken.
func (mr *MockServiceInterfaceMockRecorder) RefreshToken(ctx, refreshToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RefreshToken", reflect.TypeOf((*MockServiceInterface)(nil).RefreshToken), ctx, refreshToken)
}

// RegenerateSecret mocks base method.
func (m *MockServiceInterface) RegenerateSecret(ctx context.Context, id int) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RegenerateSecret", ctx, id)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RegenerateSecret indicates an expected call of RegenerateSecret.
func (mr *MockServiceInterfaceMockRecorder) RegenerateSecret(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegenerateSecret", reflect.TypeOf((*MockServiceInterface)(nil).RegenerateSecret), ctx, id)
}

// RevokeClient mocks base method.
func (m *MockServiceInterface) RevokeClient(ctx context.Context, id int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeClient", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// RevokeClient indicates an expected call of RevokeClient.
func (mr *MockServiceInterfaceMockRecorder) RevokeClient(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeClient", reflect.TypeOf((*MockServiceInterface)(nil).RevokeClient), ctx, id)
}

// VerifyClient mocks base method.
func (m *MockServiceInterface) VerifyClient(ctx context.Context, id int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyClient", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// VerifyClient indicates an expected call of VerifyClient.
func (mr *MockServiceInterfaceMockRecorder) VerifyClient(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyClient", reflect.TypeOf((*MockServiceInterface)(nil).VerifyClient), ctx, id)
}

// WithTransaction mocks base method.
func (m *MockServiceInterface) WithTransaction(ctx context.Context, fn func(datastore.DB) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithTransaction", ctx, fn)
	ret0, _ := ret[0].(error)
	return ret0
}

// WithTransaction indicates an expected call of WithTransaction.
func (mr *MockServiceInterfaceMockRecorder) WithTransaction(ctx, fn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithTransaction", reflect.TypeOf((*MockServiceInterface)(nil).WithTransaction), ctx, fn)
}

// MockRepositoryInterface is a mock of RepositoryInterface interface.
type MockRepositoryInterface struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryInterfaceMockRecorder
	isgomock struct{}
}

// MockRepositoryInterfaceMockRecorder is the mock recorder for MockRepositoryInterface.
type MockRepositoryInterfaceMockRecorder struct {
	mock *MockRepositoryInterface
}

// NewMockRepositoryInterface creates a new mock instance.
func NewMockRepositoryInterface(ctrl *gomock.Controller) *MockRepositoryInterface {
	mock := &MockRepositoryInterface{ctrl: ctrl}
	mock.recorder = &MockRepositoryInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepositoryInterface) EXPECT() *MockRepositoryInterfaceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockRepositoryInterface) Create(ctx context.Context, tx datastore.DB, client M2MClient) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, tx, client)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockRepositoryInterfaceMockRecorder) Create(ctx, tx, client any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRepositoryInterface)(nil).Create), ctx, tx, client)
}

// GetActiveByUserID mocks base method.
func (m *MockRepositoryInterface) GetActiveByUserID(ctx context.Context, userID string) (*M2MClient, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActiveByUserID", ctx, userID)
	ret0, _ := ret[0].(*M2MClient)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActiveByUserID indicates an expected call of GetActiveByUserID.
func (mr *MockRepositoryInterfaceMockRecorder) GetActiveByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActiveByUserID", reflect.TypeOf((*MockRepositoryInterface)(nil).GetActiveByUserID), ctx, userID)
}

// GetByClientID mocks base method.
func (m *MockRepositoryInterface) GetByClientID(ctx context.Context, clientID string) (*M2MClient, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByClientID", ctx, clientID)
	ret0, _ := ret[0].(*M2MClient)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByClientID indicates an expected call of GetByClientID.
func (mr *MockRepositoryInterfaceMockRecorder) GetByClientID(ctx, clientID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByClientID", reflect.TypeOf((*MockRepositoryInterface)(nil).GetByClientID), ctx, clientID)
}

// GetByID mocks base method.
func (m *MockRepositoryInterface) GetByID(ctx context.Context, tx datastore.DB, id int) (*M2MClient, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, tx, id)
	ret0, _ := ret[0].(*M2MClient)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockRepositoryInterfaceMockRecorder) GetByID(ctx, tx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockRepositoryInterface)(nil).GetByID), ctx, tx, id)
}

// GetDB mocks base method.
func (m *MockRepositoryInterface) GetDB() *sqlx.DB {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDB")
	ret0, _ := ret[0].(*sqlx.DB)
	return ret0
}

// GetDB indicates an expected call of GetDB.
func (mr *MockRepositoryInterfaceMockRecorder) GetDB() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDB", reflect.TypeOf((*MockRepositoryInterface)(nil).GetDB))
}

// List mocks base method.
func (m *MockRepositoryInterface) List(ctx context.Context, userID string, includeRevoked bool) ([]M2MClient, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, userID, includeRevoked)
	ret0, _ := ret[0].([]M2MClient)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockRepositoryInterfaceMockRecorder) List(ctx, userID, includeRevoked any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockRepositoryInterface)(nil).List), ctx, userID, includeRevoked)
}

// Revoke mocks base method.
func (m *MockRepositoryInterface) Revoke(ctx context.Context, tx datastore.DB, id int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Revoke", ctx, tx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Revoke indicates an expected call of Revoke.
func (mr *MockRepositoryInterfaceMockRecorder) Revoke(ctx, tx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Revoke", reflect.TypeOf((*MockRepositoryInterface)(nil).Revoke), ctx, tx, id)
}

// TouchLastUsed mocks base method.
func (m *MockRepositoryInterface) TouchLastUsed(ctx context.Context, tx datastore.DB, id int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TouchLastUsed", ctx, tx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// TouchLastUsed indicates an expected call of TouchLastUsed.
func (mr *MockRepositoryInterfaceMockRecorder) TouchLastUsed(ctx, tx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TouchLastUsed", reflect.TypeOf((*MockRepositoryInterface)(nil).TouchLastUsed), ctx, tx, id)
}

// UpdateSecret mocks base method.
func (m *MockRepositoryInterface) UpdateSecret(ctx context.Context, tx datastore.DB, id int, secretHash string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSecret", ctx, tx, id, secretHash)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateSecret indicates an expected call of UpdateSecret.
func (mr *MockRepositoryInterfaceMockRecorder) UpdateSecret(ctx, tx, id, secretHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSecret", reflect.TypeOf((*MockRepositoryInterface)(nil).UpdateSecret), ctx, tx, id, secretHash)
}

// UpdateVerificationStatus mocks base method.
func (m *MockRepositoryInterface) UpdateVerificationStatus(ctx context.Context, tx datastore.DB, id int, isVerified bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateVerificationStatus", ctx, tx, id, isVerified)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateVerificationStatus indicates an expected call of UpdateVerificationStatus.
func (mr *MockRepositoryInterfaceMockRecorder) UpdateVerificationStatus(ctx, tx, id, isVerified any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateVerificationStatus", reflect.TypeOf((*MockRepositoryInterface)(nil).UpdateVerificationStatus), ctx, tx, id, isVerified)
}

// WithTransaction mocks base method.
func (m *MockRepositoryInterface) WithTransaction(ctx context.Context, fn func(datastore.DB) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithTransaction", ctx, fn)
	ret0, _ := ret[0].(error)
	return ret0
}

// WithTransaction indicates an expected call of WithTransaction.
func (mr *MockRepositoryInterfaceMockRecorder) WithTransaction(ctx, fn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithTransaction", reflect.TypeOf((*MockRepositoryInterface)(nil).WithTransaction), ctx, fn)
}
