// Code generated by MockGen. DO NOT EDIT.
// Source: interface.go
//
// Generated by this command:
//
//	mockgen -source=interface.go -package=logs -destination=mock_interfaces.go
//

// Package logs is a generated GoMock package.
package logs

import (
	context "context"
	reflect "reflect"

	sqlx "github.com/jmoiron/sqlx"
	audit "github.com/olazo-johnalbert/duckload-api/internal/core/audit"
	structs "github.com/olazo-johnalbert/duckload-api/internal/core/structs"
	datastore "github.com/olazo-johnalbert/duckload-api/internal/infrastructure/datastore"
	gomock "go.uber.org/mock/gomock"
)

// MockServiceInterface is a mock of ServiceInterface interface.
type MockServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockServiceInterfaceMockRecorder
	isgomock struct{}
}

// MockServiceInterfaceMockRecorder is the mock recorder for MockServiceInterface.
type MockServiceInterfaceMockRecorder struct {
	mock *MockServiceInterface
}

// NewMockServiceInterface creates a new mock instance.
func NewMockServiceInterface(ctrl *gomock.Controller) *MockServiceInterface {
	mock := &MockServiceInterface{ctrl: ctrl}
	mock.recorder = &MockServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockServiceInterface) EXPECT() *MockServiceInterfaceMockRecorder {
	return m.recorder
}

// DeleteLogsOlderThan mocks base method.
func (m *MockServiceInterface) DeleteLogsOlderThan(ctx context.Context, days int) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteLogsOlderThan", ctx, days)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteLogsOlderThan indicates an expected call of DeleteLogsOlderThan.
func (mr *MockServiceInterfaceMockRecorder) DeleteLogsOlderThan(ctx, days any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteLogsOlderThan", reflect.TypeOf((*MockServiceInterface)(nil).DeleteLogsOlderThan), ctx, days)
}

// GetActivityStats mocks base method.
func (m *MockServiceInterface) GetActivityStats(ctx context.Context) ([]audit.LogActivityDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActivityStats", ctx)
	ret0, _ := ret[0].([]audit.LogActivityDTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActivityStats indicates an expected call of GetActivityStats.
func (mr *MockServiceInterfaceMockRecorder) GetActivityStats(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActivityStats", reflect.TypeOf((*MockServiceInterface)(nil).GetActivityStats), ctx)
}

// GetDB mocks base method.
func (m *MockServiceInterface) GetDB() datastore.DB {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDB")
	ret0, _ := ret[0].(datastore.DB)
	return ret0
}

// GetDB indicates an expected call of GetDB.
func (mr *MockServiceInterfaceMockRecorder) GetDB() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDB", reflect.TypeOf((*MockServiceInterface)(nil).GetDB))
}

// GetStats mocks base method.
func (m *MockServiceInterface) GetStats(ctx context.Context, startDate, endDate string) ([]audit.LogStatsDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStats", ctx, startDate, endDate)
	ret0, _ := ret[0].([]audit.LogStatsDTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStats indicates an expected call of GetStats.
func (mr *MockServiceInterfaceMockRecorder) GetStats(ctx, startDate, endDate any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStats", reflect.TypeOf((*MockServiceInterface)(nil).GetStats), ctx, startDate, endDate)
}

// ListLogs mocks base method.
func (m *MockServiceInterface) ListLogs(ctx context.Context, req audit.ListSystemLogsRequest) (*audit.ListSystemLogsDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListLogs", ctx, req)
	ret0, _ := ret[0].(*audit.ListSystemLogsDTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListLogs indicates an expected call of ListLogs.
func (mr *MockServiceInterfaceMockRecorder) ListLogs(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListLogs", reflect.TypeOf((*MockServiceInterface)(nil).ListLogs), ctx, req)
}

// Record mocks base method.
func (m *MockServiceInterface) Record(ctx context.Context, tx datastore.DB, entry audit.LogEntry) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Record", ctx, tx, entry)
}

// Record indicates an expected call of Record.
func (mr *MockServiceInterfaceMockRecorder) Record(ctx, tx, entry any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Record", reflect.TypeOf((*MockServiceInterface)(nil).Record), ctx, tx, entry)
}

// RecordSecurity mocks base method.
func (m *MockServiceInterface) RecordSecurity(ctx context.Context, tx datastore.DB, action, message string, userEmail, userID, ipAddress, userAgent structs.NullableString) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RecordSecurity", ctx, tx, action, message, userEmail, userID, ipAddress, userAgent)
}

// RecordSecurity indicates an expected call of RecordSecurity.
func (mr *MockServiceInterfaceMockRecorder) RecordSecurity(ctx, tx, action, message, userEmail, userID, ipAddress, userAgent any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordSecurity", reflect.TypeOf((*MockServiceInterface)(nil).RecordSecurity), ctx, tx, action, message, userEmail, userID, ipAddress, userAgent)
}

// MockRepositoryInterface is a mock of RepositoryInterface interface.
type MockRepositoryInterface struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryInterfaceMockRecorder
	isgomock struct{}
}

// MockRepositoryInterfaceMockRecorder is the mock recorder for MockRepositoryInterface.
type MockRepositoryInterfaceMockRecorder struct {
	mock *MockRepositoryInterface
}

// NewMockRepositoryInterface creates a new mock instance.
func NewMockRepositoryInterface(ctrl *gomock.Controller) *MockRepositoryInterface {
	mock := &MockRepositoryInterface{ctrl: ctrl}
	mock.recorder = &MockRepositoryInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepositoryInterface) EXPECT() *MockRepositoryInterfaceMockRecorder {
	return m.recorder
}

// DeleteLogsOlderThan mocks base method.
func (m *MockRepositoryInterface) DeleteLogsOlderThan(ctx context.Context, days int) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteLogsOlderThan", ctx, days)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteLogsOlderThan indicates an expected call of DeleteLogsOlderThan.
func (mr *MockRepositoryInterfaceMockRecorder) DeleteLogsOlderThan(ctx, days any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteLogsOlderThan", reflect.TypeOf((*MockRepositoryInterface)(nil).DeleteLogsOlderThan), ctx, days)
}

// GetActivityStats mocks base method.
func (m *MockRepositoryInterface) GetActivityStats(ctx context.Context) ([]audit.LogActivityDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActivityStats", ctx)
	ret0, _ := ret[0].([]audit.LogActivityDTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActivityStats indicates an expected call of GetActivityStats.
func (mr *MockRepositoryInterfaceMockRecorder) GetActivityStats(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActivityStats", reflect.TypeOf((*MockRepositoryInterface)(nil).GetActivityStats), ctx)
}

// GetDB mocks base method.
func (m *MockRepositoryInterface) GetDB() *sqlx.DB {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDB")
	ret0, _ := ret[0].(*sqlx.DB)
	return ret0
}

// GetDB indicates an expected call of GetDB.
func (mr *MockRepositoryInterfaceMockRecorder) GetDB() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDB", reflect.TypeOf((*MockRepositoryInterface)(nil).GetDB))
}

// GetStats mocks base method.
func (m *MockRepositoryInterface) GetStats(ctx context.Context, startDate, endDate string) ([]audit.LogStatsDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStats", ctx, startDate, endDate)
	ret0, _ := ret[0].([]audit.LogStatsDTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStats indicates an expected call of GetStats.
func (mr *MockRepositoryInterfaceMockRecorder) GetStats(ctx, startDate, endDate any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStats", reflect.TypeOf((*MockRepositoryInterface)(nil).GetStats), ctx, startDate, endDate)
}

// GetTotalCount mocks base method.
func (m *MockRepositoryInterface) GetTotalCount(ctx context.Context, category, action, userEmail, targetType, targetEmail, search, startDate, endDate string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTotalCount", ctx, category, action, userEmail, targetType, targetEmail, search, startDate, endDate)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTotalCount indicates an expected call of GetTotalCount.
func (mr *MockRepositoryInterfaceMockRecorder) GetTotalCount(ctx, category, action, userEmail, targetType, targetEmail, search, startDate, endDate any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTotalCount", reflect.TypeOf((*MockRepositoryInterface)(nil).GetTotalCount), ctx, category, action, userEmail, targetType, targetEmail, search, startDate, endDate)
}

// List mocks base method.
func (m *MockRepositoryInterface) List(ctx context.Context, offset, limit int, category, action, userEmail, targetType, targetEmail, search, startDate, endDate, orderBy string) ([]SystemLog, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, offset, limit, category, action, userEmail, targetType, targetEmail, search, startDate, endDate, orderBy)
	ret0, _ := ret[0].([]SystemLog)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockRepositoryInterfaceMockRecorder) List(ctx, offset, limit, category, action, userEmail, targetType, targetEmail, search, startDate, endDate, orderBy any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockRepositoryInterface)(nil).List), ctx, offset, limit, category, action, userEmail, targetType, targetEmail, search, startDate, endDate, orderBy)
}

// Record mocks base method.
func (m *MockRepositoryInterface) Record(ctx context.Context, tx datastore.DB, log *SystemLog) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Record", ctx, tx, log)
	ret0, _ := ret[0].(error)
	return ret0
}

// Record indicates an expected call of Record.
func (mr *MockRepositoryInterfaceMockRecorder) Record(ctx, tx, log any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Record", reflect.TypeOf((*MockRepositoryInterface)(nil).Record), ctx, tx, log)
}

// WithTransaction mocks base method.
func (m *MockRepositoryInterface) WithTransaction(ctx context.Context, fn func(datastore.DB) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithTransaction", ctx, fn)
	ret0, _ := ret[0].(error)
	return ret0
}

// WithTransaction indicates an expected call of WithTransaction.
func (mr *MockRepositoryInterfaceMockRecorder) WithTransaction(ctx, fn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithTransaction", reflect.TypeOf((*MockRepositoryInterface)(nil).WithTransaction), ctx, fn)
}
