// Code generated by MockGen. DO NOT EDIT.
// Source: internal\infrastructure\ai\classifier\interface.go
//
// Generated by this command:
//
//	mockgen -source=internal\infrastructure\ai\classifier\interface.go -package=classifier -destination=internal\infrastructure\ai\classifier\mock_service.go
//

// Package classifier is a generated GoMock package.
package classifier

import (
	context "context"
	reflect "reflect"

	config "github.com/olazo-johnalbert/duckload-api/internal/core/config"
	gomock "go.uber.org/mock/gomock"
)

// MockServiceInterface is a mock of ServiceInterface interface.
type MockServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockServiceInterfaceMockRecorder
	isgomock struct{}
}

// MockServiceInterfaceMockRecorder is the mock recorder for MockServiceInterface.
type MockServiceInterfaceMockRecorder struct {
	mock *MockServiceInterface
}

// NewMockServiceInterface creates a new mock instance.
func NewMockServiceInterface(ctrl *gomock.Controller) *MockServiceInterface {
	mock := &MockServiceInterface{ctrl: ctrl}
	mock.recorder = &MockServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockServiceInterface) EXPECT() *MockServiceInterfaceMockRecorder {
	return m.recorder
}

// Classify mocks base method.
func (m *MockServiceInterface) Classify(ctx context.Context, text string, cfg *config.Config) (*ClassifyResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Classify", ctx, text, cfg)
	ret0, _ := ret[0].(*ClassifyResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Classify indicates an expected call of Classify.
func (mr *MockServiceInterfaceMockRecorder) Classify(ctx, text, cfg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Classify", reflect.TypeOf((*MockServiceInterface)(nil).Classify), ctx, text, cfg)
}
