// Package integrations Code generated by swaggo/swag. DO NOT EDIT
package integrations

import "github.com/swaggo/swag"

const docTemplateintegrations = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/m2m/refresh": {
            "post": {
                "description": "Refreshes an existing M2M session using a valid refresh token.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "M2M Token Refresh",
                "parameters": [
                    {
                        "description": "Refresh Token",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/m2mclients.M2MRefreshTokenRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/m2mclients.M2MTokenSuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.CommonErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/response.CommonErrorResponse"
                        }
                    }
                }
            }
        },
        "/auth/m2m/token": {
            "post": {
                "description": "Exchanges client credentials (client_id and client_secret) for an M2M access token.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "M2M Token Exchange",
                "parameters": [
                    {
                        "description": "M2M Credentials",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/m2mclients.M2MTokenRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/m2mclients.M2MTokenSuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.CommonErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/response.CommonErrorResponse"
                        }
                    }
                }
            }
        },
        "/integrations/students/profiles": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Get a paginated list of students with optional filters",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "External Students"
                ],
                "summary": "List students",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Search term for student name or number",
                        "name": "search",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Filter by course ID",
                        "name": "course_id",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Filter by gender ID",
                        "name": "gender_id",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Filter by year level",
                        "name": "year_level",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Order by field (first_name, last_name, student_number, created_at, updated_at, year_level, course_id)",
                        "name": "order_by",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Page number for pagination",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Number of items per page for pagination",
                        "name": "page_size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/integrations.ListStudentsSuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.CommonErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/response.CommonErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.CommonErrorResponse"
                        }
                    }
                }
            }
        },
        "/integrations/students/{studentNumber}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Get student information by student number",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "External Students"
                ],
                "summary": "Get student by student number",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Student number of the student",
                        "name": "studentNumber",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/integrations.StudentSuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.CommonErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/response.CommonErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/response.CommonErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.CommonErrorResponse"
                        }
                    }
                }
            }
        },
        "/integrations/students/{studentNumber}/addresses": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Get all addresses of a student by their student number",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "External Students"
                ],
                "summary": "Get student addresses by student number",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Student number of the student",
                        "name": "studentNumber",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/integrations.StudentAddressSuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.CommonErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/response.CommonErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/response.CommonErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.CommonErrorResponse"
                        }
                    }
                }
            }
        },
        "/integrations/students/{studentNumber}/personal-info": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Get personal information of a student by their student number",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "External Students"
                ],
                "summary": "Get personal information by student number",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Student number of the student",
                        "name": "studentNumber",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/integrations.StudentPersonalInfoSuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.CommonErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/response.CommonErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/response.CommonErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.CommonErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "integrations.ListStudentsSuccessResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/integrations.OGOSListStudentsResponse"
                },
                "status": {
                    "allOf": [
                        {
                            "$ref": "#/definitions/response.JSendStatus"
                        }
                    ],
                    "example": "success"
                }
            }
        },
        "integrations.OGOSListStudentsResponse": {
            "type": "object",
            "properties": {
                "meta": {
                    "$ref": "#/definitions/structs.PaginationMetadata"
                },
                "students": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/integrations.OGOSStudentDTO"
                    }
                }
            }
        },
        "integrations.OGOSStudentAddressDTO": {
            "type": "object",
            "properties": {
                "addressType": {
                    "type": "string"
                },
                "barangay": {
                    "$ref": "#/definitions/locations.Barangay"
                },
                "city": {
                    "$ref": "#/definitions/locations.City"
                },
                "province": {
                    "$ref": "#/definitions/locations.ProvinceDTO"
                },
                "region": {
                    "$ref": "#/definitions/locations.Region"
                },
                "streetDetail": {
                    "type": "string"
                },
                "studentNumber": {
                    "type": "string"
                }
            }
        },
        "integrations.OGOSStudentDTO": {
            "type": "object",
            "properties": {
                "course": {
                    "$ref": "#/definitions/students.Course"
                },
                "email": {
                    "type": "string"
                },
                "firstName": {
                    "type": "string"
                },
                "lastName": {
                    "type": "string"
                },
                "middleName": {
                    "$ref": "#/definitions/structs.NullableString"
                },
                "mobileNumber": {
                    "type": "string"
                },
                "section": {
                    "type": "string"
                },
                "studentNumber": {
                    "type": "string"
                },
                "suffixName": {
                    "type": "string"
                },
                "yearLevel": {
                    "type": "integer"
                }
            }
        },
        "integrations.OGOSStudentPersonalInfoDTO": {
            "type": "object",
            "properties": {
                "dateOfBirth": {
                    "type": "string"
                },
                "gender": {
                    "$ref": "#/definitions/students.Gender"
                },
                "heightFt": {
                    "type": "number"
                },
                "placeOfBirth": {
                    "type": "string"
                },
                "studentNumber": {
                    "type": "string"
                },
                "weightKg": {
                    "type": "number"
                }
            }
        },
        "integrations.StudentAddressSuccessResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/integrations.OGOSStudentAddressDTO"
                    }
                },
                "status": {
                    "allOf": [
                        {
                            "$ref": "#/definitions/response.JSendStatus"
                        }
                    ],
                    "example": "success"
                }
            }
        },
        "integrations.StudentPersonalInfoSuccessResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/integrations.OGOSStudentPersonalInfoDTO"
                },
                "status": {
                    "allOf": [
                        {
                            "$ref": "#/definitions/response.JSendStatus"
                        }
                    ],
                    "example": "success"
                }
            }
        },
        "integrations.StudentSuccessResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/integrations.OGOSStudentDTO"
                },
                "status": {
                    "type": "string",
                    "example": "success"
                }
            }
        },
        "locations.Barangay": {
            "type": "object",
            "properties": {
                "cityId": {
                    "type": "integer"
                },
                "code": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "locations.City": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "district": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "provinceCode": {
                    "type": "string"
                },
                "regionCode": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                },
                "zipCode": {
                    "type": "string"
                }
            }
        },
        "locations.ProvinceDTO": {
            "type": "object",
            "properties": {
                "code": {
                    "$ref": "#/definitions/structs.NullableString"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "$ref": "#/definitions/structs.NullableString"
                },
                "regionCode": {
                    "$ref": "#/definitions/structs.NullableString"
                }
            }
        },
        "locations.Region": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "m2mclients.M2MRefreshTokenRequest": {
            "type": "object",
            "required": [
                "refreshToken"
            ],
            "properties": {
                "refreshToken": {
                    "type": "string"
                }
            }
        },
        "m2mclients.M2MTokenRequest": {
            "type": "object",
            "required": [
                "clientId",
                "clientSecret"
            ],
            "properties": {
                "clientId": {
                    "type": "string"
                },
                "clientSecret": {
                    "type": "string"
                }
            }
        },
        "m2mclients.M2MTokenResponse": {
            "type": "object",
            "properties": {
                "accessToken": {
                    "type": "string"
                },
                "expiresIn": {
                    "description": "Seconds",
                    "type": "integer"
                },
                "refreshToken": {
                    "type": "string"
                },
                "tokenType": {
                    "type": "string"
                }
            }
        },
        "m2mclients.M2MTokenSuccessResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/m2mclients.M2MTokenResponse"
                },
                "status": {
                    "type": "string",
                    "example": "success"
                }
            }
        },
        "response.CommonErrorResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer",
                    "example": 400
                },
                "data": {},
                "message": {
                    "type": "string",
                    "example": "Detailed error message"
                },
                "status": {
                    "type": "string",
                    "example": "fail"
                }
            }
        },
        "response.JSendStatus": {
            "type": "string",
            "enum": [
                "success",
                "fail",
                "error"
            ],
            "x-enum-varnames": [
                "StatusSuccess",
                "StatusFail",
                "StatusError"
            ]
        },
        "structs.NullableString": {
            "type": "object",
            "properties": {
                "string": {
                    "type": "string"
                },
                "valid": {
                    "description": "Valid is true if String is not NULL",
                    "type": "boolean"
                }
            }
        },
        "structs.PaginationMetadata": {
            "type": "object",
            "properties": {
                "page": {
                    "type": "integer"
                },
                "pagesSize": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                },
                "totalPages": {
                    "type": "integer"
                }
            }
        },
        "students.Course": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "students.Gender": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfointegrations holds exported Swagger Info so clients can modify it
var SwaggerInfointegrations = &swag.Spec{
	Version:          "2.0",
	Host:             "",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Student data API",
	Description:      "",
	InfoInstanceName: "integrations",
	SwaggerTemplate:  docTemplateintegrations,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfointegrations.InstanceName(), SwaggerInfointegrations)
}
