// Code generated by MockGen. DO NOT EDIT.
// Source: C:\Users\JA\school_programming\capstone\DuckLoadLogic-Capstone\ogos-gin-api\internal\features\appointments\interface.go
//
// Generated by this command:
//
//	mockgen -source=C:\Users\JA\school_programming\capstone\DuckLoadLogic-Capstone\ogos-gin-api\internal\features\appointments\interface.go -package=appointments -destination=C:\Users\JA\school_programming\capstone\DuckLoadLogic-Capstone\ogos-gin-api\internal\features\appointments\mock_interfaces_test.go
//

// Package appointments is a generated GoMock package.
package appointments

import (
	context "context"
	reflect "reflect"

	sqlx "github.com/jmoiron/sqlx"
	config "github.com/olazo-johnalbert/duckload-api/internal/core/config"
	datastore "github.com/olazo-johnalbert/duckload-api/internal/infrastructure/datastore"
	gomock "go.uber.org/mock/gomock"
)

// MockServiceInterface is a mock of ServiceInterface interface.
type MockServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockServiceInterfaceMockRecorder
	isgomock struct{}
}

// MockServiceInterfaceMockRecorder is the mock recorder for MockServiceInterface.
type MockServiceInterfaceMockRecorder struct {
	mock *MockServiceInterface
}

// NewMockServiceInterface creates a new mock instance.
func NewMockServiceInterface(ctrl *gomock.Controller) *MockServiceInterface {
	mock := &MockServiceInterface{ctrl: ctrl}
	mock.recorder = &MockServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockServiceInterface) EXPECT() *MockServiceInterfaceMockRecorder {
	return m.recorder
}

// CreateAppointment mocks base method.
func (m *MockServiceInterface) CreateAppointment(ctx context.Context, iirID string, req AppointmentDTO, cfg *config.Config) (*Appointment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAppointment", ctx, iirID, req, cfg)
	ret0, _ := ret[0].(*Appointment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateAppointment indicates an expected call of CreateAppointment.
func (mr *MockServiceInterfaceMockRecorder) CreateAppointment(ctx, iirID, req, cfg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAppointment", reflect.TypeOf((*MockServiceInterface)(nil).CreateAppointment), ctx, iirID, req, cfg)
}

// GetAppointmentByID mocks base method.
func (m *MockServiceInterface) GetAppointmentByID(ctx context.Context, id string) (*AppointmentDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAppointmentByID", ctx, id)
	ret0, _ := ret[0].(*AppointmentDTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAppointmentByID indicates an expected call of GetAppointmentByID.
func (mr *MockServiceInterfaceMockRecorder) GetAppointmentByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAppointmentByID", reflect.TypeOf((*MockServiceInterface)(nil).GetAppointmentByID), ctx, id)
}

// GetAppointmentStats mocks base method.
func (m *MockServiceInterface) GetAppointmentStats(ctx context.Context, req ListAppointmentsRequest, iirID *string) ([]StatusCount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAppointmentStats", ctx, req, iirID)
	ret0, _ := ret[0].([]StatusCount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAppointmentStats indicates an expected call of GetAppointmentStats.
func (mr *MockServiceInterfaceMockRecorder) GetAppointmentStats(ctx, req, iirID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAppointmentStats", reflect.TypeOf((*MockServiceInterface)(nil).GetAppointmentStats), ctx, req, iirID)
}

// GetAppointmentStatuses mocks base method.
func (m *MockServiceInterface) GetAppointmentStatuses(ctx context.Context) ([]AppointmentStatus, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAppointmentStatuses", ctx)
	ret0, _ := ret[0].([]AppointmentStatus)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAppointmentStatuses indicates an expected call of GetAppointmentStatuses.
func (mr *MockServiceInterfaceMockRecorder) GetAppointmentStatuses(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAppointmentStatuses", reflect.TypeOf((*MockServiceInterface)(nil).GetAppointmentStatuses), ctx)
}

// GetAppointmentsByIIRID mocks base method.
func (m *MockServiceInterface) GetAppointmentsByIIRID(ctx context.Context, iirID string, req ListAppointmentsRequest) (*ListAppointmentsDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAppointmentsByIIRID", ctx, iirID, req)
	ret0, _ := ret[0].(*ListAppointmentsDTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAppointmentsByIIRID indicates an expected call of GetAppointmentsByIIRID.
func (mr *MockServiceInterfaceMockRecorder) GetAppointmentsByIIRID(ctx, iirID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAppointmentsByIIRID", reflect.TypeOf((*MockServiceInterface)(nil).GetAppointmentsByIIRID), ctx, iirID, req)
}

// GetAppointmentsByUserID mocks base method.
func (m *MockServiceInterface) GetAppointmentsByUserID(ctx context.Context, userID string, req ListAppointmentsRequest) (*ListAppointmentsDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAppointmentsByUserID", ctx, userID, req)
	ret0, _ := ret[0].(*ListAppointmentsDTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAppointmentsByUserID indicates an expected call of GetAppointmentsByUserID.
func (mr *MockServiceInterfaceMockRecorder) GetAppointmentsByUserID(ctx, userID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAppointmentsByUserID", reflect.TypeOf((*MockServiceInterface)(nil).GetAppointmentsByUserID), ctx, userID, req)
}

// GetAvailableTimeSlots mocks base method.
func (m *MockServiceInterface) GetAvailableTimeSlots(ctx context.Context, date string) ([]AvailableTimeSlotView, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAvailableTimeSlots", ctx, date)
	ret0, _ := ret[0].([]AvailableTimeSlotView)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAvailableTimeSlots indicates an expected call of GetAvailableTimeSlots.
func (mr *MockServiceInterfaceMockRecorder) GetAvailableTimeSlots(ctx, date any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAvailableTimeSlots", reflect.TypeOf((*MockServiceInterface)(nil).GetAvailableTimeSlots), ctx, date)
}

// GetConcernCategories mocks base method.
func (m *MockServiceInterface) GetConcernCategories(ctx context.Context) ([]AppointmentCategory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConcernCategories", ctx)
	ret0, _ := ret[0].([]AppointmentCategory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetConcernCategories indicates an expected call of GetConcernCategories.
func (mr *MockServiceInterfaceMockRecorder) GetConcernCategories(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConcernCategories", reflect.TypeOf((*MockServiceInterface)(nil).GetConcernCategories), ctx)
}

// GetDailyStatusCount mocks base method.
func (m *MockServiceInterface) GetDailyStatusCount(ctx context.Context, startDate string) ([]DailyStatusCount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDailyStatusCount", ctx, startDate)
	ret0, _ := ret[0].([]DailyStatusCount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDailyStatusCount indicates an expected call of GetDailyStatusCount.
func (mr *MockServiceInterfaceMockRecorder) GetDailyStatusCount(ctx, startDate any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDailyStatusCount", reflect.TypeOf((*MockServiceInterface)(nil).GetDailyStatusCount), ctx, startDate)
}

// GetUserIDByAppointmentID mocks base method.
func (m *MockServiceInterface) GetUserIDByAppointmentID(ctx context.Context, id string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserIDByAppointmentID", ctx, id)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserIDByAppointmentID indicates an expected call of GetUserIDByAppointmentID.
func (mr *MockServiceInterfaceMockRecorder) GetUserIDByAppointmentID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserIDByAppointmentID", reflect.TypeOf((*MockServiceInterface)(nil).GetUserIDByAppointmentID), ctx, id)
}

// ListAppointments mocks base method.
func (m *MockServiceInterface) ListAppointments(ctx context.Context, req ListAppointmentsRequest) (*ListAppointmentsDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAppointments", ctx, req)
	ret0, _ := ret[0].(*ListAppointmentsDTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAppointments indicates an expected call of ListAppointments.
func (mr *MockServiceInterfaceMockRecorder) ListAppointments(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAppointments", reflect.TypeOf((*MockServiceInterface)(nil).ListAppointments), ctx, req)
}

// UpdateAppointment mocks base method.
func (m *MockServiceInterface) UpdateAppointment(ctx context.Context, id string, req AppointmentDTO) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAppointment", ctx, id, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateAppointment indicates an expected call of UpdateAppointment.
func (mr *MockServiceInterfaceMockRecorder) UpdateAppointment(ctx, id, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAppointment", reflect.TypeOf((*MockServiceInterface)(nil).UpdateAppointment), ctx, id, req)
}

// MockRepositoryInterface is a mock of RepositoryInterface interface.
type MockRepositoryInterface struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryInterfaceMockRecorder
	isgomock struct{}
}

// MockRepositoryInterfaceMockRecorder is the mock recorder for MockRepositoryInterface.
type MockRepositoryInterfaceMockRecorder struct {
	mock *MockRepositoryInterface
}

// NewMockRepositoryInterface creates a new mock instance.
func NewMockRepositoryInterface(ctrl *gomock.Controller) *MockRepositoryInterface {
	mock := &MockRepositoryInterface{ctrl: ctrl}
	mock.recorder = &MockRepositoryInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepositoryInterface) EXPECT() *MockRepositoryInterfaceMockRecorder {
	return m.recorder
}

// CreateAppointment mocks base method.
func (m *MockRepositoryInterface) CreateAppointment(ctx context.Context, tx datastore.DB, appt *Appointment) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAppointment", ctx, tx, appt)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateAppointment indicates an expected call of CreateAppointment.
func (mr *MockRepositoryInterfaceMockRecorder) CreateAppointment(ctx, tx, appt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAppointment", reflect.TypeOf((*MockRepositoryInterface)(nil).CreateAppointment), ctx, tx, appt)
}

// GetAppointment mocks base method.
func (m *MockRepositoryInterface) GetAppointment(ctx context.Context, id string) (*AppointmentWithDetailsView, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAppointment", ctx, id)
	ret0, _ := ret[0].(*AppointmentWithDetailsView)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAppointment indicates an expected call of GetAppointment.
func (mr *MockRepositoryInterfaceMockRecorder) GetAppointment(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAppointment", reflect.TypeOf((*MockRepositoryInterface)(nil).GetAppointment), ctx, id)
}

// GetAppointmentCategoryByID mocks base method.
func (m *MockRepositoryInterface) GetAppointmentCategoryByID(ctx context.Context, id int) (*AppointmentCategory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAppointmentCategoryByID", ctx, id)
	ret0, _ := ret[0].(*AppointmentCategory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAppointmentCategoryByID indicates an expected call of GetAppointmentCategoryByID.
func (mr *MockRepositoryInterfaceMockRecorder) GetAppointmentCategoryByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAppointmentCategoryByID", reflect.TypeOf((*MockRepositoryInterface)(nil).GetAppointmentCategoryByID), ctx, id)
}

// GetAppointmentStats mocks base method.
func (m *MockRepositoryInterface) GetAppointmentStats(ctx context.Context, statusID, startDate, endDate string, iirID *string) ([]StatusCount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAppointmentStats", ctx, statusID, startDate, endDate, iirID)
	ret0, _ := ret[0].([]StatusCount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAppointmentStats indicates an expected call of GetAppointmentStats.
func (mr *MockRepositoryInterfaceMockRecorder) GetAppointmentStats(ctx, statusID, startDate, endDate, iirID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAppointmentStats", reflect.TypeOf((*MockRepositoryInterface)(nil).GetAppointmentStats), ctx, statusID, startDate, endDate, iirID)
}

// GetAvailableTimeSlots mocks base method.
func (m *MockRepositoryInterface) GetAvailableTimeSlots(ctx context.Context, date string) ([]AvailableTimeSlotView, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAvailableTimeSlots", ctx, date)
	ret0, _ := ret[0].([]AvailableTimeSlotView)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAvailableTimeSlots indicates an expected call of GetAvailableTimeSlots.
func (mr *MockRepositoryInterfaceMockRecorder) GetAvailableTimeSlots(ctx, date any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAvailableTimeSlots", reflect.TypeOf((*MockRepositoryInterface)(nil).GetAvailableTimeSlots), ctx, date)
}

// GetCategories mocks base method.
func (m *MockRepositoryInterface) GetCategories(ctx context.Context) ([]AppointmentCategory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCategories", ctx)
	ret0, _ := ret[0].([]AppointmentCategory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCategories indicates an expected call of GetCategories.
func (mr *MockRepositoryInterfaceMockRecorder) GetCategories(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCategories", reflect.TypeOf((*MockRepositoryInterface)(nil).GetCategories), ctx)
}

// GetDB mocks base method.
func (m *MockRepositoryInterface) GetDB() *sqlx.DB {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDB")
	ret0, _ := ret[0].(*sqlx.DB)
	return ret0
}

// GetDB indicates an expected call of GetDB.
func (mr *MockRepositoryInterfaceMockRecorder) GetDB() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDB", reflect.TypeOf((*MockRepositoryInterface)(nil).GetDB))
}

// GetDailyStatusCount mocks base method.
func (m *MockRepositoryInterface) GetDailyStatusCount(ctx context.Context, startDate, endDate string) ([]DailyStatusCount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDailyStatusCount", ctx, startDate, endDate)
	ret0, _ := ret[0].([]DailyStatusCount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDailyStatusCount indicates an expected call of GetDailyStatusCount.
func (mr *MockRepositoryInterfaceMockRecorder) GetDailyStatusCount(ctx, startDate, endDate any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDailyStatusCount", reflect.TypeOf((*MockRepositoryInterface)(nil).GetDailyStatusCount), ctx, startDate, endDate)
}

// GetStatusByID mocks base method.
func (m *MockRepositoryInterface) GetStatusByID(ctx context.Context, id int) (*AppointmentStatus, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStatusByID", ctx, id)
	ret0, _ := ret[0].(*AppointmentStatus)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStatusByID indicates an expected call of GetStatusByID.
func (mr *MockRepositoryInterfaceMockRecorder) GetStatusByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStatusByID", reflect.TypeOf((*MockRepositoryInterface)(nil).GetStatusByID), ctx, id)
}

// GetStatuses mocks base method.
func (m *MockRepositoryInterface) GetStatuses(ctx context.Context) ([]AppointmentStatus, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStatuses", ctx)
	ret0, _ := ret[0].([]AppointmentStatus)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStatuses indicates an expected call of GetStatuses.
func (mr *MockRepositoryInterfaceMockRecorder) GetStatuses(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStatuses", reflect.TypeOf((*MockRepositoryInterface)(nil).GetStatuses), ctx)
}

// GetTimeSlotByID mocks base method.
func (m *MockRepositoryInterface) GetTimeSlotByID(ctx context.Context, id int) (*TimeSlot, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTimeSlotByID", ctx, id)
	ret0, _ := ret[0].(*TimeSlot)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTimeSlotByID indicates an expected call of GetTimeSlotByID.
func (mr *MockRepositoryInterfaceMockRecorder) GetTimeSlotByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTimeSlotByID", reflect.TypeOf((*MockRepositoryInterface)(nil).GetTimeSlotByID), ctx, id)
}

// GetTimeSlots mocks base method.
func (m *MockRepositoryInterface) GetTimeSlots(ctx context.Context, date string) ([]TimeSlot, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTimeSlots", ctx, date)
	ret0, _ := ret[0].([]TimeSlot)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTimeSlots indicates an expected call of GetTimeSlots.
func (mr *MockRepositoryInterfaceMockRecorder) GetTimeSlots(ctx, date any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTimeSlots", reflect.TypeOf((*MockRepositoryInterface)(nil).GetTimeSlots), ctx, date)
}

// GetTotalAppointmentsCount mocks base method.
func (m *MockRepositoryInterface) GetTotalAppointmentsCount(ctx context.Context, statusID, startDate, endDate string, iirID *string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTotalAppointmentsCount", ctx, statusID, startDate, endDate, iirID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTotalAppointmentsCount indicates an expected call of GetTotalAppointmentsCount.
func (mr *MockRepositoryInterfaceMockRecorder) GetTotalAppointmentsCount(ctx, statusID, startDate, endDate, iirID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTotalAppointmentsCount", reflect.TypeOf((*MockRepositoryInterface)(nil).GetTotalAppointmentsCount), ctx, statusID, startDate, endDate, iirID)
}

// GetUserIDByAppointmentID mocks base method.
func (m *MockRepositoryInterface) GetUserIDByAppointmentID(ctx context.Context, id string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserIDByAppointmentID", ctx, id)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserIDByAppointmentID indicates an expected call of GetUserIDByAppointmentID.
func (mr *MockRepositoryInterfaceMockRecorder) GetUserIDByAppointmentID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserIDByAppointmentID", reflect.TypeOf((*MockRepositoryInterface)(nil).GetUserIDByAppointmentID), ctx, id)
}

// List mocks base method.
func (m *MockRepositoryInterface) List(ctx context.Context, offset, limit int, search, orderBy, statusIDs, startDate, endDate string) ([]AppointmentWithDetailsView, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, offset, limit, search, orderBy, statusIDs, startDate, endDate)
	ret0, _ := ret[0].([]AppointmentWithDetailsView)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockRepositoryInterfaceMockRecorder) List(ctx, offset, limit, search, orderBy, statusIDs, startDate, endDate any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockRepositoryInterface)(nil).List), ctx, offset, limit, search, orderBy, statusIDs, startDate, endDate)
}

// ListByIIRID mocks base method.
func (m *MockRepositoryInterface) ListByIIRID(ctx context.Context, iirID string, offset, limit int, orderBy, statusID, startDate, endDate string) ([]AppointmentWithDetailsView, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByIIRID", ctx, iirID, offset, limit, orderBy, statusID, startDate, endDate)
	ret0, _ := ret[0].([]AppointmentWithDetailsView)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByIIRID indicates an expected call of ListByIIRID.
func (mr *MockRepositoryInterfaceMockRecorder) ListByIIRID(ctx, iirID, offset, limit, orderBy, statusID, startDate, endDate any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByIIRID", reflect.TypeOf((*MockRepositoryInterface)(nil).ListByIIRID), ctx, iirID, offset, limit, orderBy, statusID, startDate, endDate)
}

// ListByUserID mocks base method.
func (m *MockRepositoryInterface) ListByUserID(ctx context.Context, userID string, offset, limit int, orderBy, statusID, startDate, endDate string) ([]AppointmentWithDetailsView, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByUserID", ctx, userID, offset, limit, orderBy, statusID, startDate, endDate)
	ret0, _ := ret[0].([]AppointmentWithDetailsView)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByUserID indicates an expected call of ListByUserID.
func (mr *MockRepositoryInterfaceMockRecorder) ListByUserID(ctx, userID, offset, limit, orderBy, statusID, startDate, endDate any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByUserID", reflect.TypeOf((*MockRepositoryInterface)(nil).ListByUserID), ctx, userID, offset, limit, orderBy, statusID, startDate, endDate)
}

// UpdateAppointment mocks base method.
func (m *MockRepositoryInterface) UpdateAppointment(ctx context.Context, tx datastore.DB, appt Appointment) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAppointment", ctx, tx, appt)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateAppointment indicates an expected call of UpdateAppointment.
func (mr *MockRepositoryInterfaceMockRecorder) UpdateAppointment(ctx, tx, appt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAppointment", reflect.TypeOf((*MockRepositoryInterface)(nil).UpdateAppointment), ctx, tx, appt)
}

// WithTransaction mocks base method.
func (m *MockRepositoryInterface) WithTransaction(ctx context.Context, fn func(datastore.DB) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithTransaction", ctx, fn)
	ret0, _ := ret[0].(error)
	return ret0
}

// WithTransaction indicates an expected call of WithTransaction.
func (mr *MockRepositoryInterfaceMockRecorder) WithTransaction(ctx, fn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithTransaction", reflect.TypeOf((*MockRepositoryInterface)(nil).WithTransaction), ctx, fn)
}
