// Code generated by MockGen. DO NOT EDIT.
// Source: internal/features/appointments/repository.go
//
// Generated by this command:
//
//	mockgen -source=internal/features/appointments/repository.go -destination=internal/features/appointments/mock_repository.go -package=appointments
//

// Package appointments is a generated GoMock package.
package appointments
