name: Check PR Source Branch

on:
    pull_request:
        branches:
            - main

jobs:
    check-branch:
        runs-on: ubuntu-latest
        steps:
            - name: Check if source is dev
              if: github.head_ref != 'dev'
              run: |
                  echo "ERROR: Only merges from 'dev' are allowed into 'main'!"
                  exit 1
